var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(l,q){if(b){var u=require("fs").readFileSync(l);return(new Uint8Array(u)).buffer}h.dataFileDownloads||(h.dataFileDownloads={});try{var v=await fetch(l)}catch(C){throw Error(`Network Error: ${l}`,
{e:C});}if(!v.ok)throw Error(`${v.status}: ${v.url}`);u=[];q=Number(v.headers.get("Content-Length")||q);let E=0;h.setStatus&&h.setStatus("Downloading data...");for(v=v.body.getReader();;){var {done:F,value:P}=await v.read();if(F)break;u.push(P);E+=P.length;h.dataFileDownloads[l]={loaded:E,total:q};let C=0,T=0;for(var I of Object.values(h.dataFileDownloads))C+=I.loaded,T+=I.total;h.setStatus&&h.setStatus(`Downloading data... (${C}/${T})`)}l=new Uint8Array(u.map(C=>C.length).reduce((C,T)=>C+T,0));I=
0;for(const C of u)l.set(C,I),I+=C.length;return l.buffer}async function e(l){l.FS_createPath("/","Assets",!0,!0);l.FS_createPath("/Assets","Scenes",!0,!0);l.FS_createPath("/Assets","Scripts",!0,!0);l.FS_createPath("/Assets/Scripts","Box2D",!0,!0);l.FS_createPath("/Assets","Sprites",!0,!0);l.FS_createPath("/","assets",!0,!0);l.FS_createPath("/assets","builtin",!0,!0);for(var q of c.files)l.addRunDependency(`fp ${q.filename}`);l.addRunDependency("datafile_build/web/Box2D/index.data");l.preloadResults||
(l.preloadResults={});l.preloadResults["build/web/Box2D/index.data"]={sf:!1};n||=await k;(async function(u){if(!u)throw Error("Loading data file failed.");if(u.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+u.constructor.name);u=new Uint8Array(u);for(var v of c.files){var E=v.filename;l.FS_createDataFile(E,null,u.subarray(v.start,v.end),!0,!0,!0);l.removeRunDependency(`fp ${E}`)}l.removeRunDependency("datafile_build/web/Box2D/index.data")})(n)}"object"===typeof window?
window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=c.remote_package_size,k,n=h.getPreloadedPackage&&h.getPreloadedPackage(f,g);n||(k=d(f,g));h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))})({files:[{filename:"/Assets/.DS_Store",
start:0,end:6148},{filename:"/Assets/Inter_24pt-Medium.cowfont",start:6148,end:7714},{filename:"/Assets/Inter_24pt-Medium.png",start:7714,end:14780},{filename:"/Assets/Scenes/Box2DTumbler.json",start:14780,end:24127},{filename:"/Assets/Scripts/.DS_Store",start:24127,end:30275},{filename:"/Assets/Scripts/Box2D/.DS_Store",start:30275,end:36423},{filename:"/Assets/Scripts/Box2D/TumblerStressTest.bf",start:36423,end:44374},{filename:"/Assets/Scripts/Box2D/TumblerUiController.bf",start:44374,end:46435},
{filename:"/Assets/Sprites/palette.ktx2",start:46435,end:46823},{filename:"/Assets/_texsizes.txt",start:46823,end:47047},{filename:"/Assets/project.json",start:47047,end:48578},{filename:"/assets/builtin/Background.ktx2",start:48578,end:48958},{filename:"/assets/builtin/Checkmark.ktx2",start:48958,end:49459},{filename:"/assets/builtin/Knob.ktx2",start:49459,end:49989},{filename:"/assets/builtin/UIMask.ktx2",start:49989,end:50414},{filename:"/assets/builtin/UISprite.ktx2",start:50414,end:50839}],remote_package_size:50839})}})();
var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),m=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),p,r,qa,ra,t,w,x,y,sa;
function ta(){var a=ua.buffer;p=new Int8Array(a);qa=new Int16Array(a);r=new Uint8Array(a);ra=new Uint16Array(a);t=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);sa=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a="Aborted("+a+")";m(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){m(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ya(a){var b=va;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){m(`wasm streaming compile failed: ${d}`),m("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=0,Fa=null,Ga=()=>{Ea--;h.monitorRunDependencies?.(Ea);if(0==Ea&&Fa){var a=Fa;Fa=null;a()}},Ha=()=>{Ea++;h.monitorRunDependencies?.(Ea)},Ia=!0,Ja=new TextDecoder,Ka=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},A=(a,b,c)=>a?Ja.decode(r.subarray(a,Ka(r,a,b,c))):"",Ma=()=>{var a=t[+La>>2];La+=4;return a},Na=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):
".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Na(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Qa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ra=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>
crypto.getRandomValues(b)},Sa=a=>{(Sa=Ra())(a)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Na(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ua=a=>{var b=Ka(a,0);return Ja.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Xa=a=>{var b=Array(Wa(a)+1);a=B(a,b,0,b.length);
b.length=a;return b},Ya=[];function Za(a,b){Ya[a]={input:[],output:[],$c:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.$c.fsync(a.tty)},fsync(a){a.tty.$c.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.$c.me)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.$c.me(a.tty)}catch(k){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.$c.Wd)throw new D(60);try{for(var e=0;e<d;e++)a.tty.$c.Wd(a.tty,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bb={me(){a:{if(!Va.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Xa(a)}a=Va.shift()}return a},Wd(a,b){null===b||10===b?(ma(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(Ua(a.output)),a.output=[])},Le(){return{cf:25856,ef:5,bf:191,df:35387,af:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Me(){return 0},Ne(){return[24,80]}},cb={Wd(a,b){null===b||10===b?(m(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(m(Ua(a.output)),a.output=[])}},G={Xc:null,Zc(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);G.Xc||(G.Xc={dir:{node:{Sc:G.Ic.Sc,
Yc:G.Ic.Yc,lookup:G.Ic.lookup,zd:G.Ic.zd,rename:G.Ic.rename,unlink:G.Ic.unlink,rmdir:G.Ic.rmdir,readdir:G.Ic.readdir,symlink:G.Ic.symlink},stream:{Wc:G.Gc.Wc}},file:{node:{Sc:G.Ic.Sc,Yc:G.Ic.Yc},stream:{Wc:G.Gc.Wc,read:G.Gc.read,write:G.Gc.write,Td:G.Gc.Td,re:G.Gc.re}},link:{node:{Sc:G.Ic.Sc,Yc:G.Ic.Yc,readlink:G.Ic.readlink},stream:{}},he:{node:{Sc:G.Ic.Sc,Yc:G.Ic.Yc},stream:db}});c=eb(a,b,c,d);H(c.mode)?(c.Ic=G.Xc.dir.node,c.Gc=G.Xc.dir.stream,c.Hc={}):32768===(c.mode&61440)?(c.Ic=G.Xc.file.node,
c.Gc=G.Xc.file.stream,c.Jc=0,c.Hc=null):40960===(c.mode&61440)?(c.Ic=G.Xc.link.node,c.Gc=G.Xc.link.stream):8192===(c.mode&61440)&&(c.Ic=G.Xc.he.node,c.Gc=G.Xc.he.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Hc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},vf(a){return a.Hc?a.Hc.subarray?a.Hc.subarray(0,a.Jc):new Uint8Array(a.Hc):new Uint8Array(0)},Ic:{Sc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.Jc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Yc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Jc!=b&&(0==b?(a.Hc=null,a.Jc=0):(c=a.Hc,a.Hc=new Uint8Array(b),c&&a.Hc.set(c.subarray(0,Math.min(b,a.Jc))),a.Jc=b)))},lookup(){G.Kd||(G.Kd=new D(44),G.Kd.stack="<generic error, no stack>");
throw G.Kd;},zd(a,b,c,d){return G.createNode(a,b,c,d)},rename(a,b,c){try{var d=fb(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Hc)throw new D(55);gb(d)}delete a.parent.Hc[a.name];b.Hc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Hc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=fb(a,b),d;for(d in c.Hc)throw new D(55);delete a.Hc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Hc)]},symlink(a,b,c){a=G.createNode(a,b,41471,
0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},Gc:{read(a,b,c,d,e){var f=a.node.Hc;if(e>=a.node.Jc)return 0;a=Math.min(a.node.Jc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Hc||a.Hc.subarray)){if(f)return a.Hc=b.subarray(c,c+d),a.Jc=d;if(0===a.Jc&&0===e)return a.Hc=b.slice(c,c+d),a.Jc=d;
if(e+d<=a.Jc)return a.Hc.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Hc?a.Hc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Hc,a.Hc=new Uint8Array(f),0<a.Jc&&a.Hc.set(g.subarray(0,a.Jc),0));if(a.Hc.subarray&&b.subarray)a.Hc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Hc[e+f]=b[c+f];a.Jc=Math.max(a.Jc,e+d);return d},Wc(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Jc);if(0>b)throw new D(28);return b},Td(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new D(43);a=a.node.Hc;if(e&2||!a||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{qd:e,Xe:d}},re(a,b,c,d){G.Gc.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=async a=>{a=await ja(a);return new Uint8Array(a)},jb=[],kb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.wf();for(var c of jb)if(c.canHandle(b))return c.handle(a,
b);return a},lb=null,mb={},nb=[],ob=1,pb=null,qb=!1,rb=!0,sb={},D=class{name="ErrnoError";constructor(a){this.Kc=a}},tb=class{Fc={};node=null;get flags(){return this.Fc.flags}set flags(a){this.Fc.flags=a}get position(){return this.Fc.position}set position(a){this.Fc.position=a}},ub=class{Ic={};Gc={};ld=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Zc=a.Zc;this.id=ob++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Pe(){return H(this.mode)}get Oe(){return 8192===(this.mode&61440)}};
function vb(a,b={}){if(!a)throw new D(44);b.Nd??(b.Nd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=lb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Pa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oa(e+"/"+a[f]);try{d=fb(d,a[f])}catch(k){if(44===k?.Kc&&g&&b.Re)return{path:e};throw k;}!d.ld||g&&!b.Nd||(d=d.ld.root);if(40960===(d.mode&61440)&&(!g||b.td)){if(!d.Ic.readlink)throw new D(52);
d=d.Ic.readlink(d);"/"===d.charAt(0)||(d=Pa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.Zc.qe,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}
function gb(a){var b=xb(a.parent.id,a.name);if(pb[b]===a)pb[b]=a.md;else for(b=pb[b];b;){if(b.md===a){b.md=a.md;break}b=b.md}}function fb(a,b){var c=H(a.mode)?(c=yb(a,"x"))?c:a.Ic.lookup?0:2:54;if(c)throw new D(c);for(c=pb[xb(a.id,b)];c;c=c.md){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ic.lookup(a,b)}function eb(a,b,c,d){a=new ub(a,b,c,d);b=xb(a.parent.id,a.name);a.md=pb[b];return pb[b]=a}function H(a){return 16384===(a&61440)}
function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){if(!H(a.mode))return 54;try{return fb(a,b),20}catch(c){}return yb(a,"wx")}
function Bb(a,b,c){try{var d=fb(a,b)}catch(e){return e.Kc}if(a=yb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(d===d.parent||"/"===wb(d))return 10}else if(H(d.mode))return 31;return 0}function Cb(a){if(!a)throw new D(63);return a}function Db(a){a=nb[a];if(!a)throw new D(8);return a}function Eb(a,b=-1){a=Object.assign(new tb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!nb[b])break a;throw new D(33);}a.fd=b;return nb[b]=a}function Fb(a,b=-1){a=Eb(a,b);a.Gc?.nf?.(a);return a}
function Gb(a,b){var c=null?.Gc.Yc,d=c?null:a;c??=a.Ic.Yc;Cb(c);c(d,b)}var db={open(a){a.Gc=mb[a.node.rdev].Gc;a.Gc.open?.(a)},Wc(){throw new D(70);}};function $a(a,b){mb[a]={Gc:b}}function Hb(a,b){var c="/"===b;if(c&&lb)throw new D(10);if(!c&&b){var d=vb(b,{Nd:!1});b=d.path;d=d.node;if(d.ld)throw new D(10);if(!H(d.mode))throw new D(54);}b={type:a,Af:{},qe:b,Qe:[]};a=a.Zc(b);a.Zc=b;b.root=a;c?lb=a:d&&(d.ld=b,d.Zc&&d.Zc.Qe.push(b))}
function Ib(a,b,c){var d=vb(a,{parent:!0}).node;a=Qa(a);if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=Ab(d,a);if(e)throw new D(e);if(!d.Ic.zd)throw new D(63);return d.Ic.zd(d,a,b,c)}function Jb(a,b=438){return Ib(a,b&4095|32768,0)}function J(a){return Ib(a,16895,0)}function Kb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ib(a,b|8192,c)}
function Lb(a,b){if(!Ta(a))throw new D(44);var c=vb(b,{parent:!0}).node;if(!c)throw new D(44);b=Qa(b);var d=Ab(c,b);if(d)throw new D(d);if(!c.Ic.symlink)throw new D(63);c.Ic.symlink(c,b,a)}function Mb(a){var b=vb(a,{parent:!0}).node;a=Qa(a);var c=fb(b,a),d=Bb(b,a,!0);if(d)throw new D(d);if(!b.Ic.rmdir)throw new D(63);if(c.ld)throw new D(10);b.Ic.rmdir(b,a);gb(c)}
function Nb(a){var b=vb(a,{parent:!0}).node;if(!b)throw new D(44);a=Qa(a);var c=fb(b,a),d=Bb(b,a,!1);if(d)throw new D(d);if(!b.Ic.unlink)throw new D(63);if(c.ld)throw new D(10);b.Ic.unlink(b,a);gb(c)}function Ob(a,b){a=vb(a,{td:!b}).node;return Cb(a.Ic.Sc)(a)}function Pb(a,b){a="string"==typeof a?vb(a,{td:!0}).node:a;Gb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),mf:void 0})}
function Qb(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=vb(a,{td:!(b&131072),Re:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Ib(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new D(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:H(d.mode)&&("r"!==zb(b)||b&576)?31:yb(d,zb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?vb(e,{td:!0}).node:e;if(H(e.mode))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=yb(e,"w");if(g)throw new D(g);Gb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:d,path:wb(d),flags:b,seekable:!0,position:0,Gc:d.Gc,Ve:[],error:!1});e.Gc.open&&e.Gc.open(e);f&&Pb(d,c&511);!h.logReadFiles||b&1||a in sb||(sb[a]=1);return e}
function Rb(a){if(null===a.fd)throw new D(8);a.Pd&&(a.Pd=null);try{a.Gc.close&&a.Gc.close(a)}catch(b){throw b;}finally{nb[a.fd]=null}a.fd=null}function Sb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.Gc.Wc)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.Gc.Wc(a,b,c);a.Ve=[]}
function Tb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(H(a.node.mode))throw new D(31);if(!a.Gc.write)throw new D(28);a.seekable&&a.flags&1024&&Sb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.Gc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ub(a,b){a="string"==typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oa(a+"/"+c);try{J(d)}catch(e){if(20!=e.Kc)throw e;}a=d}}return d}function Vb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);return Jb(a,hb(c,d))}
function Wb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:wb(a),g=b?Oa(a+"/"+b):a);a=hb(d,e);g=Jb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Pb(g,a|146);b=Qb(g,577);Tb(b,c,0,c.length,0,f);Rb(b);Pb(g,a)}}
function Xb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);b=hb(!!c,!!d);Xb.oe??(Xb.oe=64);var e=Xb.oe++<<8|0;$a(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,n){for(var l=0,q=0;q<n;q++){try{var u=c()}catch(v){throw new D(29);}if(void 0===u&&0===l)throw new D(6);if(null===u||void 0===u)break;l++;g[k+q]=u}l&&(f.node.atime=Date.now());return l},write(f,g,k,n){for(var l=0;l<n;l++)try{d(g[k+l])}catch(q){throw new D(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return l}});
return Kb(a,b,e)}function Yb(a){if(!(a.Oe||a.Pe||a.link||a.Hc))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Hc=ka(a.url)}catch(b){throw new D(29);}}
function Zb(a,b,c,d,e){class f{Hd=!1;Fc=[];Gd=void 0;ee=0;de=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.Gd(l/this.chunkSize|0)[q]}}Fe(l){this.Gd=l}fe(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||z("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),u,v=(u=l.getResponseHeader("Accept-Ranges"))&&"bytes"===u;l=(u=l.getResponseHeader("Content-Encoding"))&&"gzip"===u;var E=
1048576;v||(E=q);var F=this;F.Fe(P=>{var I=P*E,C=(P+1)*E-1;C=Math.min(C,q-1);if("undefined"==typeof F.Fc[P]){var T=F.Fc;I>C&&z("invalid range ("+I+", "+C+") or no bytes requested!");C>q-1&&z("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);q!==E&&N.setRequestHeader("Range","bytes="+I+"-"+C);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);200<=N.status&&300>N.status||304===N.status||z("Couldn't load "+
c+". Status: "+N.status);I=void 0!==N.response?new Uint8Array(N.response||[]):Xa(N.responseText||"");T[P]=I}"undefined"==typeof F.Fc[P]&&z("doXHR failed!");return F.Fc[P]});if(l||!q)E=q=1,E=q=this.Gd(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.ee=q;this.de=E;this.Hd=!0}get length(){this.Hd||this.fe();return this.ee}get chunkSize(){this.Hd||this.fe();return this.de}}if(globalThis.XMLHttpRequest){ba||z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var k=void 0}else k=c,g=void 0;var n=Vb(a,b,d,e);g?n.Hc=g:k&&(n.Hc=null,n.url=k);Object.defineProperties(n,{Jc:{get:function(){return this.Hc.length}}});a={};for(const [l,q]of Object.entries(n.Gc))a[l]=(...u)=>{Yb(n);return q(...u)};a.read=(l,q,u,v,E)=>{Yb(n);l=l.node.Hc;if(E>=l.length)q=0;else{v=Math.min(l.length-E,v);if(l.slice)for(var F=0;F<v;F++)q[u+F]=l[E+F];else for(F=0;F<v;F++)q[u+F]=l.get(E+F);q=v}return q};a.Td=()=>{Yb(n);z();throw new D(48);};n.Gc=a;return n}var K={};
function $b(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Db(a).path;if(0==b.length){if(!c)throw new D(44);return a}return a+"/"+b}
function ac(a,b){w[a>>2]=b.dev;w[a+4>>2]=b.mode;w[a+8>>2]=b.nlink;w[a+12>>2]=b.uid;w[a+16>>2]=b.gid;w[a+20>>2]=b.rdev;sa[a+24>>3]=BigInt(b.size);t[a+32>>2]=4096;t[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();sa[a+40>>3]=BigInt(Math.floor(c/1E3));w[a+48>>2]=c%1E3*1E6;sa[a+56>>3]=BigInt(Math.floor(d/1E3));w[a+64>>2]=d%1E3*1E6;sa[a+72>>3]=BigInt(Math.floor(e/1E3));w[a+80>>2]=e%1E3*1E6;sa[a+88>>3]=BigInt(b.ino);return 0}
var La=void 0,bc=0,cc={},dc=a=>{a instanceof za||"unwind"==a||fa(1,a)},ec=a=>{pa=a;Ia||0<bc||(h.onExit?.(a),oa=!0);fa(a,new za(a))},fc=()=>{if(!(Ia||0<bc))try{var a=pa;pa=a;ec(a)}catch(b){dc(b)}},gc=a=>{if(!oa)try{a(),fc()}catch(b){dc(b)}},hc=[],ic=(a,b)=>{hc.length=0;for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;hc.push(112==c?w[b>>2]:106==c?sa[b>>3]:105==c?t[b>>2]:y[b>>3]);b+=d?8:4}return hc},sc=(a,b)=>{jc=a;kc=b;if(lc)if(mc||=!0,0==a)nc=function(){setTimeout(oc,Math.max(0,pc+b-performance.now())|
0)};else if(1==a)nc=function(){qc(oc)};else if(2==a){if(!rc)if(globalThis.setImmediate)rc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);rc=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}nc=function(){rc(oc)}}},Bc=(a,b,c,d,e)=>{function f(){return g<tc?(fc(),!1):!0}lc=a;uc=
d;var g=tc;mc=!1;oc=function(){if(!oa)if(0<vc.length){var k=vc.shift();k.tf(k.Ye);if(wc){var n=wc,l=0==n%1?n-1:Math.floor(n);wc=k.ff?l:(8*n+(l+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",n=wc??0,l=xc.pf??0,n?n<l?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(k):h.setStatus(""));f()&&setTimeout(oc,0)}else if(f())if(yc=yc+1|0,1==jc&&1<kc&&0!=yc%kc)nc();else{0==jc&&(pc=performance.now());a:if(!oa){for(k of zc)if(!1===k())break a;gc(a);for(n of Ac)n()}f()&&nc()}};
e||(0<b?sc(0,1E3/b):sc(1,1),nc());if(c)throw"unwind";},mc=!1,nc=null,tc=0,lc=null,uc=0,jc=0,kc=0,yc=0,vc=[],zc=[],Ac=[];function Cc(){nc=null;tc++}var Dc=0;function qc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Dc)Dc=b+1E3/60;else for(;b+2>=Dc;)Dc+=1E3/60;setTimeout(a,Math.max(Dc-b,0))}}
var xc={},pc,oc,rc,wc,Ec=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?A(a):a;return Ec[a]||globalThis.document?.querySelector(a)},Gc=a=>0>Ec.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Hc(a){var b=M.Nc[a];b.target.removeEventListener(b.Mc,b.le,b.Tc);M.Nc.splice(a,1)}function Ic(){if(navigator.userActivation?navigator.userActivation.isActive:M.Qd&&M.Ge.Jd){var a=M.bd;M.bd=[];for(var b of a)b.Xd(...b.ge)}}
function O(a){if(!a.target)return-4;if(a.Oc)a.le=function(c){++M.Qd;M.Ge=a;Ic();a.Vc(c);Ic();--M.Qd},a.target.addEventListener(a.Mc,a.le,a.Tc),M.Nc.push(a);else for(var b=0;b<M.Nc.length;++b)M.Nc[b].target==a.target&&M.Nc[b].Mc==a.Mc&&Hc(b--);return 0}function Jc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Ze:0,uf:0,Rd:0,Ad:0,ce:0,Zd:0,Md:0,kf:0,Bf:0,jf:0,Od:0,Vd:0,Mf:0,Yd:0,Df(){for(;M.Nc.length;)Hc(M.Nc.length-1);M.bd=[]},Qd:0,bd:[],hf(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of M.bd)if(e.Xd==a&&d(e.ge,c))return;M.bd.push({Xd:a,ue:b,ge:c});M.bd.sort((f,g)=>f.ue<g.ue)},Ff(a){M.bd=M.bd.filter(b=>b.Xd!=a)},Nc:[],Ef:(a,b)=>{for(var c=0;c<M.Nc.length;++c)M.Nc[c].target!=a||b&&b!=M.Nc[c].Mc||Hc(c--)},Gf(a){let b=!1;for(let c=0;c<
M.Nc.length;++c){const d=M.Nc[c];d.target===a.target&&d.Rc===a.Rc&&d.Oc===a.Oc&&d.Uc===a.Uc&&(Hc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Kc=(a,b,c,d,e,f)=>{M.Md||(M.Md=Q(256));a={target:L(a),Mc:f,Rc:e,Uc:b,Oc:d,Vc:g=>{var k=g.target.id?g.target.id:"",n=M.Md;B(Jc(g.target),r,n+0,128);B(k,r,n+128,128);R.get(d)(e,n,b)&&g.preventDefault()},Tc:c};return O(a)},Lc=(a,b,c,d,e)=>{M.Od||(M.Od=Q(276));return O({target:a,Mc:e,Rc:19,Uc:b,
Oc:d,Vc:f=>{var g=M.Od,k=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!k;p[g]=n;p[g+1]=M.fullscreenEnabled();var l=n?k:M.Te,q=l?.id||"";B(Jc(l),r,g+2,128);B(q,r,g+130,128);t[g+260>>2]=l?l.clientWidth:0;t[g+264>>2]=l?l.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(M.Te=k);R.get(d)(19,g,b)&&f.preventDefault()},Tc:c})},Mc=(a,b,c,d,e,f)=>{M.Rd||(M.Rd=Q(160));
a={target:L(a),Mc:f,Rc:e,Uc:b,Oc:d,Vc:g=>{var k=M.Rd;y[k>>3]=g.timeStamp;var n=k>>2;t[n+2]=g.location;p[k+12]=g.ctrlKey;p[k+13]=g.shiftKey;p[k+14]=g.altKey;p[k+15]=g.metaKey;p[k+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;B(g.key||"",r,k+32,32);B(g.code||"",r,k+64,32);B(g.char||"",r,k+96,32);B(g.locale||"",r,k+128,32);R.get(d)(e,k,b)&&g.preventDefault()},Tc:c};return O(a)},Nc=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;
p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Gc(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Oc=(a,b,c,d,e,f)=>{M.Ad||(M.Ad=Q(64));a=L(a);return O({target:a,Jd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Mc:f,Rc:e,Uc:b,Oc:d,Vc:g=>{Nc(M.Ad,g,a);R.get(d)(e,M.Ad,b)&&g.preventDefault()},Tc:c})},Pc=(a,b,c,d)=>{M.Vd||(M.Vd=Q(257));return O({target:a,Mc:"pointerlockchange",Rc:20,
Uc:b,Oc:d,Vc:e=>{var f=M.Vd,g=document.pointerLockElement;p[f]=!!g;var k=g?.id||"";B(Jc(g),r,f+1,128);B(k,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},Tc:c})},Qc=(a,b,c,d)=>O({target:a,Mc:"pointerlockerror",Rc:38,Uc:b,Oc:d,Vc:e=>{R.get(d)(38,0,b)&&e.preventDefault()},Tc:c}),Rc=(a,b,c,d)=>{M.Zd||(M.Zd=Q(36));a=L(a);return O({target:a,Mc:"resize",Rc:10,Uc:b,Oc:d,Vc:e=>{if(e.target==a){var f=document.body;if(f){var g=M.Zd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;
t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},Tc:c})},Sc=(a,b,c,d,e,f)=>{M.Yd||(M.Yd=Q(1552));a=L(a);return O({target:a,Jd:"touchstart"==f||"touchend"==f,Mc:f,Rc:e,Uc:b,Oc:d,Vc:g=>{var k={},n=g.touches;for(var l of n)l.ne=l.se=0,k[l.identifier]=l;for(var q of g.changedTouches)q.ne=1,k[q.identifier]=q;for(var u of g.targetTouches)k[u.identifier].se=1;n=M.Yd;y[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;
p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;l=n+16;q=Gc(a);u=0;for(let v of Object.values(k))if(k=l>>2,t[k]=v.identifier,t[k+1]=v.screenX,t[k+2]=v.screenY,t[k+3]=v.clientX,t[k+4]=v.clientY,t[k+5]=v.pageX,t[k+6]=v.pageY,p[l+28]=v.ne,p[l+29]=v.se,t[k+8]=v.clientX-(q.left|0),t[k+9]=v.clientY-(q.top|0),l+=48,31<++u)break;t[n+8>>2]=u;R.get(d)(e,n,b)&&g.preventDefault()},Tc:c})},S,Tc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Uc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Vc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Wc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Xc=1,U=[],V=[],Yc=[],Zc=[],$c=[],W=[],ad=[],bd=[],cd=[],dd=[1,1,2,2,4,4,4,2,3,4,8],ed={},fd=4,gd=0,hd=a=>{for(var b=Xc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Xc++;return b},jd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&hd(d);f?(f.name=g,d[g]=f):X||=1282;t[b+4*e>>2]=g}},kd=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Y.nd[a];if(b)return b;b=S.getParameter(34965);Y.nd[a]=S.createBuffer();S.bindBuffer(34963,Y.nd[a]);S.bufferData(34963,
1<<a,35048);S.bindBuffer(34963,b);return Y.nd[a]},md=a=>{ld=!1;for(var b=0;b<Y.Sd;++b){var c=Y.ed[b];if(c.gd&&c.enabled){ld=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*dd[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=Y.od[e];var g=Y.dd[e];Y.dd[e]=Y.dd[e]+1&63;var k=f[g];k?e=k:(k=S.getParameter(34964),f[g]=S.createBuffer(),S.bindBuffer(34962,f[g]),S.bufferData(34962,1<<e,35048),S.bindBuffer(34962,k),e=f[g]);S.bindBuffer(34962,e);S.bufferSubData(34962,0,r.subarray(c.qd,c.qd+d));c.be.call(S,b,c.size,
c.type,c.Ud,c.stride,0)}}},od=(a,b)=>{a.Fc||(a.Fc=a.getContext,a.getContext=function(d,e){e=a.Fc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.pe?a.getContext("webgl2",b):a.getContext("webgl",b);return c?nd(c,b):0},nd=(a,b)=>{var c=hd(bd),d={handle:c,attributes:b,version:b.pe,Fd:a};a.canvas&&(a.canvas.We=d);bd[c]=d;if("undefined"==typeof b.ke||b.ke)if((a=d)||(a=Y),!a.Je){a.Je=!0;b=a.Fd;b.zf=b.getExtension("WEBGL_multi_draw");b.rf=b.getExtension("EXT_polygon_offset_clamp");
b.qf=b.getExtension("EXT_clip_control");b.Nf=b.getExtension("WEBGL_polygon_mode");Tc(b);Uc(b);Vc(b);b.lf=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.xf=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.je=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.je)b.je=b.getExtension("EXT_disjoint_timer_query");for(var e of Wc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.Sd=d.Fd.getParameter(34921);
d.ed=[];for(e=0;e<d.Sd;e++)d.ed[e]={enabled:!1,gd:!1,size:0,type:0,Ud:0,stride:0,qd:0,be:null};d.dd=[];d.Ed=[];d.dd.length=d.Ed.length=22;d.od=[];d.rd=[];d.od.length=d.rd.length=22;d.nd=[];d.nd.length=22;for(e=0;21>=e;++e){d.nd[e]=null;d.dd[e]=d.Ed[e]=0;d.od[e]=[];d.rd[e]=[];a=d.od[e];b=d.rd[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},X,Y,ld,pd=(a,b,c,d,e,f)=>{a={target:L(a),Mc:f,Rc:e,Uc:b,Oc:d,Vc:g=>{R.get(d)(e,0,b)&&g.preventDefault()},Tc:c};O(a)},qd=(a,b,c,d)=>{M.ce||
(M.ce=Q(96));return O({target:a,Jd:!0,Mc:"wheel",Rc:9,Uc:b,Oc:d,Vc:e=>{var f=M.ce;Nc(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},Tc:c})},rd=["default","low-power","high-performance"],sd={},ud=()=>{if(!td){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in sd)void 0===sd[b]?delete a[b]:
a[b]=sd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);td=c}return td},td,vd=[],wd=()=>{var a=Wc(S);return a=a.concat(a.map(b=>"GL_"+b))},xd=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){X||=1282;return}c=wd().length;break;case 33307:case 33308:if(2>Y.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)t[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){X||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;m(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}t[b>>2]=c}else X||=1281},yd=a=>{var b=Wa(a)+1,c=Q(b);c&&B(a,r,c,b);return c},zd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Ad=a=>{a-=5120;return 0==a?p:1==a?r:2==a?qa:4==a?t:6==a?x:5==a||28922==a||28520==a||30779==a||30782==
a?w:ra},Z=a=>{var b=S.He;if(b){var c=b.sd[a];"number"==typeof c&&(b.sd[a]=c=S.getUniformLocation(b,b.Ce[a]+(0<c?`[${c}]`:"")));return c}X||=1282},Bd=[],Cd=[],Ed=a=>{var b=Wa(a)+1,c=Dd(b);B(a,r,c,b);return c},Hd=a=>{var b=Fd();a();Gd(b)},Id=(a,b,c,d)=>{var e={string:l=>{var q=0;null!==l&&void 0!==l&&0!==l&&(q=Ed(l));return q},array:l=>{var q=Dd(l.length);p.set(l,q);return q}};a=h["_"+a];var f=[],g=0;if(d)for(var k=0;k<d.length;k++){var n=e[c[k]];n?(0===g&&(g=Fd()),f[k]=n(d[k])):f[k]=d[k]}c=a(...f);
return c=function(l){0!==g&&Gd(g);return"string"===b?A(l):"boolean"===b?!!l:l}(c)};pb=Array(4096);Hb(G,"/");J("/tmp");J("/home");J("/home/web_user");(function(){J("/dev");$a(259,{read:()=>0,write:(d,e,f,g)=>g,Wc:()=>0});Kb("/dev/null",259);Za(1280,bb);Za(1536,cb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Sa(a),b=a.byteLength);return a[--b]};Xb("/dev","random",c);Xb("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Hb({Zc(){var b=eb(a,"fd",16895,73);b.Gc={Wc:G.Gc.Wc};b.Ic={lookup(c,d){c=+d;var e=Db(c);c={parent:null,Zc:{qe:"fake"},Ic:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(nb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=qc;h.pauseMainLoop=Cc;h.resumeMainLoop=function(){tc++;var a=jc,b=kc,c=lc;lc=null;Bc(c,0,!1,uc,!0);sc(a,b);nc()};
h.preMainLoop&&zc.push(h.preMainLoop);h.postMainLoop&&Ac.push(h.postMainLoop);var Jd=()=>{if(Y){var a=Y.od;Y.od=Y.rd;Y.rd=a;a=Y.dd;Y.dd=Y.Ed;Y.Ed=a;for(a=0;21>=a;++a)Y.dd[a]=0}};"undefined"!=typeof xc&&zc.push(Jd);for(let a=0;32>a;++a)vd.push(Array(a));for(var Kd=new Float32Array(288),Ld=0;288>=Ld;++Ld)Bd[Ld]=Kd.subarray(0,Ld);var Md=new Int32Array(288);for(Ld=0;288>=Ld;++Ld)Cd[Ld]=Md.subarray(0,Ld);h.noExitRuntime&&(Ia=h.noExitRuntime);h.preloadPlugins&&(jb=h.preloadPlugins);h.print&&(ma=h.print);
h.printErr&&(m=h.printErr);h.wasmBinary&&(na=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=Ha;h.removeRunDependency=Ga;h.ccall=Id;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Id(a,b,c,f,d)};h.UTF8ToString=A;h.stringToNewUTF8=yd;
h.FS_preloadFile=async(a,b,c,d,e,f,g,k)=>{var n=b?Ta(Oa(a+"/"+b)):a,l=`cp ${n}`;Ha(l);try{var q=c;"string"==typeof c&&(q=await ib(c));q=await kb(q,n);k?.();f||Wb(a,b,q,d,e,g)}finally{Ga(l)}};h.FS_unlink=(...a)=>Nb(...a);h.FS_createPath=(...a)=>Ub(...a);h.FS_createDevice=(...a)=>Xb(...a);h.FS_createDataFile=(...a)=>Wb(...a);h.FS_createLazyFile=(...a)=>Zb(...a);
var Qd={639587:(a,b)=>{console.log(A(a,b))},639626:(a,b)=>{console.warn(A(a,b))},639666:(a,b)=>{console.error(A(a,b))},639707:()=>performance.now(),639737:(a,b,c,d,e)=>{if("undefined"===typeof window||void 0===(window.AudioContext||window.webkitAudioContext))return 0;if("undefined"===typeof window.Fc){window.Fc={Cd:0};window.Fc.Pc={};window.Fc.Pc.Bd=a;window.Fc.Pc.capture=b;window.Fc.Pc.Ld=c;window.Fc.kd={};window.Fc.kd.stopped=d;window.Fc.kd.Be=e;let f=window.Fc;f.Lc=[];f.Ue=function(g){for(var k=
0;k<f.Lc.length;++k)if(null==f.Lc[k])return f.Lc[k]=g,k;f.Lc.push(g);return f.Lc.length-1};f.Ee=function(g){for(f.Lc[g]=null;0<f.Lc.length;)if(null==f.Lc[f.Lc.length-1])f.Lc.pop();else break};f.Lf=function(g){for(var k=0;k<f.Lc.length;++k)if(f.Lc[k]==g)return f.Ee(k)};f.ud=function(g){return f.Lc[g]};f.ae=["touchend","click"];f.unlock=function(){for(var g=0;g<f.Lc.length;++g){var k=f.Lc[g];null!=k&&null!=k.Qc&&k.state===f.kd.Be&&k.Qc.resume().then(()=>{Nd(k.te)},n=>{console.error("Failed to resume audiocontext",
n)})}f.ae.map(function(n){document.removeEventListener(n,f.unlock,!0)})};f.ae.map(function(g){document.addEventListener(g,f.unlock,!0)})}window.Fc.Cd+=1;return 1},641915:()=>{"undefined"!==typeof window.Fc&&(window.Fc.ae.map(function(a){document.removeEventListener(a,window.Fc.unlock,!0)}),--window.Fc.Cd,0===window.Fc.Cd&&delete window.Fc)},642219:()=>void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia,642323:()=>{try{var a=new (window.AudioContext||window.webkitAudioContext),
b=a.sampleRate;a.close();return b}catch(c){return 0}},642494:(a,b,c,d,e,f)=>{if("undefined"===typeof window.Fc)return-1;var g={},k={};a==window.Fc.Pc.Bd&&0!=c&&(k.sampleRate=c);g.Qc=new (window.AudioContext||window.webkitAudioContext)(k);g.Qc.suspend();g.state=window.Fc.kd.stopped;c=0;a!=window.Fc.Pc.Bd&&(c=b);g.cd=g.Qc.createScriptProcessor(d,c,b);g.cd.onaudioprocess=function(n){if(null==g.vd||0==g.vd.length)g.vd=new Float32Array(x.buffer,e,d*b);if(a==window.Fc.Pc.capture||a==window.Fc.Pc.Ld){for(var l=
0;l<b;l+=1)for(var q=n.inputBuffer.getChannelData(l),u=g.vd,v=0;v<d;v+=1)u[v*b+l]=q[v];Od(f,d,e)}if(a==window.Fc.Pc.Bd||a==window.Fc.Pc.Ld)for(Pd(f,d,e),l=0;l<n.outputBuffer.numberOfChannels;++l)for(q=n.outputBuffer.getChannelData(l),u=g.vd,v=0;v<d;v+=1)q[v]=u[v*b+l];else for(l=0;l<n.outputBuffer.numberOfChannels;++l)n.outputBuffer.getChannelData(l).fill(0)};a!=window.Fc.Pc.capture&&a!=window.Fc.Pc.Ld||navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(n){g.Dd=g.Qc.createMediaStreamSource(n);
g.Dd.connect(g.cd);g.cd.connect(g.Qc.destination)}).catch(function(n){console.log("Failed to get user media: "+n)});a==window.Fc.Pc.Bd&&g.cd.connect(g.Qc.destination);g.te=f;return window.Fc.Ue(g)},645371:a=>window.Fc.ud(a).Qc.sampleRate,645444:a=>{a=window.Fc.ud(a);void 0!==a.cd&&(a.cd.onaudioprocess=function(){},a.cd.disconnect(),a.cd=void 0);void 0!==a.Dd&&(a.Dd.disconnect(),a.Dd=void 0);a.Qc.close();a.Qc=void 0;a.te=void 0},645844:a=>{window.Fc.Ee(a)},645894:a=>{a=window.Fc.ud(a);a.Qc.resume();
a.state=window.Fc.kd.Be},646033:a=>{a=window.Fc.ud(a);a.Qc.suspend();a.state=window.Fc.kd.stopped}},Rd,Sd,Td,Ud,Vd,Q,Nd,Od,Pd,Wd,Xd,Gd,Dd,Fd,ua,R,Yd={zb:(a,b)=>{var c=Error().stack.toString(),d=c.split("\n");c="";var e=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),f=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of d){d=f.exec(g);if(5==d?.length)d=d[1];else if(d=e.exec(g),4<=d?.length)d=d[1];else{c+=g+"\n";continue}if("_emscripten_log"==d||"_emscripten_get_callstack"==d)c=""}c=c.replace(/\s+$/,
"");c=c.split("\n");for(e=0;e<c.length&&0===R.get(a)(0,b);e++);},d:(a,b,c,d)=>z(`Assertion failed: ${A(a)}, at: `+[b?A(b):"unknown filename",c,d?A(d):"unknown function"]),mb:(a,b)=>R.get(a)(b),ga:function(a,b,c){La=c;try{var d=Db(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;nb[e];)e++;return Fb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==
f.name)throw f;return-f.Kc}},sb:function(a,b){try{var c=Db(a),d=c.node,e=c.Gc.Sc;a=e?c:d;e??=d.Ic.Sc;Cb(e);var f=e(a);return ac(b,f)}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.Kc}},tb:function(a,b,c){La=c;try{var d=Db(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.$c.Le){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>
f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.$c.Me)for(e=Ma(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ma();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ma();if(!d.Gc.Ke)throw new D(59);return d.Gc.Ke(d,b,e);case 21523:if(!d.tty)return-59;d.tty.$c.Ne&&(f=[24,80],e=Ma(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?
0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.Kc}},pb:function(a,b,c,d){try{b=A(b);b=$b(a,b);switch(c&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}Ib(b,c,d);return 0}catch(e){if("undefined"==typeof K||"ErrnoError"!==e.name)throw e;return-e.Kc}},rb:function(a,b,c,d){try{b=A(b);var e=d&256;b=$b(a,b,d&4096);return ac(c,e?Ob(b,!0):Ob(b))}catch(f){if("undefined"==typeof K||"ErrnoError"!==
f.name)throw f;return-f.Kc}},fa:function(a,b,c,d){La=d;try{b=A(b);b=$b(a,b);var e=d?Ma():0;return Qb(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Kc}},kb:function(a){try{return a=A(a),Mb(a),0}catch(b){if("undefined"==typeof K||"ErrnoError"!==b.name)throw b;return-b.Kc}},lb:function(a,b,c){try{b=A(b);b=$b(a,b);if(c)if(512===c)Mb(b);else return-28;else Nb(b);return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Kc}},wb:()=>z(""),ob:()=>
{Ia=!1;bc=0},jb:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=qa[e+4>>1],g=32,k=nb[t[e>>2]];k&&(k.Gc.Se?g=k.Gc.Se(k,-1):g=5);(g&=f|24)&&c++;qa[e+6>>1]=g}return c}catch(n){if("undefined"==typeof K||"ErrnoError"!==n.name)throw n;return-n.Kc}},hb:(a,b)=>{cc[a]&&(clearTimeout(cc[a].id),delete cc[a]);if(!b)return 0;var c=setTimeout(()=>{delete cc[a];gc(()=>Xd(a,performance.now()))},b);cc[a]={id:c,Kf:b};return 0},vb:function(a,b,c){if(!(0<=a&&3>=a))return 28;sa[c>>3]=BigInt(Math.round(1E6*(0===
a?Date.now():performance.now())));return 0},Yb:(a,b,c)=>{b=ic(b,c);return Qd[a](...b)},b:(a,b,c)=>{b=ic(b,c);return Qd[a](...b)},Wb:()=>{Cc();lc=null},ub:()=>Date.now(),S:()=>globalThis.devicePixelRatio??1,sa:(a,b,c)=>{a=L(a);if(!a)return-4;a=Gc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},o:()=>performance.now(),Xb:()=>performance.now(),cb:(a,b)=>{function c(d){R.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=
1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},V:(a,b,c,d)=>Kc(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:(a,b,c,d)=>Kc(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;Lc(a,b,c,d,"webkitfullscreenchange");return Lc(a,b,c,d,"fullscreenchange")},
ja:(a,b,c,d)=>Mc(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>Mc(a,b,c,d,1,"keypress"),ha:(a,b,c,d)=>Mc(a,b,c,d,3,"keyup"),db:(a,b,c)=>{a=R.get(a);Bc(a,b,c)},F:(a,b,c,d)=>Oc(a,b,c,d,5,"mousedown"),qa:(a,b,c,d)=>Oc(a,b,c,d,33,"mouseenter"),oa:(a,b,c,d)=>Oc(a,b,c,d,34,"mouseleave"),ra:(a,b,c,d)=>Oc(a,b,c,d,8,"mousemove"),y:(a,b,c,d)=>Oc(a,b,c,d,6,"mouseup"),Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Pc(a,b,c,d):-4:-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Qc(a,b,c,d):-4:-1,_:(a,
b,c,d)=>Rc(a,b,c,d),Z:(a,b,c,d)=>Sc(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>Sc(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>Sc(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>Sc(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{pd(a,b,c,d,31,"webglcontextlost");return 0},R:(a,b,c,d)=>{pd(a,b,c,d,32,"webglcontextrestored");return 0},la:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?qd(a,b,c,d):-1:-4,Qa:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+
5],powerPreference:rd[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],pe:t[c+4],yf:t[c+5],ke:p[b+24],Ie:p[b+25],Cf:t[c+7],Hf:p[b+32]};a=L(a);return!a||b.Ie?0:od(a,b)},Ma:a=>{Y=bd[a];h.ctx=S=Y?.Fd;return!a||S?0:-5},xb:(a,b)=>{var c=0,d=0,e;for(e of ud()){var f=b+c;w[a+d>>2]=f;c+=B(e,r,f,Infinity)+1;d+=4}return 0},yb:(a,b)=>{var c=ud();w[a>>2]=c.length;a=0;for(var d of c)a+=Wa(d)+1;w[b>>2]=a;return 0},Ab:a=>{pa=a;ec(a)},v:function(a){try{var b=Db(a);Rb(b);return 0}catch(c){if("undefined"==typeof K||
"ErrnoError"!==c.name)throw c;return c.Kc}},ea:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+4>>2];a+=8;var l=e,q=k,u=n,v=f,E=p;if(0>u||0>v)throw new D(28);if(null===l.fd)throw new D(8);if(1===(l.flags&2097155))throw new D(8);if(H(l.node.mode))throw new D(31);if(!l.Gc.read)throw new D(28);var F="undefined"!=typeof v;if(!F)v=l.position;else if(!l.seekable)throw new D(70);var P=l.Gc.read(l,E,q,u,v);F||(l.position+=P);var I=P;if(0>I){var C=-1;break a}b+=I;if(I<
n)break;"undefined"!=typeof f&&(f+=I)}C=b}w[d>>2]=C;return 0}catch(T){if("undefined"==typeof K||"ErrnoError"!==T.name)throw T;return T.Kc}},qb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Db(a);Sb(e,b,c);sa[d>>3]=BigInt(e.position);e.Pd&&0===b&&0===c&&(e.Pd=null);return 0}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return f.Kc}},da:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var k=w[a>>2],n=w[a+
4>>2];a+=8;var l=Tb(e,p,k,n,f);if(0>l){var q=-1;break a}b+=l;if(l<n)break;"undefined"!=typeof f&&(f+=l)}q=b}w[d>>2]=q;return 0}catch(u){if("undefined"==typeof K||"ErrnoError"!==u.name)throw u;return u.Kc}},ma:a=>S.activeTexture(a),t:(a,b)=>{S.attachShader(V[a],W[b])},f:(a,b)=>{if(b&&!U[b]){var c=S.createBuffer();c.name=b;U[b]=c}34962==a?S.hd=b:34963==a&&(S.pd=b);35051==a?S.ie=b:35052==a&&(S.jd=b);S.bindBuffer(a,U[b])},na:(a,b,c)=>{S.bindBufferBase(a,b,U[c])},xa:(a,b,c,d,e)=>{S.bindBufferRange(a,b,
U[c],d,e)},h:(a,b)=>{S.bindFramebuffer(a,Yc[b])},Ia:(a,b)=>{S.bindRenderbuffer(a,Zc[b])},w:(a,b)=>{S.bindSampler(a,cd[b])},i:(a,b)=>{S.bindTexture(a,$c[b])},Q:a=>{S.bindVertexArray(ad[a]);a=S.getParameter(34965);S.pd=a?a.name|0:0},B:(a,b,c,d)=>S.blendColor(a,b,c,d),C:(a,b)=>S.blendEquationSeparate(a,b),D:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),Zb:(a,b,c,d,e,f,g,k,n,l)=>S.blitFramebuffer(a,b,c,d,e,f,g,k,n,l),Ua:(a,b,c,d)=>{2<=Y.version?c&&b?S.bufferData(a,r,d,c,b):S.bufferData(a,b,d):S.bufferData(a,
c?r.subarray(c,c+b):b,d)},u:(a,b,c,d)=>{2<=Y.version?c&&S.bufferSubData(a,b,r,d,c):S.bufferSubData(a,b,r.subarray(d,d+c))},Db:a=>S.checkFramebufferStatus(a),Fa:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),G:(a,b,c)=>{S.clearBufferfv(a,b,x,c>>2)},Ea:(a,b,c)=>{S.clearBufferiv(a,b,t,c>>2)},s:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Gb:a=>{S.compileShader(W[a])},Mb:(a,b,c,d,e,f,g,k,n)=>{2<=Y.version?S.jd||!k?S.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r,n,k):S.compressedTexSubImage2D(a,
b,c,d,e,f,g,r.subarray(n,n+k))},Kb:(a,b,c,d,e,f,g,k,n,l,q)=>{S.jd?S.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,l,q):S.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,r,q,l)},Oa:()=>{var a=hd(V),b=S.createProgram();b.name=a;b.yd=b.wd=b.xd=0;b.$d=1;V[a]=b;return a},Ib:a=>{var b=hd(W);W[b]=S.createShader(a);return b},A:a=>S.cullFace(a),Pb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=U[d];e&&(S.deleteBuffer(e),e.name=0,U[d]=null,d==S.hd&&(S.hd=0),d==S.pd&&(S.pd=0),d==S.ie&&(S.ie=0),d==S.jd&&(S.jd=0))}},
N:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Yc[d];e&&(S.deleteFramebuffer(e),e.name=0,Yc[d]=null)}},n:a=>{if(a){var b=V[a];b?(S.deleteProgram(b),b.name=0,V[a]=null):X||=1281}},Nb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Zc[d];e&&(S.deleteRenderbuffer(e),e.name=0,Zc[d]=null)}},Ob:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=cd[d];e&&(S.deleteSampler(e),e.name=0,cd[d]=null)}},l:a=>{if(a){var b=W[a];b?(S.deleteShader(b),W[a]=null):X||=1281}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+
4*c>>2],e=$c[d];e&&(S.deleteTexture(e),e.name=0,$c[d]=null)}},Wa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];S.deleteVertexArray(ad[d]);ad[d]=null}},q:a=>S.depthFunc(a),r:a=>{S.depthMask(!!a)},c:a=>S.disable(a),x:a=>{Y.ed[a].enabled=!1;S.disableVertexAttribArray(a)},ac:(a,b,c)=>{md(b+c);S.drawArrays(a,b,c);ld&&S.bindBuffer(34962,U[S.hd])},bc:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},I:(a,b)=>{for(var c=vd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];S.drawBuffers(c)},cc:(a,b,c,d)=>{var e=0;if(!S.pd){var f=
1*dd[c-5120]*b;var g=kd(f);S.bindBuffer(34963,g);S.bufferSubData(34963,0,r.subarray(d,d+f));if(0<b)for(g=0;g<Y.Sd;++g)if(f=Y.ed[g],f.gd&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:X||=1282;return}e=(new e(r.buffer,d,b)).reduce((k,n)=>Math.max(k,n))+1;break}d=0}md(e);S.drawElements(a,b,c,d);ld&&S.bindBuffer(34962,U[S.hd]);S.pd||S.bindBuffer(34963,null)},dc:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},g:a=>S.enable(a),ya:a=>
{Y.ed[a].enabled=!0;S.enableVertexAttribArray(a)},k:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Zc[d])},j:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,$c[d],e)},Eb:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,$c[c],d,e)},z:a=>S.frontFace(a),Va:(a,b)=>{jd(a,b,"createBuffer",U)},P:(a,b)=>{jd(a,b,"createFramebuffer",Yc)},Ja:(a,b)=>{jd(a,b,"createRenderbuffer",Zc)},Pa:(a,b)=>{jd(a,b,"createSampler",cd)},Ta:(a,b)=>{jd(a,b,"createTexture",$c)},Za:(a,b)=>{jd(a,b,"createVertexArray",ad)},Ka:(a,b)=>S.getAttribLocation(V[a],
A(b)),a:(a,b)=>xd(a,b),Na:(a,b,c,d)=>{a=S.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},K:(a,b,c)=>{if(c)if(a>=Xc)X||=1281;else if(a=V[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.yd){var d=S.getProgramParameter(a,35718);for(b=0;b<d;++b)a.yd=Math.max(a.yd,S.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.yd}else if(35722==b){if(!a.wd)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.wd=
Math.max(a.wd,S.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.wd}else if(35381==b){if(!a.xd)for(d=S.getProgramParameter(a,35382),b=0;b<d;++b)a.xd=Math.max(a.xd,S.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.xd}else t[c>>2]=S.getProgramParameter(a,b);else X||=1281},Fb:(a,b,c,d)=>{a=S.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},ia:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=
S.getShaderSource(W[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=S.getShaderParameter(W[a],b):X||=1281},Xa:(a,b)=>{if(2>Y.version)return X||=1282,0;var c=ed[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=wd().map(yd),c=ed[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},J:(a,b)=>{b=A(b);if(a=V[a]){var c=a,d=c.sd,e=c.De,f;if(!d){c.sd=d={};c.Ce={};var g=S.getProgramParameter(c,35718);for(f=0;f<g;++f){var k=S.getActiveUniform(c,f);var n=k.name;k=k.size;var l=
zd(n);l=0<l?n.slice(0,l):n;var q=c.$d;c.$d+=k;e[l]=[k,q];for(n=0;n<k;++n)d[q]=n,c.Ce[q++]=l}}c=a.sd;d=0;e=b;f=zd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.De[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else X||=1281;return-1},$b:(a,b,c)=>{for(var d=vd[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];S.invalidateFramebuffer(a,d)},L:a=>{a=V[a];S.linkProgram(a);a.sd=0;a.De={}},Ya:(a,b)=>{3317==a?fd=b:3314==a&&(gd=b);S.pixelStorei(a,b)},E:(a,b)=>S.polygonOffset(a,b),_b:a=>
S.readBuffer(a),Ha:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),M:(a,b,c)=>{S.samplerParameterf(cd[a],b,c)},e:(a,b,c)=>{S.samplerParameteri(cd[a],b,c)},H:(a,b,c,d)=>S.scissor(a,b,c,d),Hb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=A(w[c+4*f>>2],d?w[d+4*f>>2]:void 0);S.shaderSource(W[a],e)},Rb:(a,b,c)=>S.stencilFunc(a,b,c),Da:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),p:a=>S.stencilMask(a),Qb:(a,b,c)=>S.stencilOp(a,b,c),Ca:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Sa:(a,b,c,d,e)=>S.texStorage2D(a,
b,c,d,e),Ra:(a,b,c,d,e,f)=>S.texStorage3D(a,b,c,d,e,f),Lb:(a,b,c,d,e,f,g,k,n)=>{if(2<=Y.version){if(S.jd){S.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var l=Ad(k);S.texSubImage2D(a,b,c,d,e,f,g,k,l,n>>>31-Math.clz32(l.BYTES_PER_ELEMENT));return}}if(n){l=Ad(k);var q=f*((gd||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*l.BYTES_PER_ELEMENT+fd-1&-fd);n=l.subarray(n>>>31-Math.clz32(l.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(l.BYTES_PER_ELEMENT))}else n=null;S.texSubImage2D(a,
b,c,d,e,f,g,k,n)},Jb:(a,b,c,d,e,f,g,k,n,l,q)=>{if(S.jd)S.texSubImage3D(a,b,c,d,e,f,g,k,n,l,q);else if(q){var u=Ad(l);S.texSubImage3D(a,b,c,d,e,f,g,k,n,l,u,q>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,f,g,k,n,l,null)},wa:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1fv(Z(a),x,c>>2,b);else{if(288>=b)for(var d=Bd[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);S.uniform1fv(Z(a),d)}},La:(a,b)=>{S.uniform1i(Z(a),b)},ic:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1iv(Z(a),
t,c>>2,b);else{if(288>=b)for(var d=Cd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);S.uniform1iv(Z(a),d)}},va:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2fv(Z(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Bd[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);S.uniform2fv(Z(a),d)}},hc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2iv(Z(a),t,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Cd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>
2,c+8*b>>2);S.uniform2iv(Z(a),d)}},ua:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3fv(Z(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Bd[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);S.uniform3fv(Z(a),d)}},gc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3iv(Z(a),t,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Cd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);S.uniform3iv(Z(a),d)}},ta:(a,
b,c)=>{if(2<=Y.version)b&&S.uniform4fv(Z(a),x,c>>2,4*b);else{if(72>=b){var d=Bd[4*b],e=x;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);S.uniform4fv(Z(a),d)}},fc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4iv(Z(a),t,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Cd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);S.uniform4iv(Z(a),d)}},ec:(a,
b,c,d)=>{if(2<=Y.version)b&&S.uniformMatrix4fv(Z(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=Bd[16*b],f=x;d>>=2;b*=16;for(var g=0;g<b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=x.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(Z(a),!!c,e)}},m:a=>{a=V[a];S.useProgram(a);S.He=a},za:(a,b)=>{S.vertexAttribDivisor(a,
b)},Aa:(a,b,c,d,e)=>{var f=Y.ed[a];S.hd?(f.gd=!1,S.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Ud=!1,f.stride=d,f.qd=e,f.gd=!0,f.be=function(g,k,n,l,q,u){this.vertexAttribIPointer(g,k,n,q,u)})},Ba:(a,b,c,d,e,f)=>{var g=Y.ed[a];S.hd?(g.gd=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Ud=d,g.stride=e,g.qd=f,g.gd=!0,g.be=function(k,n,l,q,u,v){this.vertexAttribPointer(k,n,l,q,u,v)})},Ga:(a,b,c,d)=>S.viewport(a,b,c,d),Cb:function(){try{var a=globalThis.localStorage;if(!a)return 0;
var b=a.getItem("ScopeBee.PlayerPrefs");return null===b?0:yd(b)}catch(c){return 0}},Bb:function(a,b){try{var c=globalThis.localStorage;c&&c.setItem("ScopeBee.PlayerPrefs",A(a,b))}catch(d){}},nb:ec,gb:function(){h.ve=a=>{0!=Sd()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.ve)},fb:function(){h.Ae=a=>{const b=a.clipboardData.getData("text");Hd(()=>{const c=Ed(b);Rd(c)})};window.addEventListener("paste",h.Ae)},eb:function(){h.If=[];h.we=b=>{b.stopPropagation();b.preventDefault()};
h.xe=b=>{b.stopPropagation();b.preventDefault()};h.ye=b=>{b.stopPropagation();b.preventDefault()};h.ze=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.Jf=c;Td(c.length);for(let e=0;e<c.length;e++)Hd(()=>{const f=Ed(c[e].name);Ud(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Vd(b.clientX,b.clientY,d)};const a=h.ad;a.addEventListener("dragenter",h.we,!1);a.addEventListener("dragleave",h.xe,!1);a.addEventListener("dragover",h.ye,!1);
a.addEventListener("drop",h.ze,!1)},$a:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ab:function(a){h.Id&&(URL.revokeObjectURL(h.Id[a].$e),h.Id[a]=null)},jc:function(a,b){0!==b&&(document.title=A(b));a=A(a);void 0!==h.canvas&&("object"===typeof h.canvas?Ec[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.ad=L(a);h.ad||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.ad.requestPointerLock||
console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Vb:function(){window.removeEventListener("beforeunload",h.ve)},Ub:function(){window.removeEventListener("paste",h.Ae)},Tb:function(){const a=h.ad;a.removeEventListener("dragenter",h.we);a.removeEventListener("dragleave",h.xe);a.removeEventListener("dragover",h.ye);a.removeEventListener("drop",h.ze)},Sb:function(){h.ad&&h.ad.requestPointerLock&&h.ad.requestPointerLock()},bb:function(a,b,c){if(h.ad){if(0===b)a="none";else if(0!=
c)a=h.Id[a].gf;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.ad.style.cursor=a}},_a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(r.subarray(c,
c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},pa:function(a,b){b=A(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function Zd(a=[]){var b=Wd;a.unshift(ea);var c=a.length,d=Dd(4*(c+1)),e=d,f;for(f of a)w[e>>2]=Ed(f),e+=4;w[e>>2]=0;try{var g=b(c,d);pa=g;ec(g)}catch(k){dc(k)}}
function $d(a=da){function b(){h.calledRun=!0;if(!oa){if(!h.noFSInit&&!qb){var c,d;qb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Xb("/dev","stdin",c):Lb("/dev/tty","/dev/stdin");d?Xb("/dev","stdout",null,d):Lb("/dev/tty","/dev/stdout");e?Xb("/dev","stderr",null,e):Lb("/dev/tty1","/dev/stderr");Qb("/dev/stdin",0);Qb("/dev/stdout",1);Qb("/dev/stderr",1)}ae.lc();rb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Zd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ba.push(e)}Aa(Ba)}}if(0<Ea)Fa=$d;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<Ea?Fa=$d:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var ae;
(async function(){function a(c){c=ae=c.exports;Rd=h.__sapp_emsc_onpaste=c.mc;Sd=h.__sapp_html5_get_ask_leave_site=c.oc;Td=h.__sapp_emsc_begin_drop=c.pc;Ud=h.__sapp_emsc_drop=c.qc;Vd=h.__sapp_emsc_end_drop=c.rc;h.__sapp_emsc_invoke_fetch_cb=c.sc;h.__sapp_emsc_set_fullscreen_flag=c.tc;Q=c.uc;Nd=h._ma_device__on_notification_unlocked=c.vc;h._ma_malloc_emscripten=c.wc;h._ma_free_emscripten=c.xc;Od=h._ma_device_process_pcm_frames_capture__webaudio=c.yc;Pd=h._ma_device_process_pcm_frames_playback__webaudio=
c.zc;Wd=h._main=c.Ac;Xd=c.Bc;Gd=c.Cc;Dd=c.Dc;Fd=c.Ec;ua=c.kc;R=c.nc;ta();Ga("wasm-instantiate");return ae}Ha("wasm-instantiate");var b={a:Yd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});va??=h.locateFile?h.locateFile("index.wasm",ia):ia+"index.wasm";return a((await ya(b)).instance)})();$d();
