var k;k||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;k.expectedDataFileDownloads||(k.expectedDataFileDownloads=0);k.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(h,p){if(b){var r=require("fs").readFileSync(h);return(new Uint8Array(r)).buffer}k.dataFileDownloads||(k.dataFileDownloads={});try{var v=await fetch(h)}catch(D){throw Error(`Network Error: ${h}`,
{e:D});}if(!v.ok)throw Error(`${v.status}: ${v.url}`);r=[];p=Number(v.headers.get("Content-Length")||p);let z=0;k.setStatus&&k.setStatus("Downloading data...");for(v=v.body.getReader();;){var {done:B,value:J}=await v.read();if(B)break;r.push(J);z+=J.length;k.dataFileDownloads[h]={loaded:z,total:p};let D=0,R=0;for(var F of Object.values(k.dataFileDownloads))D+=F.loaded,R+=F.total;k.setStatus&&k.setStatus(`Downloading data... (${D}/${R})`)}h=new Uint8Array(r.map(D=>D.length).reduce((D,R)=>D+R,0));F=
0;for(const D of r)h.set(D,F),F+=D.length;return h.buffer}async function e(h){h.FS_createPath("/","Assets",!0,!0);h.FS_createPath("/Assets","Scenes",!0,!0);h.FS_createPath("/Assets","Sprites",!0,!0);h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","builtin",!0,!0);for(var p of c.files)h.addRunDependency(`fp ${p.filename}`);h.addRunDependency("datafile_build/web/Box2D/index.data");h.preloadResults||(h.preloadResults={});h.preloadResults["build/web/Box2D/index.data"]={ff:!1};l||=await m;
(async function(r){if(!r)throw Error("Loading data file failed.");if(r.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+r.constructor.name);r=new Uint8Array(r);for(var v of c.files){var z=v.filename;h.FS_createDataFile(z,null,r.subarray(v.start,v.end),!0,!0,!0);h.removeRunDependency(`fp ${z}`)}h.removeRunDependency("datafile_build/web/Box2D/index.data")})(l)}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=k.locateFile?k.locateFile("index.data",""):"index.data",g=c.remote_package_size,m,l=k.getPreloadedPackage&&k.getPreloadedPackage(f,g);l||(m=d(f,g));k.calledRun?e(k):(k.preRun||(k.preRun=[]),k.preRun.push(e))})({files:[{filename:"/Assets/Inter_24pt-Medium.cowfont",start:0,end:3441},{filename:"/Assets/Inter_24pt-Medium.png",start:3441,end:10507},
{filename:"/Assets/Scenes/Box2DTumbler.sbb",start:10507,end:15145},{filename:"/Assets/Sprites/palette.ktx2",start:15145,end:15533},{filename:"/Assets/_texsizes.txt",start:15533,end:15757},{filename:"/Assets/project.json",start:15757,end:17744},{filename:"/assets/builtin/Background.ktx2",start:17744,end:18124},{filename:"/assets/builtin/Checkmark.ktx2",start:18124,end:18625},{filename:"/assets/builtin/Knob.ktx2",start:18625,end:19155},{filename:"/assets/builtin/UIMask.ktx2",start:19155,end:19580},
{filename:"/assets/builtin/UISprite.ktx2",start:19580,end:20005}],remote_package_size:20005})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),n=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),q,t,u,qa,w,x,y,A,C;
function ra(){var a=sa.buffer;q=new Int8Array(a);u=new Int16Array(a);t=new Uint8Array(a);qa=new Uint16Array(a);w=new Int32Array(a);x=new Uint32Array(a);y=new Float32Array(a);A=new Float64Array(a);C=new BigInt64Array(a);new BigUint64Array(a)}function E(a){k.onAbort?.(a);a="Aborted("+a+")";n(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;
async function ua(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),E(d)}}
async function wa(a){var b=ta;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return va(b,a)}class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(k)},za=[],Aa=[],Ba=()=>{var a=k.preRun.shift();Aa.push(a)},Ca=0,Da=null,Ea=()=>{Ca--;k.monitorRunDependencies?.(Ca);if(0==Ca&&Da){var a=Da;Da=null;a()}},Fa=()=>{Ca++;k.monitorRunDependencies?.(Ca)},Ga=!0,Ha=new TextDecoder,Ia=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},G=(a,b,c)=>a?Ha.decode(t.subarray(a,Ia(t,a,b,c))):"",Ka=()=>{var a=w[+Ja>>2];Ja+=4;return a},La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):
".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ma=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Na=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Oa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Pa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>
crypto.getRandomValues(b)},Qa=a=>{(Qa=Pa())(a)},Ra=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=La(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Sa=a=>{var b=Ia(a,0);return Ha.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Va=a=>{var b=Array(Ua(a)+1);a=H(a,b,0,b.length);
b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],bd:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new I(43);a.tty=b;a.seekable=!1},close(a){a.tty.bd.fsync(a.tty)},fsync(a){a.tty.bd.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.bd.be)throw new I(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.bd.be(a.tty)}catch(m){throw new I(29);}if(void 0===g&&0===e)throw new I(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.bd.Ld)throw new I(60);try{for(var e=0;e<d;e++)a.tty.bd.Ld(a.tty,b[c+e])}catch(f){throw new I(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={be(){a:{if(!Ta.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Va(a)}a=Ta.shift()}return a},Ld(a,b){null===b||10===b?(ma(Sa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(Sa(a.output)),a.output=[])},ze(){return{Se:25856,Ue:5,Re:191,Te:35387,Qe:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ae(){return 0},Be(){return[24,80]}},ab={Ld(a,b){null===b||10===b?(n(Sa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(n(Sa(a.output)),a.output=[])}},K={Zc:null,ad(){return K.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(63);K.Zc||(K.Zc={dir:{node:{Uc:K.Kc.Uc,
$c:K.Kc.$c,lookup:K.Kc.lookup,sd:K.Kc.sd,rename:K.Kc.rename,unlink:K.Kc.unlink,rmdir:K.Kc.rmdir,readdir:K.Kc.readdir,symlink:K.Kc.symlink},stream:{Yc:K.Ic.Yc}},file:{node:{Uc:K.Kc.Uc,$c:K.Kc.$c},stream:{Yc:K.Ic.Yc,read:K.Ic.read,write:K.Ic.write,Jd:K.Ic.Jd,fe:K.Ic.fe}},link:{node:{Uc:K.Kc.Uc,$c:K.Kc.$c,readlink:K.Kc.readlink},stream:{}},Xd:{node:{Uc:K.Kc.Uc,$c:K.Kc.$c},stream:bb}});c=cb(a,b,c,d);L(c.mode)?(c.Kc=K.Zc.dir.node,c.Ic=K.Zc.dir.stream,c.Jc={}):32768===(c.mode&61440)?(c.Kc=K.Zc.file.node,
c.Ic=K.Zc.file.stream,c.Mc=0,c.Jc=null):40960===(c.mode&61440)?(c.Kc=K.Zc.link.node,c.Ic=K.Zc.link.stream):8192===(c.mode&61440)&&(c.Kc=K.Zc.Xd.node,c.Ic=K.Zc.Xd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Jc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},jf(a){return a.Jc?a.Jc.subarray?a.Jc.subarray(0,a.Mc):new Uint8Array(a.Jc):new Uint8Array(0)},Kc:{Uc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.Mc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},$c(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Mc!=b&&(0==b?(a.Jc=null,a.Mc=0):(c=a.Jc,a.Jc=new Uint8Array(b),c&&a.Jc.set(c.subarray(0,Math.min(b,a.Mc))),a.Mc=b)))},lookup(){K.Bd||(K.Bd=new I(44),K.Bd.stack="<generic error, no stack>");
throw K.Bd;},sd(a,b,c,d){return K.createNode(a,b,c,d)},rename(a,b,c){try{var d=db(b,c)}catch(f){}if(d){if(L(a.mode))for(var e in d.Jc)throw new I(55);eb(d)}delete a.parent.Jc[a.name];b.Jc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Jc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=db(a,b),d;for(d in c.Jc)throw new I(55);delete a.Jc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Jc)]},symlink(a,b,c){a=K.createNode(a,b,41471,
0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new I(28);return a.link}},Ic:{read(a,b,c,d,e){var f=a.node.Jc;if(e>=a.node.Mc)return 0;a=Math.min(a.node.Mc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Jc||a.Jc.subarray)){if(f)return a.Jc=b.subarray(c,c+d),a.Mc=d;if(0===a.Mc&&0===e)return a.Jc=b.slice(c,c+d),a.Mc=d;
if(e+d<=a.Mc)return a.Jc.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Jc?a.Jc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Jc,a.Jc=new Uint8Array(f),0<a.Mc&&a.Jc.set(g.subarray(0,a.Mc),0));if(a.Jc.subarray&&b.subarray)a.Jc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Jc[e+f]=b[c+f];a.Mc=Math.max(a.Mc,e+d);return d},Yc(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Mc);if(0>b)throw new I(28);return b},Jd(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new I(43);a=a.node.Jc;if(e&2||!a||a.buffer!==q.buffer){d=!0;E();e=void 0;if(!e)throw new I(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);q.set(a,e)}}else d=!1,e=a.byteOffset;return{sf:e,Me:d}},fe(a,b,c,d){K.Ic.write(a,b,0,d,c,!1);return 0}}},fb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},gb=async a=>{a=await ja(a);return new Uint8Array(a)},hb=[],ib=async(a,b)=>{"undefined"!=typeof Browser&&Browser.kf();for(var c of hb)if(c.canHandle(b))return c.handle(a,
b);return a},jb=null,kb={},lb=[],mb=1,nb=null,ob=!1,pb=!0,qb={},I=class{name="ErrnoError";constructor(a){this.Lc=a}},rb=class{Hc={};node=null;get flags(){return this.Hc.flags}set flags(a){this.Hc.flags=a}get position(){return this.Hc.position}set position(a){this.Hc.position=a}},sb=class{Kc={};Ic={};jd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ad=a.ad;this.id=mb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get De(){return L(this.mode)}get Ce(){return 8192===(this.mode&61440)}};
function tb(a,b={}){if(!a)throw new I(44);b.Ed??(b.Ed=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=jb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Na(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Ma(e+"/"+a[f]);try{d=db(d,a[f])}catch(m){if(44===m?.Lc&&g&&b.Ge)return{path:e};throw m;}!d.jd||g&&!b.Ed||(d=d.jd.root);if(40960===(d.mode&61440)&&(!g||b.md)){if(!d.Kc.readlink)throw new I(52);
d=d.Kc.readlink(d);"/"===d.charAt(0)||(d=Na(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new I(32);}function ub(a){for(var b;;){if(a===a.parent)return a=a.ad.ee,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length}
function eb(a){var b=vb(a.parent.id,a.name);if(nb[b]===a)nb[b]=a.kd;else for(b=nb[b];b;){if(b.kd===a){b.kd=a.kd;break}b=b.kd}}function db(a,b){var c=L(a.mode)?(c=wb(a,"x"))?c:a.Kc.lookup?0:2:54;if(c)throw new I(c);for(c=nb[vb(a.id,b)];c;c=c.kd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Kc.lookup(a,b)}function cb(a,b,c,d){a=new sb(a,b,c,d);b=vb(a.parent.id,a.name);a.kd=nb[b];return nb[b]=a}function L(a){return 16384===(a&61440)}
function xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function wb(a,b){if(pb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function yb(a,b){if(!L(a.mode))return 54;try{return db(a,b),20}catch(c){}return wb(a,"wx")}
function zb(a,b,c){try{var d=db(a,b)}catch(e){return e.Lc}if(a=wb(a,"wx"))return a;if(c){if(!L(d.mode))return 54;if(d===d.parent||"/"===ub(d))return 10}else if(L(d.mode))return 31;return 0}function Ab(a){if(!a)throw new I(63);return a}function Bb(a){a=lb[a];if(!a)throw new I(8);return a}function Cb(a,b=-1){a=Object.assign(new rb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!lb[b])break a;throw new I(33);}a.fd=b;return lb[b]=a}function Db(a,b=-1){a=Cb(a,b);a.Ic?.bf?.(a);return a}
function Eb(a,b){var c=null?.Ic.$c,d=c?null:a;c??=a.Kc.$c;Ab(c);c(d,b)}var bb={open(a){a.Ic=kb[a.node.rdev].Ic;a.Ic.open?.(a)},Yc(){throw new I(70);}};function Ya(a,b){kb[a]={Ic:b}}function Fb(a,b){var c="/"===b;if(c&&jb)throw new I(10);if(!c&&b){var d=tb(b,{Ed:!1});b=d.path;d=d.node;if(d.jd)throw new I(10);if(!L(d.mode))throw new I(54);}b={type:a,pf:{},ee:b,Fe:[]};a=a.ad(b);a.ad=b;b.root=a;c?jb=a:d&&(d.jd=b,d.ad&&d.ad.Fe.push(b))}
function Gb(a,b,c){var d=tb(a,{parent:!0}).node;a=Oa(a);if(!a)throw new I(28);if("."===a||".."===a)throw new I(20);var e=yb(d,a);if(e)throw new I(e);if(!d.Kc.sd)throw new I(63);return d.Kc.sd(d,a,b,c)}function Hb(a,b=438){return Gb(a,b&4095|32768,0)}function N(a){return Gb(a,16895,0)}function Ib(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Gb(a,b|8192,c)}
function Jb(a,b){if(!Ra(a))throw new I(44);var c=tb(b,{parent:!0}).node;if(!c)throw new I(44);b=Oa(b);var d=yb(c,b);if(d)throw new I(d);if(!c.Kc.symlink)throw new I(63);c.Kc.symlink(c,b,a)}function Kb(a){var b=tb(a,{parent:!0}).node;a=Oa(a);var c=db(b,a),d=zb(b,a,!0);if(d)throw new I(d);if(!b.Kc.rmdir)throw new I(63);if(c.jd)throw new I(10);b.Kc.rmdir(b,a);eb(c)}
function Lb(a){var b=tb(a,{parent:!0}).node;if(!b)throw new I(44);a=Oa(a);var c=db(b,a),d=zb(b,a,!1);if(d)throw new I(d);if(!b.Kc.unlink)throw new I(63);if(c.jd)throw new I(10);b.Kc.unlink(b,a);eb(c)}function Mb(a,b){a=tb(a,{md:!b}).node;return Ab(a.Kc.Uc)(a)}function Nb(a,b){a="string"==typeof a?tb(a,{md:!0}).node:a;Eb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),af:void 0})}
function Ob(a,b,c=438){if(""===a)throw new I(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=tb(a,{md:!(b&131072),Ge:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new I(20);}else{if(e)throw new I(31);d=Gb(a,c|511,0);f=!0}if(!d)throw new I(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!L(d.mode))throw new I(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:L(d.mode)&&("r"!==xb(b)||b&576)?31:wb(d,xb(b)):44))throw new I(e);if(b&512&&!f){e=d;e="string"==typeof e?tb(e,{md:!0}).node:e;if(L(e.mode))throw new I(31);if(32768!==(e.mode&61440))throw new I(28);var g=wb(e,"w");if(g)throw new I(g);Eb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Cb({node:d,path:ub(d),flags:b,seekable:!0,position:0,Ic:d.Ic,Ke:[],error:!1});e.Ic.open&&e.Ic.open(e);f&&Nb(d,c&511);!k.logReadFiles||b&1||a in qb||(qb[a]=1);return e}
function Pb(a){if(null===a.fd)throw new I(8);a.Gd&&(a.Gd=null);try{a.Ic.close&&a.Ic.close(a)}catch(b){throw b;}finally{lb[a.fd]=null}a.fd=null}function Qb(a,b,c){if(null===a.fd)throw new I(8);if(!a.seekable||!a.Ic.Yc)throw new I(70);if(0!=c&&1!=c&&2!=c)throw new I(28);a.position=a.Ic.Yc(a,b,c);a.Ke=[]}
function Rb(a,b,c,d,e,f){if(0>d||0>e)throw new I(28);if(null===a.fd)throw new I(8);if(0===(a.flags&2097155))throw new I(8);if(L(a.node.mode))throw new I(31);if(!a.Ic.write)throw new I(28);a.seekable&&a.flags&1024&&Qb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new I(70);b=a.Ic.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Sb(a,b){a="string"==typeof a?a:ub(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ma(a+"/"+c);try{N(d)}catch(e){if(20!=e.Lc)throw e;}a=d}}return d}function Tb(a,b,c,d){a=Ma(("string"==typeof a?a:ub(a))+"/"+b);return Hb(a,fb(c,d))}
function Ub(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:ub(a),g=b?Ma(a+"/"+b):a);a=fb(d,e);g=Hb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Nb(g,a|146);b=Ob(g,577);Rb(b,c,0,c.length,0,f);Pb(b);Nb(g,a)}}
function Vb(a,b,c,d){a=Ma(("string"==typeof a?a:ub(a))+"/"+b);b=fb(!!c,!!d);Vb.de??(Vb.de=64);var e=Vb.de++<<8|0;Ya(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,l){for(var h=0,p=0;p<l;p++){try{var r=c()}catch(v){throw new I(29);}if(void 0===r&&0===h)throw new I(6);if(null===r||void 0===r)break;h++;g[m+p]=r}h&&(f.node.atime=Date.now());return h},write(f,g,m,l){for(var h=0;h<l;h++)try{d(g[m+h])}catch(p){throw new I(29);}l&&(f.node.mtime=f.node.ctime=Date.now());return h}});
return Ib(a,b,e)}function Wb(a){if(!(a.Ce||a.De||a.link||a.Jc))if(globalThis.XMLHttpRequest)E("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Jc=ka(a.url)}catch(b){throw new I(29);}}
function Xb(a,b,c,d,e){class f{yd=!1;Hc=[];xd=void 0;Ud=0;Td=0;get(h){if(!(h>this.length-1||0>h)){var p=h%this.chunkSize;return this.xd(h/this.chunkSize|0)[p]}}te(h){this.xd=h}Vd(){var h=new XMLHttpRequest;h.open("HEAD",c,!1);h.send(null);200<=h.status&&300>h.status||304===h.status||E("Couldn't load "+c+". Status: "+h.status);var p=Number(h.getResponseHeader("Content-length")),r,v=(r=h.getResponseHeader("Accept-Ranges"))&&"bytes"===r;h=(r=h.getResponseHeader("Content-Encoding"))&&"gzip"===r;var z=
1048576;v||(z=p);var B=this;B.te(J=>{var F=J*z,D=(J+1)*z-1;D=Math.min(D,p-1);if("undefined"==typeof B.Hc[J]){var R=B.Hc;F>D&&E("invalid range ("+F+", "+D+") or no bytes requested!");D>p-1&&E("only "+p+" bytes available! programmer error!");var M=new XMLHttpRequest;M.open("GET",c,!1);p!==z&&M.setRequestHeader("Range","bytes="+F+"-"+D);M.responseType="arraybuffer";M.overrideMimeType&&M.overrideMimeType("text/plain; charset=x-user-defined");M.send(null);200<=M.status&&300>M.status||304===M.status||E("Couldn't load "+
c+". Status: "+M.status);F=void 0!==M.response?new Uint8Array(M.response||[]):Va(M.responseText||"");R[J]=F}"undefined"==typeof B.Hc[J]&&E("doXHR failed!");return B.Hc[J]});if(h||!p)z=p=1,z=p=this.xd(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Ud=p;this.Td=z;this.yd=!0}get length(){this.yd||this.Vd();return this.Ud}get chunkSize(){this.yd||this.Vd();return this.Td}}if(globalThis.XMLHttpRequest){ba||E("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var m=void 0}else m=c,g=void 0;var l=Tb(a,b,d,e);g?l.Jc=g:m&&(l.Jc=null,l.url=m);Object.defineProperties(l,{Mc:{get:function(){return this.Jc.length}}});a={};for(const [h,p]of Object.entries(l.Ic))a[h]=(...r)=>{Wb(l);return p(...r)};a.read=(h,p,r,v,z)=>{Wb(l);h=h.node.Jc;if(z>=h.length)p=0;else{v=Math.min(h.length-z,v);if(h.slice)for(var B=0;B<v;B++)p[r+B]=h[z+B];else for(B=0;B<v;B++)p[r+B]=h.get(z+B);p=v}return p};a.Jd=()=>{Wb(l);E();throw new I(48);};l.Ic=a;return l}var O={};
function Yb(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Bb(a).path;if(0==b.length){if(!c)throw new I(44);return a}return a+"/"+b}
function Zb(a,b){x[a>>2]=b.dev;x[a+4>>2]=b.mode;x[a+8>>2]=b.nlink;x[a+12>>2]=b.uid;x[a+16>>2]=b.gid;x[a+20>>2]=b.rdev;C[a+24>>3]=BigInt(b.size);w[a+32>>2]=4096;w[a+36>>2]=b.blocks;var c=b.atime.getTime(),d=b.mtime.getTime(),e=b.ctime.getTime();C[a+40>>3]=BigInt(Math.floor(c/1E3));x[a+48>>2]=c%1E3*1E6;C[a+56>>3]=BigInt(Math.floor(d/1E3));x[a+64>>2]=d%1E3*1E6;C[a+72>>3]=BigInt(Math.floor(e/1E3));x[a+80>>2]=e%1E3*1E6;C[a+88>>3]=BigInt(b.ino);return 0}
var Ja=void 0,$b=0,ac={},bc=a=>{a instanceof xa||"unwind"==a||fa(1,a)},cc=a=>{pa=a;Ga||0<$b||(k.onExit?.(a),oa=!0);fa(a,new xa(a))},dc=()=>{if(!(Ga||0<$b))try{var a=pa;pa=a;cc(a)}catch(b){bc(b)}},ec=a=>{if(!oa)try{a(),dc()}catch(b){bc(b)}},fc=[],gc=(a,b)=>{fc.length=0;for(var c;c=t[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;fc.push(112==c?x[b>>2]:106==c?C[b>>3]:105==c?w[b>>2]:A[b>>3]);b+=d?8:4}return fc},qc=(a,b)=>{hc=a;ic=b;if(jc)if(kc||=!0,0==a)lc=function(){setTimeout(mc,Math.max(0,nc+b-performance.now())|
0)};else if(1==a)lc=function(){oc(mc)};else if(2==a){if(!pc)if(globalThis.setImmediate)pc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);pc=d=>{c.push(d);if(ba){let e;(e=k).setImmediates??(e.setImmediates=[]);k.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}lc=function(){pc(mc)}}},zc=(a,b,c,d,e)=>{function f(){return g<rc?(dc(),!1):!0}jc=a;sc=
d;var g=rc;kc=!1;mc=function(){if(!oa)if(0<tc.length){var m=tc.shift();m.gf(m.Ne);if(uc){var l=uc,h=0==l%1?l-1:Math.floor(l);uc=m.Ve?h:(8*l+(h+.5))/9}k.setStatus&&(m=k.statusMessage||"Please wait...",l=uc??0,h=vc.cf??0,l?l<h?k.setStatus("{message} ({expected - remaining}/{expected})"):k.setStatus(m):k.setStatus(""));f()&&setTimeout(mc,0)}else if(f())if(wc=wc+1|0,1==hc&&1<ic&&0!=wc%ic)lc();else{0==hc&&(nc=performance.now());a:if(!oa){for(m of xc)if(!1===m())break a;ec(a);for(l of yc)l()}f()&&lc()}};
e||(0<b?qc(0,1E3/b):qc(1,1),lc());if(c)throw"unwind";},kc=!1,lc=null,rc=0,jc=null,sc=0,hc=0,ic=0,wc=0,tc=[],xc=[],yc=[];function Ac(){lc=null;rc++}var Bc=0;function oc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Bc)Bc=b+1E3/60;else for(;b+2>=Bc;)Bc+=1E3/60;setTimeout(a,Math.max(Bc-b,0))}}
var vc={},nc,mc,pc,uc,Cc=[0,globalThis.document??0,globalThis.window??0],P=a=>{a=2<a?G(a):a;return Cc[a]||globalThis.document?.querySelector(a)},Dc=a=>0>Cc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Ec(a){var b=Q.Pc[a];b.target.removeEventListener(b.Oc,b.ae,b.Vc);Q.Pc.splice(a,1)}function Fc(){if(navigator.userActivation?navigator.userActivation.isActive:Q.Hd&&Q.ue.Ad){var a=Q.dd;Q.dd=[];for(var b of a)b.Md(...b.Wd)}}
function S(a){if(!a.target)return-4;if(a.Qc)a.ae=function(c){++Q.Hd;Q.ue=a;Fc();a.Xc(c);Fc();--Q.Hd},a.target.addEventListener(a.Oc,a.ae,a.Vc),Q.Pc.push(a);else for(var b=0;b<Q.Pc.length;++b)Q.Pc[b].target==a.target&&Q.Pc[b].Oc==a.Oc&&Ec(b--);return 0}function Gc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var Q={Oe:0,hf:0,Id:0,td:0,Rd:0,Od:0,Dd:0,Ze:0,qf:0,Ye:0,Fd:0,Kd:0,Cf:0,Nd:0,tf(){for(;Q.Pc.length;)Ec(Q.Pc.length-1);Q.dd=[]},Hd:0,dd:[],Xe(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of Q.dd)if(e.Md==a&&d(e.Wd,c))return;Q.dd.push({Md:a,ie:b,Wd:c});Q.dd.sort((f,g)=>f.ie<g.ie)},vf(a){Q.dd=Q.dd.filter(b=>b.Md!=a)},Pc:[],uf:(a,b)=>{for(var c=0;c<Q.Pc.length;++c)Q.Pc[c].target!=a||b&&b!=Q.Pc[c].Oc||Ec(c--)},wf(a){let b=!1;for(let c=0;c<
Q.Pc.length;++c){const d=Q.Pc[c];d.target===a.target&&d.Tc===a.Tc&&d.Qc===a.Qc&&d.Wc===a.Wc&&(Ec(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Ic=(a,b,c,d,e,f)=>{Q.Dd||(Q.Dd=T(256));a={target:P(a),Oc:f,Tc:e,Wc:b,Qc:d,Xc:g=>{var m=g.target.id?g.target.id:"",l=Q.Dd;H(Gc(g.target),t,l+0,128);H(m,t,l+128,128);U.get(d)(e,l,b)&&g.preventDefault()},Vc:c};return S(a)},Jc=(a,b,c,d,e)=>{Q.Fd||(Q.Fd=T(276));return S({target:a,Oc:e,Tc:19,Wc:b,
Qc:d,Xc:f=>{var g=Q.Fd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,l=!!m;q[g]=l;q[g+1]=Q.fullscreenEnabled();var h=l?m:Q.Ie,p=h?.id||"";H(Gc(h),t,g+2,128);H(p,t,g+130,128);w[g+260>>2]=h?h.clientWidth:0;w[g+264>>2]=h?h.clientHeight:0;w[g+268>>2]=screen.width;w[g+272>>2]=screen.height;l&&(Q.Ie=m);U.get(d)(19,g,b)&&f.preventDefault()},Vc:c})},Kc=(a,b,c,d,e,f)=>{Q.Id||(Q.Id=T(160));
a={target:P(a),Oc:f,Tc:e,Wc:b,Qc:d,Xc:g=>{var m=Q.Id;A[m>>3]=g.timeStamp;var l=m>>2;w[l+2]=g.location;q[m+12]=g.ctrlKey;q[m+13]=g.shiftKey;q[m+14]=g.altKey;q[m+15]=g.metaKey;q[m+16]=g.repeat;w[l+5]=g.charCode;w[l+6]=g.keyCode;w[l+7]=g.which;H(g.key||"",t,m+32,32);H(g.code||"",t,m+64,32);H(g.char||"",t,m+96,32);H(g.locale||"",t,m+128,32);U.get(d)(e,m,b)&&g.preventDefault()},Vc:c};return S(a)},Lc=(a,b,c)=>{A[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;
q[a+24]=b.ctrlKey;q[a+25]=b.shiftKey;q[a+26]=b.altKey;q[a+27]=b.metaKey;u[2*d+14]=b.button;u[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Dc(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},Mc=(a,b,c,d,e,f)=>{Q.td||(Q.td=T(64));a=P(a);return S({target:a,Ad:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Oc:f,Tc:e,Wc:b,Qc:d,Xc:g=>{Lc(Q.td,g,a);U.get(d)(e,Q.td,b)&&g.preventDefault()},Vc:c})},Nc=(a,b,c,d)=>{Q.Kd||(Q.Kd=T(257));return S({target:a,Oc:"pointerlockchange",Tc:20,
Wc:b,Qc:d,Xc:e=>{var f=Q.Kd,g=document.pointerLockElement;q[f]=!!g;var m=g?.id||"";H(Gc(g),t,f+1,128);H(m,t,f+129,128);U.get(d)(20,f,b)&&e.preventDefault()},Vc:c})},Oc=(a,b,c,d)=>S({target:a,Oc:"pointerlockerror",Tc:38,Wc:b,Qc:d,Xc:e=>{U.get(d)(38,0,b)&&e.preventDefault()},Vc:c}),Pc=(a,b,c,d)=>{Q.Od||(Q.Od=T(36));a=P(a);return S({target:a,Oc:"resize",Tc:10,Wc:b,Qc:d,Xc:e=>{if(e.target==a){var f=document.body;if(f){var g=Q.Od;w[g>>2]=0;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;
w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset|0;w[g+32>>2]=pageYOffset|0;U.get(d)(10,g,b)&&e.preventDefault()}}},Vc:c})},Qc=(a,b,c,d,e,f)=>{Q.Nd||(Q.Nd=T(1552));a=P(a);return S({target:a,Ad:"touchstart"==f||"touchend"==f,Oc:f,Tc:e,Wc:b,Qc:d,Xc:g=>{var m={},l=g.touches;for(var h of l)h.ce=h.ge=0,m[h.identifier]=h;for(var p of g.changedTouches)p.ce=1,m[p.identifier]=p;for(var r of g.targetTouches)m[r.identifier].ge=1;l=Q.Nd;A[l>>3]=g.timeStamp;q[l+12]=g.ctrlKey;
q[l+13]=g.shiftKey;q[l+14]=g.altKey;q[l+15]=g.metaKey;h=l+16;p=Dc(a);r=0;for(let v of Object.values(m))if(m=h>>2,w[m]=v.identifier,w[m+1]=v.screenX,w[m+2]=v.screenY,w[m+3]=v.clientX,w[m+4]=v.clientY,w[m+5]=v.pageX,w[m+6]=v.pageY,q[h+28]=v.ce,q[h+29]=v.ge,w[m+8]=v.clientX-(p.left|0),w[m+9]=v.clientY-(p.top|0),h+=48,31<++r)break;w[l+8>>2]=r;U.get(d)(e,l,b)&&g.preventDefault()},Vc:c})},V,Rc=a=>{var b="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Sc=1,Tc=[],W=[],Uc=[],Vc=[],Wc=[],X=[],Xc=[],Yc=[],Zc=[],$c={},ad=4,bd=0,cd=a=>{for(var b=Sc++,c=a.length;c<b;c++)a[c]=null;return b},dd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=V[c](),g=f&&cd(d);f?(f.name=g,d[g]=f):Y||=1282;w[b+4*e>>2]=g}},fd=(a,b)=>{a.Hc||(a.Hc=a.getContext,a.getContext=function(d,e){e=a.Hc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl2",b);return c?ed(c,b):0},ed=(a,b)=>
{var c=cd(Yc),d={handle:c,attributes:b,version:b.Ee,Sd:a};a.canvas&&(a.canvas.Le=d);Yc[c]=d;if("undefined"==typeof b.$d||b.$d)if((a=d)||(a=gd),!a.xe){a.xe=!0;b=a.Sd;b.nf=b.getExtension("WEBGL_multi_draw");b.ef=b.getExtension("EXT_polygon_offset_clamp");b.df=b.getExtension("EXT_clip_control");b.Df=b.getExtension("WEBGL_polygon_mode");b.$e=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.lf=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Zd=
b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Zd)b.Zd=b.getExtension("EXT_disjoint_timer_query");for(var e of Rc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},Y,gd,hd=(a,b,c,d,e,f)=>{a={target:P(a),Oc:f,Tc:e,Wc:b,Qc:d,Xc:g=>{U.get(d)(e,0,b)&&g.preventDefault()},Vc:c};S(a)},jd=(a,b,c,d)=>{Q.Rd||(Q.Rd=T(96));return S({target:a,Ad:!0,Oc:"wheel",Tc:9,Wc:b,Qc:d,Xc:e=>{var f=Q.Rd;Lc(f,e,a);A[f+64>>3]=e.deltaX;A[f+72>>3]=e.deltaY;A[f+80>>3]=e.deltaZ;
w[f+88>>2]=e.deltaMode;U.get(d)(9,f,b)&&e.preventDefault()},Vc:c})},kd=["default","low-power","high-performance"],ld={},nd=()=>{if(!md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in ld)void 0===ld[b]?delete a[b]:a[b]=ld[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);md=c}return md},md,od=[],pd=()=>{var a=Rc(V);return a=a.concat(a.map(b=>"GL_"+b))},qd=(a,b)=>{if(b){var c=
void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=V.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>gd.version){Y||=1282;return}c=pd().length;break;case 33307:case 33308:if(2>gd.version){Y||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=V.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=
0;break;default:Y||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:Y||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else Y||=1281},rd=
a=>{var b=Ua(a)+1,c=T(b);c&&H(a,t,c,b);return c},sd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),td=a=>{a-=5120;return 0==a?q:1==a?t:2==a?u:4==a?w:6==a?y:5==a||28922==a||28520==a||30779==a||30782==a?x:qa},Z=a=>{var b=V.ve;if(b){var c=b.ld[a];"number"==typeof c&&(b.ld[a]=c=V.getUniformLocation(b,b.qe[a]+(0<c?`[${c}]`:"")));return c}Y||=1282},vd=a=>{var b=Ua(a)+1,c=ud(b);H(a,t,c,b);return c},yd=a=>{var b=wd();a();xd(b)};nb=Array(4096);Fb(K,"/");N("/tmp");N("/home");N("/home/web_user");
(function(){N("/dev");Ya(259,{read:()=>0,write:(d,e,f,g)=>g,Yc:()=>0});Ib("/dev/null",259);Xa(1280,$a);Xa(1536,ab);Ib("/dev/tty",1280);Ib("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Qa(a),b=a.byteLength);return a[--b]};Vb("/dev","random",c);Vb("/dev","urandom",c);N("/dev/shm");N("/dev/shm/tmp")})();
(function(){N("/proc");var a=N("/proc/self");N("/proc/self/fd");Fb({ad(){var b=cb(a,"fd",16895,73);b.Ic={Yc:K.Ic.Yc};b.Kc={lookup(c,d){c=+d;var e=Bb(c);c={parent:null,ad:{ee:"fake"},Kc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(lb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();k.requestAnimationFrame=oc;k.pauseMainLoop=Ac;k.resumeMainLoop=function(){rc++;var a=hc,b=ic,c=jc;jc=null;zc(c,0,!1,sc,!0);qc(a,b);lc()};
k.preMainLoop&&xc.push(k.preMainLoop);k.postMainLoop&&yc.push(k.postMainLoop);for(let a=0;32>a;++a)od.push(Array(a));k.noExitRuntime&&(Ga=k.noExitRuntime);k.preloadPlugins&&(hb=k.preloadPlugins);k.print&&(ma=k.print);k.printErr&&(n=k.printErr);k.wasmBinary&&(na=k.wasmBinary);k.arguments&&(da=k.arguments);k.thisProgram&&(ea=k.thisProgram);if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();k.addRunDependency=Fa;k.removeRunDependency=Ea;
k.UTF8ToString=G;k.stringToNewUTF8=rd;k.FS_preloadFile=async(a,b,c,d,e,f,g,m)=>{var l=b?Ra(Ma(a+"/"+b)):a,h=`cp ${l}`;Fa(h);try{var p=c;"string"==typeof c&&(p=await gb(c));p=await ib(p,l);m?.();f||Ub(a,b,p,d,e,g)}finally{Ea(h)}};k.FS_unlink=(...a)=>Lb(...a);k.FS_createPath=(...a)=>Sb(...a);k.FS_createDevice=(...a)=>Vb(...a);k.FS_createDataFile=(...a)=>Ub(...a);k.FS_createLazyFile=(...a)=>Xb(...a);
var Cd={783520:(a,b)=>{console.log(G(a,b))},783559:(a,b)=>{console.warn(G(a,b))},783599:(a,b)=>{console.error(G(a,b))},783640:()=>performance.now(),783670:()=>{try{return(new URLSearchParams(location.search)).has("perf")?1:0}catch(a){return 0}},783771:(a,b)=>{try{var c=(new URLSearchParams(location.search)).get(G(a));if(null===c)return b;var d=parseInt(c,10);return isNaN(d)?b:d}catch(e){return b}},783954:(a,b,c,d,e)=>{if("undefined"===typeof window||void 0===(window.AudioContext||window.webkitAudioContext))return 0;
if("undefined"===typeof window.Hc){window.Hc={vd:0};window.Hc.Rc={};window.Hc.Rc.ud=a;window.Hc.Rc.capture=b;window.Hc.Rc.Cd=c;window.Hc.hd={};window.Hc.hd.stopped=d;window.Hc.hd.pe=e;let f=window.Hc;f.Nc=[];f.Je=function(g){for(var m=0;m<f.Nc.length;++m)if(null==f.Nc[m])return f.Nc[m]=g,m;f.Nc.push(g);return f.Nc.length-1};f.se=function(g){for(f.Nc[g]=null;0<f.Nc.length;)if(null==f.Nc[f.Nc.length-1])f.Nc.pop();else break};f.Bf=function(g){for(var m=0;m<f.Nc.length;++m)if(f.Nc[m]==g)return f.se(m)};
f.nd=function(g){return f.Nc[g]};f.Qd=["touchend","click"];f.unlock=function(){for(var g=0;g<f.Nc.length;++g){var m=f.Nc[g];null!=m&&null!=m.Sc&&m.state===f.hd.pe&&m.Sc.resume().then(()=>{zd(m.he)},l=>{console.error("Failed to resume audiocontext",l)})}f.Qd.map(function(l){document.removeEventListener(l,f.unlock,!0)})};f.Qd.map(function(g){document.addEventListener(g,f.unlock,!0)})}window.Hc.vd+=1;return 1},786132:()=>{"undefined"!==typeof window.Hc&&(window.Hc.Qd.map(function(a){document.removeEventListener(a,
window.Hc.unlock,!0)}),--window.Hc.vd,0===window.Hc.vd&&delete window.Hc)},786436:()=>void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia,786540:()=>{try{var a=new (window.AudioContext||window.webkitAudioContext),b=a.sampleRate;a.close();return b}catch(c){return 0}},786711:(a,b,c,d,e,f)=>{if("undefined"===typeof window.Hc)return-1;var g={},m={};a==window.Hc.Rc.ud&&0!=c&&(m.sampleRate=c);g.Sc=new (window.AudioContext||window.webkitAudioContext)(m);g.Sc.suspend();g.state=window.Hc.hd.stopped;
c=0;a!=window.Hc.Rc.ud&&(c=b);g.ed=g.Sc.createScriptProcessor(d,c,b);g.ed.onaudioprocess=function(l){if(null==g.od||0==g.od.length)g.od=new Float32Array(y.buffer,e,d*b);if(a==window.Hc.Rc.capture||a==window.Hc.Rc.Cd){for(var h=0;h<b;h+=1)for(var p=l.inputBuffer.getChannelData(h),r=g.od,v=0;v<d;v+=1)r[v*b+h]=p[v];Ad(f,d,e)}if(a==window.Hc.Rc.ud||a==window.Hc.Rc.Cd)for(Bd(f,d,e),h=0;h<l.outputBuffer.numberOfChannels;++h)for(p=l.outputBuffer.getChannelData(h),r=g.od,v=0;v<d;v+=1)p[v]=r[v*b+h];else for(h=
0;h<l.outputBuffer.numberOfChannels;++h)l.outputBuffer.getChannelData(h).fill(0)};a!=window.Hc.Rc.capture&&a!=window.Hc.Rc.Cd||navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(function(l){g.wd=g.Sc.createMediaStreamSource(l);g.wd.connect(g.ed);g.ed.connect(g.Sc.destination)}).catch(function(l){console.log("Failed to get user media: "+l)});a==window.Hc.Rc.ud&&g.ed.connect(g.Sc.destination);g.he=f;return window.Hc.Je(g)},789588:a=>window.Hc.nd(a).Sc.sampleRate,789661:a=>{a=window.Hc.nd(a);
void 0!==a.ed&&(a.ed.onaudioprocess=function(){},a.ed.disconnect(),a.ed=void 0);void 0!==a.wd&&(a.wd.disconnect(),a.wd=void 0);a.Sc.close();a.Sc=void 0;a.he=void 0},790061:a=>{window.Hc.se(a)},790111:a=>{a=window.Hc.nd(a);a.Sc.resume();a.state=window.Hc.hd.pe},790250:a=>{a=window.Hc.nd(a);a.Sc.suspend();a.state=window.Hc.hd.stopped}};
function Dd(){if(!globalThis.__sbj){var a=new TextEncoder,b=new TextDecoder;globalThis.__sbj={encode:function(c){function d(z){if(Object.prototype.hasOwnProperty.call(m,z))return m[z];var B=a.encode(z),J=g;f.push(B);g+=B.length+1;return m[z]=J}var e=[],f=[],g=0,m={};c=[[c,0]];e.push({kind:0,sub:0,count:0,data:0,key:0});for(var l=0;l<c.length;l++){var h=c[l][0],p=e[c[l][1]];if(null===h||void 0===h)p.kind=0;else if(!0===h)p.kind=2;else if(!1===h)p.kind=1;else if("number"===typeof h)Number.isInteger(h)&&
9007199254740991>=Math.abs(h)?(p.kind=3,p.sub=0>h?1:0):p.kind=4,p.data=h;else if("string"===typeof h)p.kind=5,p.data=d(h);else if(Array.isArray(h)){p.kind=6;p.count=h.length;p.data=e.length;for(var r=0;r<h.length;r++)e.push({kind:0,sub:0,count:0,data:0,key:0}),c.push([h[r],p.data+r])}else{r=Object.keys(h);p.kind=7;p.count=r.length;p.data=e.length;for(var v=0;v<r.length;v++)e.push({kind:0,sub:0,count:0,data:0,key:d(r[v])}),c.push([h[r[v]],p.data+v])}}c=new Uint8Array(16+24*e.length+g);l=new DataView(c.buffer);
l.setUint32(0,826950227,!0);l.setUint32(4,e.length,!0);l.setUint32(8,g,!0);l.setUint32(12,0,!0);for(h=0;h<e.length;h++)p=e[h],r=16+24*h,c[r]=p.kind,c[r+1]=p.sub,l.setUint32(r+4,p.count,!0),4===p.kind?l.setFloat64(r+8,p.data,!0):3===p.kind?l.setBigInt64(r+8,BigInt(p.data),!0):l.setBigUint64(r+8,BigInt(p.data),!0),l.setBigUint64(r+16,BigInt(p.key),!0);e=16+24*e.length;for(l=0;l<f.length;l++)c.set(f[l],e),e+=f[l].length+1;return c},decode:function(c){function d(l){for(var h=m+l;h<c.length&&0!==c[h];)h++;
return b.decode(c.subarray(m+l,h))}function e(l){var h=16+24*l,p=c[h];l=f.getUint32(h+4,!0);switch(p){case 1:return!1;case 2:return!0;case 3:return Number(f.getBigInt64(h+8,!0));case 4:return f.getFloat64(h+8,!0);case 5:return d(Number(f.getBigUint64(h+8,!0)));case 6:h=Number(f.getBigUint64(h+8,!0));p=[];for(var r=0;r<l;r++)p.push(e(h+r));return p;case 7:h=Number(f.getBigUint64(h+8,!0));p={};for(r=0;r<l;r++)p[d(Number(f.getBigUint64(24*(h+r)+32,!0)))]=e(h+r);return p}return null}var f=new DataView(c.buffer,
c.byteOffset,c.byteLength);if(16>c.length||826950227!==f.getUint32(0,!0))return null;var g=f.getUint32(4,!0);f.getUint32(8,!0);var m=16+24*g;return 0<g?e(0):null}}}}
var Ed,Fd,Gd,Hd,Id,T,zd,Ad,Bd,Jd,Kd,xd,ud,wd,sa,U,Ld={Bb:(a,b)=>{var c=Error().stack.toString(),d=c.split("\n");c="";var e=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),f=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of d){d=f.exec(g);if(5==d?.length)d=d[1];else if(d=e.exec(g),4<=d?.length)d=d[1];else{c+=g+"\n";continue}if("_emscripten_log"==d||"_emscripten_get_callstack"==d)c=""}c=c.replace(/\s+$/,"");c=c.split("\n");for(e=0;e<c.length&&0===U.get(a)(0,b);e++);},d:(a,b,c,d)=>E(`Assertion failed: ${G(a)}, at: `+
[b?G(b):"unknown filename",c,d?G(d):"unknown function"]),mb:(a,b)=>U.get(a)(b),ga:function(a,b,c){Ja=c;try{var d=Bb(a);switch(b){case 0:var e=Ka();if(0>e)break;for(;lb[e];)e++;return Db(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ka(),d.flags|=e,0;case 12:return e=Ka(),u[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof O||"ErrnoError"!==f.name)throw f;return-f.Lc}},ub:function(a,b){try{var c=Bb(a),d=c.node,e=c.Ic.Uc;a=e?c:d;e??=d.Kc.Uc;Ab(e);
var f=e(a);return Zb(b,f)}catch(g){if("undefined"==typeof O||"ErrnoError"!==g.name)throw g;return-g.Lc}},vb:function(a,b,c){Ja=c;try{var d=Bb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.bd.ze){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ka();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;32>f;f++)q[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;
if(d.tty.bd.Ae)for(e=Ka(),a=[],f=0;32>f;f++)a.push(q[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ka();return w[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ka();if(!d.Ic.ye)throw new I(59);return d.Ic.ye(d,b,e);case 21523:if(!d.tty)return-59;d.tty.bd.Be&&(f=[24,80],e=Ka(),u[e>>1]=f[0],u[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof O||"ErrnoError"!==g.name)throw g;return-g.Lc}},sb:function(a,
b){try{return a=G(a),Zb(b,Mb(a,!0))}catch(c){if("undefined"==typeof O||"ErrnoError"!==c.name)throw c;return-c.Lc}},pb:function(a,b,c,d){try{b=G(b);b=Yb(a,b);switch(c&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}Gb(b,c,d);return 0}catch(e){if("undefined"==typeof O||"ErrnoError"!==e.name)throw e;return-e.Lc}},rb:function(a,b,c,d){try{b=G(b);var e=d&256;b=Yb(a,b,d&4096);return Zb(c,e?Mb(b,!0):Mb(b))}catch(f){if("undefined"==typeof O||"ErrnoError"!==f.name)throw f;
return-f.Lc}},fa:function(a,b,c,d){Ja=d;try{b=G(b);b=Yb(a,b);var e=d?Ka():0;return Ob(b,c,e).fd}catch(f){if("undefined"==typeof O||"ErrnoError"!==f.name)throw f;return-f.Lc}},kb:function(a){try{return a=G(a),Kb(a),0}catch(b){if("undefined"==typeof O||"ErrnoError"!==b.name)throw b;return-b.Lc}},tb:function(a,b){try{return a=G(a),Zb(b,Mb(a))}catch(c){if("undefined"==typeof O||"ErrnoError"!==c.name)throw c;return-c.Lc}},lb:function(a,b,c){try{b=G(b);b=Yb(a,b);if(c)if(512===c)Kb(b);else return-28;else Lb(b);
return 0}catch(d){if("undefined"==typeof O||"ErrnoError"!==d.name)throw d;return-d.Lc}},yb:()=>E(""),ob:()=>{Ga=!1;$b=0},jb:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=u[e+4>>1],g=32,m=lb[w[e>>2]];m&&(m.Ic.He?g=m.Ic.He(m,-1):g=5);(g&=f|24)&&c++;u[e+6>>1]=g}return c}catch(l){if("undefined"==typeof O||"ErrnoError"!==l.name)throw l;return-l.Lc}},hb:(a,b)=>{ac[a]&&(clearTimeout(ac[a].id),delete ac[a]);if(!b)return 0;var c=setTimeout(()=>{delete ac[a];ec(()=>Kd(a,performance.now()))},b);ac[a]=
{id:c,Af:b};return 0},xb:function(a,b,c){if(!(0<=a&&3>=a))return 28;C[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},_b:(a,b,c)=>{b=gc(b,c);return Cd[a](...b)},b:(a,b,c)=>{b=gc(b,c);return Cd[a](...b)},Yb:()=>{Ac();jc=null},wb:()=>Date.now(),S:()=>globalThis.devicePixelRatio??1,sa:(a,b,c)=>{a=P(a);if(!a)return-4;a=Dc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},o:()=>performance.now(),Zb:()=>performance.now(),cb:(a,b)=>{function c(d){U.get(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},ib:a=>{var b=t.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-sa.buffer.byteLength+65535)/65536|0;try{sa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},V:(a,b,c,d)=>Ic(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:(a,b,c,d)=>Ic(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!Q.fullscreenEnabled())return-1;
a=P(a);if(!a)return-4;Jc(a,b,c,d,"webkitfullscreenchange");return Jc(a,b,c,d,"fullscreenchange")},ja:(a,b,c,d)=>Kc(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>Kc(a,b,c,d,1,"keypress"),ha:(a,b,c,d)=>Kc(a,b,c,d,3,"keyup"),db:(a,b,c)=>{a=U.get(a);zc(a,b,c)},F:(a,b,c,d)=>Mc(a,b,c,d,5,"mousedown"),qa:(a,b,c,d)=>Mc(a,b,c,d,33,"mouseenter"),oa:(a,b,c,d)=>Mc(a,b,c,d,34,"mouseleave"),ra:(a,b,c,d)=>Mc(a,b,c,d,8,"mousemove"),y:(a,b,c,d)=>Mc(a,b,c,d,6,"mouseup"),Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=P(a))?
Nc(a,b,c,d):-4:-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=P(a))?Oc(a,b,c,d):-4:-1,_:(a,b,c,d)=>Pc(a,b,c,d),Z:(a,b,c,d)=>Qc(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>Qc(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>Qc(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>Qc(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{hd(a,b,c,d,31,"webglcontextlost");return 0},R:(a,b,c,d)=>{hd(a,b,c,d,32,"webglcontextrestored");return 0},la:(a,b,c,d)=>(a=P(a))?"undefined"!=typeof a.onwheel?jd(a,b,c,d):-1:-4,Qa:(a,b)=>{var c=b>>2;b={alpha:!!q[b+
0],depth:!!q[b+1],stencil:!!q[b+2],antialias:!!q[b+3],premultipliedAlpha:!!q[b+4],preserveDrawingBuffer:!!q[b+5],powerPreference:kd[w[c+2]],failIfMajorPerformanceCaveat:!!q[b+12],Ee:w[c+4],mf:w[c+5],$d:q[b+24],we:q[b+25],rf:w[c+7],xf:q[b+32]};a=P(a);return!a||b.we?0:fd(a,b)},Ma:a=>{gd=Yc[a];k.ctx=V=gd?.Sd;return!a||V?0:-5},zb:(a,b)=>{var c=0,d=0,e;for(e of nd()){var f=b+c;x[a+d>>2]=f;c+=H(e,t,f,Infinity)+1;d+=4}return 0},Ab:(a,b)=>{var c=nd();x[a>>2]=c.length;a=0;for(var d of c)a+=Ua(d)+1;x[b>>2]=
a;return 0},Cb:a=>{pa=a;cc(a)},v:function(a){try{var b=Bb(a);Pb(b);return 0}catch(c){if("undefined"==typeof O||"ErrnoError"!==c.name)throw c;return c.Lc}},ea:function(a,b,c,d){try{a:{var e=Bb(a);a=b;for(var f,g=b=0;g<c;g++){var m=x[a>>2],l=x[a+4>>2];a+=8;var h=e,p=m,r=l,v=f,z=q;if(0>r||0>v)throw new I(28);if(null===h.fd)throw new I(8);if(1===(h.flags&2097155))throw new I(8);if(L(h.node.mode))throw new I(31);if(!h.Ic.read)throw new I(28);var B="undefined"!=typeof v;if(!B)v=h.position;else if(!h.seekable)throw new I(70);
var J=h.Ic.read(h,z,p,r,v);B||(h.position+=J);var F=J;if(0>F){var D=-1;break a}b+=F;if(F<l)break;"undefined"!=typeof f&&(f+=F)}D=b}x[d>>2]=D;return 0}catch(R){if("undefined"==typeof O||"ErrnoError"!==R.name)throw R;return R.Lc}},qb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Bb(a);Qb(e,b,c);C[d>>3]=BigInt(e.position);e.Gd&&0===b&&0===c&&(e.Gd=null);return 0}catch(f){if("undefined"==typeof O||"ErrnoError"!==f.name)throw f;return f.Lc}},
da:function(a,b,c,d){try{a:{var e=Bb(a);a=b;for(var f,g=b=0;g<c;g++){var m=x[a>>2],l=x[a+4>>2];a+=8;var h=Rb(e,q,m,l,f);if(0>h){var p=-1;break a}b+=h;if(h<l)break;"undefined"!=typeof f&&(f+=h)}p=b}x[d>>2]=p;return 0}catch(r){if("undefined"==typeof O||"ErrnoError"!==r.name)throw r;return r.Lc}},ma:a=>V.activeTexture(a),t:(a,b)=>{V.attachShader(W[a],X[b])},f:(a,b)=>{35051==a?V.Yd=b:35052==a&&(V.gd=b);V.bindBuffer(a,Tc[b])},na:(a,b,c)=>{V.bindBufferBase(a,b,Tc[c])},xa:(a,b,c,d,e)=>{V.bindBufferRange(a,
b,Tc[c],d,e)},h:(a,b)=>{V.bindFramebuffer(a,Uc[b])},Ia:(a,b)=>{V.bindRenderbuffer(a,Vc[b])},w:(a,b)=>{V.bindSampler(a,Zc[b])},i:(a,b)=>{V.bindTexture(a,Wc[b])},Q:a=>{V.bindVertexArray(Xc[a])},B:(a,b,c,d)=>V.blendColor(a,b,c,d),C:(a,b)=>V.blendEquationSeparate(a,b),D:(a,b,c,d)=>V.blendFuncSeparate(a,b,c,d),$b:(a,b,c,d,e,f,g,m,l,h)=>V.blitFramebuffer(a,b,c,d,e,f,g,m,l,h),Ua:(a,b,c,d)=>{c&&b?V.bufferData(a,t,d,c,b):V.bufferData(a,b,d)},u:(a,b,c,d)=>{c&&V.bufferSubData(a,b,t,d,c)},Fb:a=>V.checkFramebufferStatus(a),
Fa:(a,b,c,d)=>V.clearBufferfi(a,b,c,d),G:(a,b,c)=>{V.clearBufferfv(a,b,y,c>>2)},Ea:(a,b,c)=>{V.clearBufferiv(a,b,w,c>>2)},s:(a,b,c,d)=>{V.colorMask(!!a,!!b,!!c,!!d)},Ib:a=>{V.compileShader(X[a])},Ob:(a,b,c,d,e,f,g,m,l)=>{V.gd||!m?V.compressedTexSubImage2D(a,b,c,d,e,f,g,m,l):V.compressedTexSubImage2D(a,b,c,d,e,f,g,t,l,m)},Mb:(a,b,c,d,e,f,g,m,l,h,p)=>{V.gd?V.compressedTexSubImage3D(a,b,c,d,e,f,g,m,l,h,p):V.compressedTexSubImage3D(a,b,c,d,e,f,g,m,l,t,p,h)},Oa:()=>{var a=cd(W),b=V.createProgram();b.name=
a;b.rd=b.pd=b.qd=0;b.Pd=1;W[a]=b;return a},Kb:a=>{var b=cd(X);X[b]=V.createShader(a);return b},A:a=>V.cullFace(a),Rb:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Tc[d];e&&(V.deleteBuffer(e),e.name=0,Tc[d]=null,d==V.Yd&&(V.Yd=0),d==V.gd&&(V.gd=0))}},N:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=Uc[d];e&&(V.deleteFramebuffer(e),e.name=0,Uc[d]=null)}},n:a=>{if(a){var b=W[a];b?(V.deleteProgram(b),b.name=0,W[a]=null):Y||=1281}},Pb:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Vc[d];e&&(V.deleteRenderbuffer(e),
e.name=0,Vc[d]=null)}},Qb:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Zc[d];e&&(V.deleteSampler(e),e.name=0,Zc[d]=null)}},l:a=>{if(a){var b=X[a];b?(V.deleteShader(b),X[a]=null):Y||=1281}},ka:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Wc[d];e&&(V.deleteTexture(e),e.name=0,Wc[d]=null)}},Wa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];V.deleteVertexArray(Xc[d]);Xc[d]=null}},q:a=>V.depthFunc(a),r:a=>{V.depthMask(!!a)},c:a=>V.disable(a),x:a=>{V.disableVertexAttribArray(a)},cc:(a,b,c)=>{V.drawArrays(a,
b,c)},dc:(a,b,c,d)=>{V.drawArraysInstanced(a,b,c,d)},I:(a,b)=>{for(var c=od[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];V.drawBuffers(c)},ec:(a,b,c,d)=>{V.drawElements(a,b,c,d)},fc:(a,b,c,d,e)=>{V.drawElementsInstanced(a,b,c,d,e)},g:a=>V.enable(a),ya:a=>{V.enableVertexAttribArray(a)},k:(a,b,c,d)=>{V.framebufferRenderbuffer(a,b,c,Vc[d])},j:(a,b,c,d,e)=>{V.framebufferTexture2D(a,b,c,Wc[d],e)},Gb:(a,b,c,d,e)=>{V.framebufferTextureLayer(a,b,Wc[c],d,e)},z:a=>V.frontFace(a),Va:(a,b)=>{dd(a,b,"createBuffer",Tc)},P:(a,
b)=>{dd(a,b,"createFramebuffer",Uc)},Ja:(a,b)=>{dd(a,b,"createRenderbuffer",Vc)},Pa:(a,b)=>{dd(a,b,"createSampler",Zc)},Ta:(a,b)=>{dd(a,b,"createTexture",Wc)},Za:(a,b)=>{dd(a,b,"createVertexArray",Xc)},Ka:(a,b)=>V.getAttribLocation(W[a],G(b)),a:(a,b)=>qd(a,b),Na:(a,b,c,d)=>{a=V.getProgramInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,t,d,b):0;c&&(w[c>>2]=b)},K:(a,b,c)=>{if(c)if(a>=Sc)Y||=1281;else if(a=W[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+
1;else if(35719==b){if(!a.rd){var d=V.getProgramParameter(a,35718);for(b=0;b<d;++b)a.rd=Math.max(a.rd,V.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.rd}else if(35722==b){if(!a.pd)for(d=V.getProgramParameter(a,35721),b=0;b<d;++b)a.pd=Math.max(a.pd,V.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.pd}else if(35381==b){if(!a.qd)for(d=V.getProgramParameter(a,35382),b=0;b<d;++b)a.qd=Math.max(a.qd,V.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.qd}else w[c>>2]=V.getProgramParameter(a,b);else Y||=1281},
Hb:(a,b,c,d)=>{a=V.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?H(a,t,d,b):0;c&&(w[c>>2]=b)},ia:(a,b,c)=>{c?35716==b?(a=V.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(X[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=V.getShaderParameter(X[a],b):Y||=1281},Xa:(a,b)=>{if(2>gd.version)return Y||=1282,0;var c=$c[a];if(c)return 0>b||b>=c.length?(Y||=1281,0):c[b];switch(a){case 7939:return c=pd().map(rd),c=$c[a]=c,0>b||b>=c.length?(Y||=
1281,0):c[b];default:return Y||=1280,0}},J:(a,b)=>{b=G(b);if(a=W[a]){var c=a,d=c.ld,e=c.re,f;if(!d){c.ld=d={};c.qe={};var g=V.getProgramParameter(c,35718);for(f=0;f<g;++f){var m=V.getActiveUniform(c,f);var l=m.name;m=m.size;var h=sd(l);h=0<h?l.slice(0,h):l;var p=c.Pd;c.Pd+=m;e[h]=[m,p];for(l=0;l<m;++l)d[p]=l,c.qe[p++]=h}}c=a.ld;d=0;e=b;f=sd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.re[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||V.getUniformLocation(a,b)))return d}else Y||=1281;return-1},
bc:(a,b,c)=>{for(var d=od[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];V.invalidateFramebuffer(a,d)},L:a=>{a=W[a];V.linkProgram(a);a.ld=0;a.re={}},Ya:(a,b)=>{3317==a?ad=b:3314==a&&(bd=b);V.pixelStorei(a,b)},E:(a,b)=>V.polygonOffset(a,b),ac:a=>V.readBuffer(a),Ha:(a,b,c,d,e)=>V.renderbufferStorageMultisample(a,b,c,d,e),M:(a,b,c)=>{V.samplerParameterf(Zc[a],b,c)},e:(a,b,c)=>{V.samplerParameteri(Zc[a],b,c)},H:(a,b,c,d)=>V.scissor(a,b,c,d),Jb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=G(x[c+4*f>>2],d?x[d+4*f>>2]:void 0);
V.shaderSource(X[a],e)},Tb:(a,b,c)=>V.stencilFunc(a,b,c),Da:(a,b,c,d)=>V.stencilFuncSeparate(a,b,c,d),p:a=>V.stencilMask(a),Sb:(a,b,c)=>V.stencilOp(a,b,c),Ca:(a,b,c,d)=>V.stencilOpSeparate(a,b,c,d),Sa:(a,b,c,d,e)=>V.texStorage2D(a,b,c,d,e),Ra:(a,b,c,d,e,f)=>V.texStorage3D(a,b,c,d,e,f),Nb:(a,b,c,d,e,f,g,m,l)=>{if(V.gd)V.texSubImage2D(a,b,c,d,e,f,g,m,l);else if(l){var h=td(m);V.texSubImage2D(a,b,c,d,e,f,g,m,h,l>>>31-Math.clz32(h.BYTES_PER_ELEMENT))}else{if(l){h=td(m);var p=f*((bd||e)*({5:3,6:4,8:2,
29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*h.BYTES_PER_ELEMENT+ad-1&-ad);l=h.subarray(l>>>31-Math.clz32(h.BYTES_PER_ELEMENT),l+p>>>31-Math.clz32(h.BYTES_PER_ELEMENT))}else l=null;V.texSubImage2D(a,b,c,d,e,f,g,m,l)}},Lb:(a,b,c,d,e,f,g,m,l,h,p)=>{if(V.gd)V.texSubImage3D(a,b,c,d,e,f,g,m,l,h,p);else if(p){var r=td(h);V.texSubImage3D(a,b,c,d,e,f,g,m,l,h,r,p>>>31-Math.clz32(r.BYTES_PER_ELEMENT))}else V.texSubImage3D(a,b,c,d,e,f,g,m,l,h,null)},wa:(a,b,c)=>{b&&V.uniform1fv(Z(a),y,c>>2,b)},
La:(a,b)=>{V.uniform1i(Z(a),b)},kc:(a,b,c)=>{b&&V.uniform1iv(Z(a),w,c>>2,b)},va:(a,b,c)=>{b&&V.uniform2fv(Z(a),y,c>>2,2*b)},jc:(a,b,c)=>{b&&V.uniform2iv(Z(a),w,c>>2,2*b)},ua:(a,b,c)=>{b&&V.uniform3fv(Z(a),y,c>>2,3*b)},ic:(a,b,c)=>{b&&V.uniform3iv(Z(a),w,c>>2,3*b)},ta:(a,b,c)=>{b&&V.uniform4fv(Z(a),y,c>>2,4*b)},hc:(a,b,c)=>{b&&V.uniform4iv(Z(a),w,c>>2,4*b)},gc:(a,b,c,d)=>{b&&V.uniformMatrix4fv(Z(a),!!c,y,d>>2,16*b)},m:a=>{a=W[a];V.useProgram(a);V.ve=a},za:(a,b)=>{V.vertexAttribDivisor(a,b)},Aa:(a,
b,c,d,e)=>{V.vertexAttribIPointer(a,b,c,d,e)},Ba:(a,b,c,d,e,f)=>{V.vertexAttribPointer(a,b,c,!!d,e,f)},Ga:(a,b,c,d)=>V.viewport(a,b,c,d),Eb:function(a){try{var b=globalThis.localStorage;if(!b)return 0;var c=b.getItem("ScopeBee.PlayerPrefs");if(null===c)return 0;Dd();var d=globalThis.__sbj.encode(JSON.parse(c)),e=T(d.length);if(!e)return 0;t.set(d,e);w[a>>2]=d.length;return e}catch(f){return 0}},Db:function(a,b){try{var c=globalThis.localStorage;if(c){Dd();var d=globalThis.__sbj.decode(t.slice(a,a+
b));null!==d&&c.setItem("ScopeBee.PlayerPrefs",JSON.stringify(d))}}catch(e){}},nb:cc,gb:function(){k.je=a=>{0!=Fd()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",k.je)},fb:function(){k.oe=a=>{const b=a.clipboardData.getData("text");yd(()=>{const c=vd(b);Ed(c)})};window.addEventListener("paste",k.oe)},eb:function(){k.yf=[];k.ke=b=>{b.stopPropagation();b.preventDefault()};k.le=b=>{b.stopPropagation();b.preventDefault()};k.me=b=>{b.stopPropagation();b.preventDefault()};
k.ne=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;k.zf=c;Gd(c.length);for(let e=0;e<c.length;e++)yd(()=>{const f=vd(c[e].name);Hd(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Id(b.clientX,b.clientY,d)};const a=k.cd;a.addEventListener("dragenter",k.ke,!1);a.addEventListener("dragleave",k.le,!1);a.addEventListener("dragover",k.me,!1);a.addEventListener("drop",k.ne,!1)},$a:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},ab:function(a){k.zd&&(URL.revokeObjectURL(k.zd[a].Pe),k.zd[a]=null)},lc:function(a,b){0!==b&&(document.title=G(b));a=G(a);void 0!==k.canvas&&("object"===typeof k.canvas?Cc[a]=k.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));k.cd=P(a);k.cd||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);k.cd.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Xb:function(){window.removeEventListener("beforeunload",
k.je)},Wb:function(){window.removeEventListener("paste",k.oe)},Vb:function(){const a=k.cd;a.removeEventListener("dragenter",k.ke);a.removeEventListener("dragleave",k.le);a.removeEventListener("dragover",k.me);a.removeEventListener("drop",k.ne)},Ub:function(){k.cd&&k.cd.requestPointerLock&&k.cd.requestPointerLock()},bb:function(a,b,c){if(k.cd){if(0===b)a="none";else if(0!=c)a=k.zd[a].We;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}k.cd.style.cursor=a}},_a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(t.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},pa:function(a,b){b=G(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function Md(a=[]){var b=Jd;a.unshift(ea);var c=a.length,d=ud(4*(c+1)),e=d,f;for(f of a)x[e>>2]=vd(f),e+=4;x[e>>2]=0;try{var g=b(c,d);pa=g;cc(g)}catch(m){bc(m)}}
function Nd(a=da){function b(){k.calledRun=!0;if(!oa){if(!k.noFSInit&&!ob){var c,d;ob=!0;c??=k.stdin;d??=k.stdout;e??=k.stderr;c?Vb("/dev","stdin",c):Jb("/dev/tty","/dev/stdin");d?Vb("/dev","stdout",null,d):Jb("/dev/tty","/dev/stdout");e?Vb("/dev","stderr",null,e):Jb("/dev/tty1","/dev/stderr");Ob("/dev/stdin",0);Ob("/dev/stdout",1);Ob("/dev/stderr",1)}Od.nc();pb=!1;k.onRuntimeInitialized?.();k.noInitialRun||Md(a);if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;){var e=
k.postRun.shift();za.push(e)}ya(za)}}if(0<Ca)Da=Nd;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ba();ya(Aa);0<Ca?Da=Nd:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);b()},1)):b()}}var Od;
(async function(){function a(c){c=Od=c.exports;Ed=k.__sapp_emsc_onpaste=c.oc;Fd=k.__sapp_html5_get_ask_leave_site=c.qc;Gd=k.__sapp_emsc_begin_drop=c.rc;Hd=k.__sapp_emsc_drop=c.sc;Id=k.__sapp_emsc_end_drop=c.tc;k.__sapp_emsc_invoke_fetch_cb=c.uc;k.__sapp_emsc_set_fullscreen_flag=c.vc;T=c.wc;zd=k._ma_device__on_notification_unlocked=c.xc;k._ma_malloc_emscripten=c.yc;k._ma_free_emscripten=c.zc;Ad=k._ma_device_process_pcm_frames_capture__webaudio=c.Ac;Bd=k._ma_device_process_pcm_frames_playback__webaudio=
c.Bc;Jd=k._main=c.Cc;Kd=c.Dc;xd=c.Ec;ud=c.Fc;wd=c.Gc;sa=c.mc;U=c.pc;ra();Ea("wasm-instantiate");return Od}Fa("wasm-instantiate");var b={a:Ld};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ta??=k.locateFile?k.locateFile("index.wasm",ia):ia+"index.wasm";return a((await wa(b)).instance)})();Nd();
