var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(k,q){if(b){var u=require("fs").readFileSync(k);return(new Uint8Array(u)).buffer}h.dataFileDownloads||(h.dataFileDownloads={});try{var x=await fetch(k)}catch(B){throw Error(`Network Error: ${k}`,
{e:B});}if(!x.ok)throw Error(`${x.status}: ${x.url}`);u=[];q=Number(x.headers.get("Content-Length")||q);let D=0;h.setStatus&&h.setStatus("Downloading data...");for(x=x.body.getReader();;){var {done:E,value:O}=await x.read();if(E)break;u.push(O);D+=O.length;h.dataFileDownloads[k]={loaded:D,total:q};let B=0,T=0;for(var H of Object.values(h.dataFileDownloads))B+=H.loaded,T+=H.total;h.setStatus&&h.setStatus(`Downloading data... (${B}/${T})`)}k=new Uint8Array(u.map(B=>B.length).reduce((B,T)=>B+T,0));H=
0;for(const B of u)k.set(B,H),H+=B.length;return k.buffer}async function e(k){k.FS_createPath("/","Assets",!0,!0);k.FS_createPath("/Assets","Fonts",!0,!0);k.FS_createPath("/Assets","Scenes",!0,!0);k.FS_createPath("/Assets","Scripts",!0,!0);k.FS_createPath("/Assets/Scripts","Boot",!0,!0);k.FS_createPath("/Assets/Scripts","Core",!0,!0);k.FS_createPath("/Assets/Scripts","Services",!0,!0);k.FS_createPath("/Assets/Scripts","Text",!0,!0);k.FS_createPath("/Assets/Scripts","Ui",!0,!0);k.FS_createPath("/Assets/Scripts",
"View",!0,!0);k.FS_createPath("/Assets","Sprites",!0,!0);k.FS_createPath("/Assets/Sprites","NewAssets",!0,!0);k.FS_createPath("/Assets/Sprites","UI",!0,!0);k.FS_createPath("/Assets/Sprites/UI","HUD",!0,!0);k.FS_createPath("/","assets",!0,!0);k.FS_createPath("/assets","builtin",!0,!0);for(var q of c.files)k.addRunDependency(`fp ${q.filename}`);k.addRunDependency("datafile_build/web/Farm/index.data");k.preloadResults||(k.preloadResults={});k.preloadResults["build/web/Farm/index.data"]={$e:!1};n||=await m;
(async function(u){if(!u)throw Error("Loading data file failed.");if(u.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+u.constructor.name);u=new Uint8Array(u);for(var x of c.files){var D=x.filename;k.FS_createDataFile(D,null,u.subarray(x.start,x.end),!0,!0,!0);k.removeRunDependency(`fp ${D}`)}k.removeRunDependency("datafile_build/web/Farm/index.data")})(n)}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=c.remote_package_size,m,n=h.getPreloadedPackage&&h.getPreloadedPackage(f,g);n||(m=d(f,g));h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))})({files:[{filename:"/Assets/.DS_Store",start:0,end:6148},{filename:"/Assets/Fonts/Onest-Bold.cowfont",start:6148,end:55157},{filename:"/Assets/Fonts/Onest-Bold.png",
start:55157,end:279703},{filename:"/Assets/Fonts/Onest-Bold.ttf",start:279703,end:376331},{filename:"/Assets/Fonts/Onest-Regular.cowfont",start:376331,end:425335},{filename:"/Assets/Fonts/Onest-Regular.png",start:425335,end:634578},{filename:"/Assets/Fonts/Onest-Regular.ttf",start:634578,end:730998},{filename:"/Assets/Scenes/.DS_Store",start:730998,end:737146},{filename:"/Assets/Scenes/Farm.json",start:737146,end:2578077},{filename:"/Assets/Scripts/.DS_Store",start:2578077,end:2584225},{filename:"/Assets/Scripts/Boot/GameBoot.bf",
start:2584225,end:2592100},{filename:"/Assets/Scripts/Boot/GameContext.bf",start:2592100,end:2596173},{filename:"/Assets/Scripts/Boot/GameLoop.bf",start:2596173,end:2599504},{filename:"/Assets/Scripts/Core/AchievementDefs.bf",start:2599504,end:2612933},{filename:"/Assets/Scripts/Core/AchievementSystem.bf",start:2612933,end:2622281},{filename:"/Assets/Scripts/Core/EconomyMath.bf",start:2622281,end:2628761},{filename:"/Assets/Scripts/Core/FarmManager.bf",start:2628761,end:2661133},{filename:"/Assets/Scripts/Core/GameConfig.bf",
start:2661133,end:2671535},{filename:"/Assets/Scripts/Core/GameStats.bf",start:2671535,end:2680288},{filename:"/Assets/Scripts/Core/LineId.bf",start:2680288,end:2682208},{filename:"/Assets/Scripts/Core/LineSim.bf",start:2682208,end:2688292},{filename:"/Assets/Scripts/Core/NumFormat.bf",start:2688292,end:2694056},{filename:"/Assets/Scripts/Core/Wallet.bf",start:2694056,end:2696925},{filename:"/Assets/Scripts/Services/AdService.bf",start:2696925,end:2698467},{filename:"/Assets/Scripts/Services/GameSettings.bf",
start:2698467,end:2700072},{filename:"/Assets/Scripts/Services/IapService.bf",start:2700072,end:2701142},{filename:"/Assets/Scripts/Services/SaveData.bf",start:2701142,end:2705403},{filename:"/Assets/Scripts/Services/SaveMigrations.bf",start:2705403,end:2708172},{filename:"/Assets/Scripts/Services/SaveService.bf",start:2708172,end:2727230},{filename:"/Assets/Scripts/Services/SettingsService.bf",start:2727230,end:2730820},{filename:"/Assets/Scripts/Services/TimeService.bf",start:2730820,end:2735436},
{filename:"/Assets/Scripts/Text/AchievementTexts.bf",start:2735436,end:2758932},{filename:"/Assets/Scripts/Text/Strings.bf",start:2758932,end:2782343},{filename:"/Assets/Scripts/Ui/AchBadge.bf",start:2782343,end:2784861},{filename:"/Assets/Scripts/Ui/AchievementPopup.bf",start:2784861,end:2788153},{filename:"/Assets/Scripts/Ui/AchievementsWindow.bf",start:2788153,end:2804244},{filename:"/Assets/Scripts/Ui/DogRow.bf",start:2804244,end:2810951},{filename:"/Assets/Scripts/Ui/FairCell.bf",start:2810951,
end:2811662},{filename:"/Assets/Scripts/Ui/FairWindow.bf",start:2811662,end:2828997},{filename:"/Assets/Scripts/Ui/FarmWindow.bf",start:2828997,end:2842303},{filename:"/Assets/Scripts/Ui/HudTab.bf",start:2842303,end:2846401},{filename:"/Assets/Scripts/Ui/HudView.bf",start:2846401,end:2859514},{filename:"/Assets/Scripts/Ui/KennelWindow.bf",start:2859514,end:2866583},{filename:"/Assets/Scripts/Ui/LineRow.bf",start:2866583,end:2876874},{filename:"/Assets/Scripts/Ui/ListRow.bf",start:2876874,end:2895205},
{filename:"/Assets/Scripts/Ui/ListWindow.bf",start:2895205,end:2901816},{filename:"/Assets/Scripts/Ui/MultChip.bf",start:2901816,end:2903566},{filename:"/Assets/Scripts/Ui/OfflinePopup.bf",start:2903566,end:2909731},{filename:"/Assets/Scripts/Ui/SettingsWindow.bf",start:2909731,end:2914885},{filename:"/Assets/Scripts/Ui/ShopWindow.bf",start:2914885,end:2922714},{filename:"/Assets/Scripts/Ui/Window.bf",start:2922714,end:2925119},{filename:"/Assets/Scripts/Ui/WindowId.bf",start:2925119,end:2927438},
{filename:"/Assets/Scripts/Ui/WindowManager.bf",start:2927438,end:2941654},{filename:"/Assets/Scripts/View/CameraController.bf",start:2941654,end:2948484},{filename:"/Assets/Scripts/View/FarmView.bf",start:2948484,end:2957465},{filename:"/Assets/Scripts/View/PenView.bf",start:2957465,end:2968614},{filename:"/Assets/Sprites/.DS_Store",start:2968614,end:2974762},{filename:"/Assets/Sprites/Game.coatlas",start:2974762,end:2986762},{filename:"/Assets/Sprites/Game.ktx2",start:2986762,end:3192670},{filename:"/Assets/Sprites/NewAssets/.DS_Store",
start:3192670,end:3198818},{filename:"/Assets/Sprites/NewAssets/Background2.ktx2",start:3198818,end:3608578},{filename:"/Assets/Sprites/UI.coatlas",start:3608578,end:3613240},{filename:"/Assets/Sprites/UI.ktx2",start:3613240,end:3734508},{filename:"/Assets/Sprites/UI/.DS_Store",start:3734508,end:3740656},{filename:"/Assets/Sprites/UI/HUD/.DS_Store",start:3740656,end:3746804},{filename:"/Assets/_atlases.txt",start:3746804,end:3746860},{filename:"/Assets/_texsizes.txt",start:3746860,end:3747185},{filename:"/Assets/project.json",
start:3747185,end:3749051},{filename:"/assets/builtin/Background.ktx2",start:3749051,end:3749431},{filename:"/assets/builtin/Checkmark.ktx2",start:3749431,end:3749932},{filename:"/assets/builtin/Knob.ktx2",start:3749932,end:3750462},{filename:"/assets/builtin/Roboto-Regular.cowfont",start:3750462,end:3761183},{filename:"/assets/builtin/Roboto-Regular.png",start:3761183,end:3804031},{filename:"/assets/builtin/UIMask.ktx2",start:3804031,end:3804456},{filename:"/assets/builtin/UISprite.ktx2",start:3804456,
end:3804881}],remote_package_size:3804881})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),l=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),p,r,qa,ra,t,v,w,y,sa;
function ta(){var a=ua.buffer;p=new Int8Array(a);qa=new Int16Array(a);r=new Uint8Array(a);ra=new Uint16Array(a);t=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);y=new Float64Array(a);sa=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ya(a){var b=va;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=0,Fa=null,Ga=()=>{Ea--;h.monitorRunDependencies?.(Ea);if(0==Ea&&Fa){var a=Fa;Fa=null;a()}},Ha=()=>{Ea++;h.monitorRunDependencies?.(Ea)},Ia=!0,Ja=new TextDecoder,Ka=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},A=(a,b,c)=>a?Ja.decode(r.subarray(a,Ka(r,a,b,c))):"",Ma=()=>{var a=t[+La>>2];La+=4;return a},Na=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):
".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Na(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Qa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ra=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>
crypto.getRandomValues(b)},Sa=a=>{(Sa=Ra())(a)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Na(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ua=a=>{var b=Ka(a,0);return Ja.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Xa=a=>{var b=Array(Wa(a)+1);a=C(a,b,0,b.length);
b.length=a;return b},Ya=[];function Za(a,b){Ya[a]={input:[],output:[],Vc:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new F(43);a.tty=b;a.seekable=!1},close(a){a.tty.Vc.fsync(a.tty)},fsync(a){a.tty.Vc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Vc.$d)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Vc.$d(a.tty)}catch(m){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Vc.Kd)throw new F(60);try{for(var e=0;e<d;e++)a.tty.Vc.Kd(a.tty,b[c+e])}catch(f){throw new F(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bb={$d(){a:{if(!Va.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Xa(a)}a=Va.shift()}return a},Kd(a,b){null===b||10===b?(ma(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(Ua(a.output)),a.output=[])},ve(){return{Me:25856,Oe:5,Le:191,Ne:35387,Ke:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},we(){return 0},xe(){return[24,80]}},cb={Kd(a,b){null===b||10===b?(l(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(l(Ua(a.output)),a.output=[])}},G={Sc:null,Uc(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.Sc||(G.Sc={dir:{node:{Yc:G.Gc.Yc,
Tc:G.Gc.Tc,lookup:G.Gc.lookup,qd:G.Gc.qd,rename:G.Gc.rename,unlink:G.Gc.unlink,rmdir:G.Gc.rmdir,readdir:G.Gc.readdir,symlink:G.Gc.symlink},stream:{Rc:G.Fc.Rc}},file:{node:{Yc:G.Gc.Yc,Tc:G.Gc.Tc},stream:{Rc:G.Fc.Rc,read:G.Fc.read,write:G.Fc.write,Hd:G.Fc.Hd,ee:G.Fc.ee}},link:{node:{Yc:G.Gc.Yc,Tc:G.Gc.Tc,readlink:G.Gc.readlink},stream:{}},Vd:{node:{Yc:G.Gc.Yc,Tc:G.Gc.Tc},stream:db}});c=eb(a,b,c,d);I(c.mode)?(c.Gc=G.Sc.dir.node,c.Fc=G.Sc.dir.stream,c.Ec={}):32768===(c.mode&61440)?(c.Gc=G.Sc.file.node,
c.Fc=G.Sc.file.stream,c.Hc=0,c.Ec=null):40960===(c.mode&61440)?(c.Gc=G.Sc.link.node,c.Fc=G.Sc.link.stream):8192===(c.mode&61440)&&(c.Gc=G.Sc.Vd.node,c.Fc=G.Sc.Vd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Ec[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},cf(a){return a.Ec?a.Ec.subarray?a.Ec.subarray(0,a.Hc):new Uint8Array(a.Ec):new Uint8Array(0)},Gc:{Yc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;I(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.Hc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Tc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Hc!=b&&(0==b?(a.Ec=null,a.Hc=0):(c=a.Ec,a.Ec=new Uint8Array(b),c&&a.Ec.set(c.subarray(0,Math.min(b,a.Hc))),a.Hc=b)))},lookup(){G.yd||(G.yd=new F(44),G.yd.stack="<generic error, no stack>");
throw G.yd;},qd(a,b,c,d){return G.createNode(a,b,c,d)},rename(a,b,c){try{var d=fb(b,c)}catch(f){}if(d){if(I(a.mode))for(var e in d.Ec)throw new F(55);gb(d)}delete a.parent.Ec[a.name];b.Ec[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Ec[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=fb(a,b),d;for(d in c.Ec)throw new F(55);delete a.Ec[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Ec)]},symlink(a,b,c){a=G.createNode(a,b,41471,
0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},Fc:{read(a,b,c,d,e){var f=a.node.Ec;if(e>=a.node.Hc)return 0;a=Math.min(a.node.Hc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Ec||a.Ec.subarray)){if(f)return a.Ec=b.subarray(c,c+d),a.Hc=d;if(0===a.Hc&&0===e)return a.Ec=b.slice(c,c+d),a.Hc=d;
if(e+d<=a.Hc)return a.Ec.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Ec?a.Ec.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Ec,a.Ec=new Uint8Array(f),0<a.Hc&&a.Ec.set(g.subarray(0,a.Hc),0));if(a.Ec.subarray&&b.subarray)a.Ec.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ec[e+f]=b[c+f];a.Hc=Math.max(a.Hc,e+d);return d},Rc(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Hc);if(0>b)throw new F(28);return b},Hd(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new F(43);a=a.node.Ec;if(e&2||!a||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new F(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{kd:e,Ge:d}},ee(a,b,c,d){G.Fc.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=async a=>{a=await ja(a);return new Uint8Array(a)},jb=[],kb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.df();for(var c of jb)if(c.canHandle(b))return c.handle(a,
b);return a},lb=null,mb={},nb=[],ob=1,pb=null,qb=!1,rb=!0,sb={},F=class{name="ErrnoError";constructor(a){this.Ic=a}},tb=class{Lc={};node=null;get flags(){return this.Lc.flags}set flags(a){this.Lc.flags=a}get position(){return this.Lc.position}set position(a){this.Lc.position=a}},ub=class{Gc={};Fc={};dd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Uc=a.Uc;this.id=ob++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ze(){return I(this.mode)}get ye(){return 8192===(this.mode&61440)}};
function vb(a,b={}){if(!a)throw new F(44);b.Bd??(b.Bd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=lb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Pa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oa(e+"/"+a[f]);try{d=fb(d,a[f])}catch(m){if(44===m?.Ic&&g&&b.Be)return{path:e};throw m;}!d.dd||g&&!b.Bd||(d=d.dd.root);if(40960===(d.mode&61440)&&(!g||b.Ad)){if(!d.Gc.readlink)throw new F(52);
d=d.Gc.readlink(d);"/"===d.charAt(0)||(d=Pa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new F(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.Uc.de,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}
function gb(a){var b=xb(a.parent.id,a.name);if(pb[b]===a)pb[b]=a.ed;else for(b=pb[b];b;){if(b.ed===a){b.ed=a.ed;break}b=b.ed}}function fb(a,b){var c=I(a.mode)?(c=yb(a,"x"))?c:a.Gc.lookup?0:2:54;if(c)throw new F(c);for(c=pb[xb(a.id,b)];c;c=c.ed){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Gc.lookup(a,b)}function eb(a,b,c,d){a=new ub(a,b,c,d);b=xb(a.parent.id,a.name);a.ed=pb[b];return pb[b]=a}function I(a){return 16384===(a&61440)}
function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){if(!I(a.mode))return 54;try{return fb(a,b),20}catch(c){}return yb(a,"wx")}
function Bb(a,b,c){try{var d=fb(a,b)}catch(e){return e.Ic}if(a=yb(a,"wx"))return a;if(c){if(!I(d.mode))return 54;if(d===d.parent||"/"===wb(d))return 10}else if(I(d.mode))return 31;return 0}function Cb(a){a=nb[a];if(!a)throw new F(8);return a}function Db(a,b=-1){a=Object.assign(new tb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!nb[b])break a;throw new F(33);}a.fd=b;return nb[b]=a}function Eb(a,b=-1){a=Db(a,b);a.Fc?.We?.(a);return a}
function Fb(a,b){var c=null?.Fc.Tc,d=c?null:a;c??=a.Gc.Tc;if(!c)throw new F(63);c(d,b)}var db={open(a){a.Fc=mb[a.node.rdev].Fc;a.Fc.open?.(a)},Rc(){throw new F(70);}};function $a(a,b){mb[a]={Fc:b}}function Gb(a,b){var c="/"===b;if(c&&lb)throw new F(10);if(!c&&b){var d=vb(b,{Bd:!1});b=d.path;d=d.node;if(d.dd)throw new F(10);if(!I(d.mode))throw new F(54);}b={type:a,hf:{},de:b,Ae:[]};a=a.Uc(b);a.Uc=b;b.root=a;c?lb=a:d&&(d.dd=b,d.Uc&&d.Uc.Ae.push(b))}
function Hb(a,b,c){var d=vb(a,{parent:!0}).node;a=Qa(a);if(!a)throw new F(28);if("."===a||".."===a)throw new F(20);var e=Ab(d,a);if(e)throw new F(e);if(!d.Gc.qd)throw new F(63);return d.Gc.qd(d,a,b,c)}function Ib(a,b=438){return Hb(a,b&4095|32768,0)}function J(a){return Hb(a,16895,0)}function Jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Hb(a,b|8192,c)}
function Kb(a,b){if(!Ta(a))throw new F(44);var c=vb(b,{parent:!0}).node;if(!c)throw new F(44);b=Qa(b);var d=Ab(c,b);if(d)throw new F(d);if(!c.Gc.symlink)throw new F(63);c.Gc.symlink(c,b,a)}function Lb(a){var b=vb(a,{parent:!0}).node;a=Qa(a);var c=fb(b,a),d=Bb(b,a,!0);if(d)throw new F(d);if(!b.Gc.rmdir)throw new F(63);if(c.dd)throw new F(10);b.Gc.rmdir(b,a);gb(c)}
function Mb(a){var b=vb(a,{parent:!0}).node;if(!b)throw new F(44);a=Qa(a);var c=fb(b,a),d=Bb(b,a,!1);if(d)throw new F(d);if(!b.Gc.unlink)throw new F(63);if(c.dd)throw new F(10);b.Gc.unlink(b,a);gb(c)}function Nb(a,b){a="string"==typeof a?vb(a,{Ad:!0}).node:a;Fb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Ve:void 0})}
function Ob(a,b,c=438){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=vb(a,{Ad:!(b&131072),Be:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new F(20);}else{if(e)throw new F(31);d=Hb(a,c|511,0);f=!0}if(!d)throw new F(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!I(d.mode))throw new F(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:I(d.mode)&&("r"!==zb(b)||b&576)?31:yb(d,zb(b)):44))throw new F(e);if(b&512&&!f){e=d;e="string"==typeof e?vb(e,{Ad:!0}).node:e;if(I(e.mode))throw new F(31);if(32768!==(e.mode&61440))throw new F(28);var g=yb(e,"w");if(g)throw new F(g);Fb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Db({node:d,path:wb(d),flags:b,seekable:!0,position:0,Fc:d.Fc,Ee:[],error:!1});e.Fc.open&&e.Fc.open(e);f&&Nb(d,c&511);!h.logReadFiles||b&1||a in sb||(sb[a]=1);return e}
function Pb(a){if(null===a.fd)throw new F(8);a.Dd&&(a.Dd=null);try{a.Fc.close&&a.Fc.close(a)}catch(b){throw b;}finally{nb[a.fd]=null}a.fd=null}function Qb(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.Fc.Rc)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.Fc.Rc(a,b,c);a.Ee=[]}
function Rb(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(I(a.node.mode))throw new F(31);if(!a.Fc.write)throw new F(28);a.seekable&&a.flags&1024&&Qb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F(70);b=a.Fc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Sb(a,b){a="string"==typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oa(a+"/"+c);try{J(d)}catch(e){if(20!=e.Ic)throw e;}a=d}}return d}function Tb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);return Ib(a,hb(c,d))}
function Ub(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:wb(a),g=b?Oa(a+"/"+b):a);a=hb(d,e);g=Ib(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Nb(g,a|146);b=Ob(g,577);Rb(b,c,0,c.length,0,f);Pb(b);Nb(g,a)}}
function Vb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);b=hb(!!c,!!d);Vb.be??(Vb.be=64);var e=Vb.be++<<8|0;$a(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var k=0,q=0;q<n;q++){try{var u=c()}catch(x){throw new F(29);}if(void 0===u&&0===k)throw new F(6);if(null===u||void 0===u)break;k++;g[m+q]=u}k&&(f.node.atime=Date.now());return k},write(f,g,m,n){for(var k=0;k<n;k++)try{d(g[m+k])}catch(q){throw new F(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return k}});
return Jb(a,b,e)}function Wb(a){if(!(a.ye||a.ze||a.link||a.Ec))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Ec=ka(a.url)}catch(b){throw new F(29);}}
function Xb(a,b,c,d,e){class f{vd=!1;Lc=[];td=void 0;Sd=0;Rd=0;get(k){if(!(k>this.length-1||0>k)){var q=k%this.chunkSize;return this.td(k/this.chunkSize|0)[q]}}pe(k){this.td=k}Td(){var k=new XMLHttpRequest;k.open("HEAD",c,!1);k.send(null);200<=k.status&&300>k.status||304===k.status||z("Couldn't load "+c+". Status: "+k.status);var q=Number(k.getResponseHeader("Content-length")),u,x=(u=k.getResponseHeader("Accept-Ranges"))&&"bytes"===u;k=(u=k.getResponseHeader("Content-Encoding"))&&"gzip"===u;var D=
1048576;x||(D=q);var E=this;E.pe(O=>{var H=O*D,B=(O+1)*D-1;B=Math.min(B,q-1);if("undefined"==typeof E.Lc[O]){var T=E.Lc;H>B&&z("invalid range ("+H+", "+B+") or no bytes requested!");B>q-1&&z("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);q!==D&&N.setRequestHeader("Range","bytes="+H+"-"+B);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);200<=N.status&&300>N.status||304===N.status||z("Couldn't load "+
c+". Status: "+N.status);H=void 0!==N.response?new Uint8Array(N.response||[]):Xa(N.responseText||"");T[O]=H}"undefined"==typeof E.Lc[O]&&z("doXHR failed!");return E.Lc[O]});if(k||!q)D=q=1,D=q=this.td(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Sd=q;this.Rd=D;this.vd=!0}get length(){this.vd||this.Td();return this.Sd}get chunkSize(){this.vd||this.Td();return this.Rd}}if(globalThis.XMLHttpRequest){ba||z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var m=void 0}else m=c,g=void 0;var n=Tb(a,b,d,e);g?n.Ec=g:m&&(n.Ec=null,n.url=m);Object.defineProperties(n,{Hc:{get:function(){return this.Ec.length}}});a={};for(const [k,q]of Object.entries(n.Fc))a[k]=(...u)=>{Wb(n);return q(...u)};a.read=(k,q,u,x,D)=>{Wb(n);k=k.node.Ec;if(D>=k.length)q=0;else{x=Math.min(k.length-D,x);if(k.slice)for(var E=0;E<x;E++)q[u+E]=k[D+E];else for(E=0;E<x;E++)q[u+E]=k.get(D+E);q=x}return q};a.Hd=()=>{Wb(n);z();throw new F(48);};n.Fc=a;return n}var K={};
function Yb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Cb(a).path;if(0==b.length)throw new F(44);return a+"/"+b}
var La=void 0,Zb=0,$b={},ac=a=>{a instanceof za||"unwind"==a||fa(1,a)},bc=a=>{pa=a;Ia||0<Zb||(h.onExit?.(a),oa=!0);fa(a,new za(a))},cc=()=>{if(!(Ia||0<Zb))try{var a=pa;pa=a;bc(a)}catch(b){ac(b)}},dc=a=>{if(!oa)try{a(),cc()}catch(b){ac(b)}},ec=[],fc=(a,b)=>{ec.length=0;for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;ec.push(112==c?v[b>>2]:106==c?sa[b>>3]:105==c?t[b>>2]:y[b>>3]);b+=d?8:4}return ec},pc=(a,b)=>{gc=a;hc=b;if(ic)if(jc||=!0,0==a)kc=function(){setTimeout(lc,Math.max(0,mc+b-performance.now())|
0)};else if(1==a)kc=function(){nc(lc)};else if(2==a){if(!oc)if(globalThis.setImmediate)oc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);oc=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}kc=function(){oc(lc)}}},yc=(a,b,c,d,e)=>{function f(){return g<qc?(cc(),!1):!0}ic=a;rc=
d;var g=qc;jc=!1;lc=function(){if(!oa)if(0<sc.length){var m=sc.shift();m.af(m.He);if(tc){var n=tc,k=0==n%1?n-1:Math.floor(n);tc=m.Pe?k:(8*n+(k+.5))/9}h.setStatus&&(m=h.statusMessage||"Please wait...",n=tc??0,k=uc.Xe??0,n?n<k?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(lc,0)}else if(f())if(vc=vc+1|0,1==gc&&1<hc&&0!=vc%hc)kc();else{0==gc&&(mc=performance.now());a:if(!oa){for(m of wc)if(!1===m())break a;dc(a);for(n of xc)n()}f()&&kc()}};
e||(0<b?pc(0,1E3/b):pc(1,1),kc());if(c)throw"unwind";},jc=!1,kc=null,qc=0,ic=null,rc=0,gc=0,hc=0,vc=0,sc=[],wc=[],xc=[];function zc(){kc=null;qc++}var Ac=0;function nc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ac)Ac=b+1E3/60;else for(;b+2>=Ac;)Ac+=1E3/60;setTimeout(a,Math.max(Ac-b,0))}}
var uc={},mc,lc,oc,tc,Bc=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?A(a):a;return Bc[a]||globalThis.document?.querySelector(a)},Cc=a=>0>Bc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Dc(a){var b=M.Kc[a];b.target.removeEventListener(b.Jc,b.Zd,b.Oc);M.Kc.splice(a,1)}function Ec(){if(navigator.userActivation?navigator.userActivation.isActive:M.Ed&&M.qe.xd){var a=M.Xc;M.Xc=[];for(var b of a)b.Ld(...b.Ud)}}
function P(a){if(!a.target)return-4;if(a.Mc)a.Zd=function(c){++M.Ed;M.qe=a;Ec();a.Qc(c);Ec();--M.Ed},a.target.addEventListener(a.Jc,a.Zd,a.Oc),M.Kc.push(a);else for(var b=0;b<M.Kc.length;++b)M.Kc[b].target==a.target&&M.Kc[b].Jc==a.Jc&&Dc(b--);return 0}function Fc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Ie:0,bf:0,Fd:0,rd:0,Qd:0,Nd:0,zd:0,Te:0,jf:0,Se:0,Cd:0,Jd:0,uf:0,Md:0,lf(){for(;M.Kc.length;)Dc(M.Kc.length-1);M.Xc=[]},Ed:0,Xc:[],Re(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of M.Xc)if(e.Ld==a&&d(e.Ud,c))return;M.Xc.push({Ld:a,ge:b,Ud:c});M.Xc.sort((f,g)=>f.ge<g.ge)},nf(a){M.Xc=M.Xc.filter(b=>b.Ld!=a)},Kc:[],mf:(a,b)=>{for(var c=0;c<M.Kc.length;++c)M.Kc[c].target!=a||b&&b!=M.Kc[c].Jc||Dc(c--)},pf(a){let b=!1;for(let c=0;c<
M.Kc.length;++c){const d=M.Kc[c];d.target===a.target&&d.Nc===a.Nc&&d.Mc===a.Mc&&d.Pc===a.Pc&&(Dc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Gc=(a,b,c,d,e,f)=>{M.zd||(M.zd=Q(256));a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var m=g.target.id?g.target.id:"",n=M.zd;C(Fc(g.target),r,n+0,128);C(m,r,n+128,128);R.get(d)(e,n,b)&&g.preventDefault()},Oc:c};return P(a)},Hc=(a,b,c,d,e)=>{M.Cd||(M.Cd=Q(276));return P({target:a,Jc:e,Nc:19,Pc:b,
Mc:d,Qc:f=>{var g=M.Cd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!m;p[g]=n;p[g+1]=M.fullscreenEnabled();var k=n?m:M.De,q=k?.id||"";C(Fc(k),r,g+2,128);C(q,r,g+130,128);t[g+260>>2]=k?k.clientWidth:0;t[g+264>>2]=k?k.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(M.De=m);R.get(d)(19,g,b)&&f.preventDefault()},Oc:c})},Ic=(a,b,c,d,e,f)=>{M.Fd||(M.Fd=Q(160));
a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var m=M.Fd;y[m>>3]=g.timeStamp;var n=m>>2;t[n+2]=g.location;p[m+12]=g.ctrlKey;p[m+13]=g.shiftKey;p[m+14]=g.altKey;p[m+15]=g.metaKey;p[m+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;C(g.key||"",r,m+32,32);C(g.code||"",r,m+64,32);C(g.char||"",r,m+96,32);C(g.locale||"",r,m+128,32);R.get(d)(e,m,b)&&g.preventDefault()},Oc:c};return P(a)},Jc=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;
p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Cc(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Kc=(a,b,c,d,e,f)=>{M.rd||(M.rd=Q(64));a=L(a);return P({target:a,xd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{Jc(M.rd,g,a);R.get(d)(e,M.rd,b)&&g.preventDefault()},Oc:c})},Lc=(a,b,c,d)=>{M.Jd||(M.Jd=Q(257));return P({target:a,Jc:"pointerlockchange",Nc:20,
Pc:b,Mc:d,Qc:e=>{var f=M.Jd,g=document.pointerLockElement;p[f]=!!g;var m=g?.id||"";C(Fc(g),r,f+1,128);C(m,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},Oc:c})},Mc=(a,b,c,d)=>P({target:a,Jc:"pointerlockerror",Nc:38,Pc:b,Mc:d,Qc:e=>{R.get(d)(38,0,b)&&e.preventDefault()},Oc:c}),Nc=(a,b,c,d)=>{M.Nd||(M.Nd=Q(36));a=L(a);return P({target:a,Jc:"resize",Nc:10,Pc:b,Mc:d,Qc:e=>{if(e.target==a){var f=document.body;if(f){var g=M.Nd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;
t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},Oc:c})},Oc=(a,b,c,d,e,f)=>{M.Md||(M.Md=Q(1552));a=L(a);return P({target:a,xd:"touchstart"==f||"touchend"==f,Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var m={},n=g.touches;for(var k of n)k.ae=k.fe=0,m[k.identifier]=k;for(var q of g.changedTouches)q.ae=1,m[q.identifier]=q;for(var u of g.targetTouches)m[u.identifier].fe=1;n=M.Md;y[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;
p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;k=n+16;q=Cc(a);u=0;for(let x of Object.values(m))if(m=k>>2,t[m]=x.identifier,t[m+1]=x.screenX,t[m+2]=x.screenY,t[m+3]=x.clientX,t[m+4]=x.clientY,t[m+5]=x.pageX,t[m+6]=x.pageY,p[k+28]=x.ae,p[k+29]=x.fe,t[m+8]=x.clientX-(q.left|0),t[m+9]=x.clientY-(q.top|0),k+=48,31<++u)break;t[n+8>>2]=u;R.get(d)(e,n,b)&&g.preventDefault()},Oc:c})},S,Pc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Qc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Rc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Sc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Tc=1,U=[],V=[],Uc=[],Vc=[],Wc=[],W=[],Xc=[],Yc=[],Zc=[],$c=[1,1,2,2,4,4,4,2,3,4,8],ad={},bd=4,cd=0,dd=a=>{for(var b=Tc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Tc++;return b},ed=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&dd(d);f?(f.name=g,d[g]=f):X||=1282;t[b+4*e>>2]=g}},fd=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Y.gd[a];if(b)return b;b=S.getParameter(34965);Y.gd[a]=S.createBuffer();S.bindBuffer(34963,Y.gd[a]);S.bufferData(34963,
1<<a,35048);S.bindBuffer(34963,b);return Y.gd[a]},hd=a=>{gd=!1;for(var b=0;b<Y.Gd;++b){var c=Y.$c[b];if(c.ad&&c.enabled){gd=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*$c[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=Y.hd[e];var g=Y.Zc[e];Y.Zc[e]=Y.Zc[e]+1&63;var m=f[g];m?e=m:(m=S.getParameter(34964),f[g]=S.createBuffer(),S.bindBuffer(34962,f[g]),S.bufferData(34962,1<<e,35048),S.bindBuffer(34962,m),e=f[g]);S.bindBuffer(34962,e);S.bufferSubData(34962,0,r.subarray(c.kd,c.kd+d));c.Pd.call(S,b,c.size,
c.type,c.Id,c.stride,0)}}},kd=(a,b)=>{a.Lc||(a.Lc=a.getContext,a.getContext=function(d,e){e=a.Lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ce?a.getContext("webgl2",b):a.getContext("webgl",b);return c?jd(c,b):0},jd=(a,b)=>{var c=dd(Yc),d={handle:c,attributes:b,version:b.ce,ud:a};a.canvas&&(a.canvas.Fe=d);Yc[c]=d;if("undefined"==typeof b.Yd||b.Yd)if((a=d)||(a=Y),!a.te){a.te=!0;b=a.ud;b.gf=b.getExtension("WEBGL_multi_draw");b.Ze=b.getExtension("EXT_polygon_offset_clamp");
b.Ye=b.getExtension("EXT_clip_control");b.vf=b.getExtension("WEBGL_polygon_mode");Pc(b);Qc(b);Rc(b);b.Ue=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ef=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Xd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Xd)b.Xd=b.getExtension("EXT_disjoint_timer_query");for(var e of Sc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.Gd=d.ud.getParameter(34921);
d.$c=[];for(e=0;e<d.Gd;e++)d.$c[e]={enabled:!1,ad:!1,size:0,type:0,Id:0,stride:0,kd:0,Pd:null};d.Zc=[];d.sd=[];d.Zc.length=d.sd.length=22;d.hd=[];d.ld=[];d.hd.length=d.ld.length=22;d.gd=[];d.gd.length=22;for(e=0;21>=e;++e){d.gd[e]=null;d.Zc[e]=d.sd[e]=0;d.hd[e]=[];d.ld[e]=[];a=d.hd[e];b=d.ld[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},X,Y,gd,ld=(a,b,c,d,e,f)=>{a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{R.get(d)(e,0,b)&&g.preventDefault()},Oc:c};P(a)},md=(a,b,c,d)=>{M.Qd||
(M.Qd=Q(96));return P({target:a,xd:!0,Jc:"wheel",Nc:9,Pc:b,Mc:d,Qc:e=>{var f=M.Qd;Jc(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},Oc:c})},nd=["default","low-power","high-performance"],od={},qd=()=>{if(!pd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in od)void 0===od[b]?delete a[b]:
a[b]=od[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);pd=c}return pd},pd,rd=[],sd=()=>{var a=Sc(S);return a=a.concat(a.map(b=>"GL_"+b))},td=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){X||=1282;return}c=sd().length;break;case 33307:case 33308:if(2>Y.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)t[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){X||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}t[b>>2]=c}else X||=1281},ud=a=>{var b=Wa(a)+1,c=Q(b);c&&C(a,r,c,b);return c},vd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),wd=a=>{a-=5120;return 0==a?p:1==a?r:2==a?qa:4==a?t:6==a?w:5==a||28922==a||28520==a||30779==a||30782==
a?v:ra},Z=a=>{var b=S.re;if(b){var c=b.md[a];"number"==typeof c&&(b.md[a]=c=S.getUniformLocation(b,b.ne[a]+(0<c?`[${c}]`:"")));return c}X||=1282},xd=[],yd=[],Ad=a=>{var b=Wa(a)+1,c=zd(b);C(a,r,c,b);return c},Dd=a=>{var b=Bd();a();Cd(b)},Ed=(a,b,c,d)=>{var e={string:k=>{var q=0;null!==k&&void 0!==k&&0!==k&&(q=Ad(k));return q},array:k=>{var q=zd(k.length);p.set(k,q);return q}};a=h["_"+a];var f=[],g=0;if(d)for(var m=0;m<d.length;m++){var n=e[c[m]];n?(0===g&&(g=Bd()),f[m]=n(d[m])):f[m]=d[m]}c=a(...f);
return c=function(k){0!==g&&Cd(g);return"string"===b?A(k):"boolean"===b?!!k:k}(c)};pb=Array(4096);Gb(G,"/");J("/tmp");J("/home");J("/home/web_user");(function(){J("/dev");$a(259,{read:()=>0,write:(d,e,f,g)=>g,Rc:()=>0});Jb("/dev/null",259);Za(1280,bb);Za(1536,cb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Sa(a),b=a.byteLength);return a[--b]};Vb("/dev","random",c);Vb("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Gb({Uc(){var b=eb(a,"fd",16895,73);b.Fc={Rc:G.Fc.Rc};b.Gc={lookup(c,d){c=+d;var e=Cb(c);c={parent:null,Uc:{de:"fake"},Gc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(nb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=nc;h.pauseMainLoop=zc;h.resumeMainLoop=function(){qc++;var a=gc,b=hc,c=ic;ic=null;yc(c,0,!1,rc,!0);pc(a,b);kc()};
h.preMainLoop&&wc.push(h.preMainLoop);h.postMainLoop&&xc.push(h.postMainLoop);var Fd=()=>{if(Y){var a=Y.hd;Y.hd=Y.ld;Y.ld=a;a=Y.Zc;Y.Zc=Y.sd;Y.sd=a;for(a=0;21>=a;++a)Y.Zc[a]=0}};"undefined"!=typeof uc&&wc.push(Fd);for(let a=0;32>a;++a)rd.push(Array(a));for(var Gd=new Float32Array(288),Hd=0;288>=Hd;++Hd)xd[Hd]=Gd.subarray(0,Hd);var Id=new Int32Array(288);for(Hd=0;288>=Hd;++Hd)yd[Hd]=Id.subarray(0,Hd);h.noExitRuntime&&(Ia=h.noExitRuntime);h.preloadPlugins&&(jb=h.preloadPlugins);h.print&&(ma=h.print);
h.printErr&&(l=h.printErr);h.wasmBinary&&(na=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=Ha;h.removeRunDependency=Ga;h.ccall=Ed;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Ed(a,b,c,f,d)};h.UTF8ToString=A;h.stringToNewUTF8=ud;
h.FS_preloadFile=async(a,b,c,d,e,f,g,m)=>{var n=b?Ta(Oa(a+"/"+b)):a,k=`cp ${n}`;Ha(k);try{var q=c;"string"==typeof c&&(q=await ib(c));q=await kb(q,n);m?.();f||Ub(a,b,q,d,e,g)}finally{Ga(k)}};h.FS_unlink=(...a)=>Mb(...a);h.FS_createPath=(...a)=>Sb(...a);h.FS_createDevice=(...a)=>Vb(...a);h.FS_createDataFile=(...a)=>Ub(...a);h.FS_createLazyFile=(...a)=>Xb(...a);
var Jd={735750:(a,b)=>{console.log(A(a,b))},735789:(a,b)=>{console.warn(A(a,b))},735829:(a,b)=>{console.error(A(a,b))},735870:()=>performance.now()},Kd,Ld,Md,Nd,Od,Q,Pd,Qd,Cd,zd,Bd,ua,R,Rd={yb:(a,b)=>{var c=Error().stack.toString(),d=c.split("\n");c="";var e=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),f=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of d){d=f.exec(g);if(5==d?.length)d=d[1];else if(d=e.exec(g),4<=d?.length)d=d[1];else{c+=g+"\n";continue}if("_emscripten_log"==d||"_emscripten_get_callstack"==
d)c=""}c=c.replace(/\s+$/,"");c=c.split("\n");for(e=0;e<c.length&&0===R.get(a)(0,b);e++);},a:(a,b,c,d)=>z(`Assertion failed: ${A(a)}, at: `+[b?A(b):"unknown filename",c,d?A(d):"unknown function"]),nb:(a,b)=>R.get(a)(b),ja:function(a,b,c){La=c;try{var d=Cb(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;nb[e];)e++;return Eb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==
typeof K||"ErrnoError"!==f.name)throw f;return-f.Ic}},sb:function(a,b,c){La=c;try{var d=Cb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Vc.ve){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Vc.we)for(e=
Ma(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ma();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ma();if(!d.Fc.ue)throw new F(59);return d.Fc.ue(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Vc.xe&&(f=[24,80],e=Ma(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.Ic}},qb:function(a,b,c,d){try{b=
A(b);b=Yb(a,b);switch(c&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}Hb(b,c,d);return 0}catch(e){if("undefined"==typeof K||"ErrnoError"!==e.name)throw e;return-e.Ic}},ia:function(a,b,c,d){La=d;try{b=A(b);b=Yb(a,b);var e=d?Ma():0;return Ob(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Ic}},lb:function(a){try{return a=A(a),Lb(a),0}catch(b){if("undefined"==typeof K||"ErrnoError"!==b.name)throw b;return-b.Ic}},mb:function(a,
b,c){try{b=A(b);b=Yb(a,b);if(c)if(512===c)Lb(b);else return-28;else Mb(b);return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Ic}},vb:()=>z(""),pb:()=>{Ia=!1;Zb=0},kb:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=qa[e+4>>1],g=32,m=nb[t[e>>2]];m&&(m.Fc.Ce?g=m.Fc.Ce(m,-1):g=5);(g&=f|24)&&c++;qa[e+6>>1]=g}return c}catch(n){if("undefined"==typeof K||"ErrnoError"!==n.name)throw n;return-n.Ic}},ib:(a,b)=>{$b[a]&&(clearTimeout($b[a].id),delete $b[a]);if(!b)return 0;
var c=setTimeout(()=>{delete $b[a];dc(()=>Qd(a,performance.now()))},b);$b[a]={id:c,tf:b};return 0},ub:function(a,b,c){if(!(0<=a&&3>=a))return 28;sa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Yb:(a,b,c)=>{b=fc(b,c);return Jd[a](...b)},C:(a,b,c)=>{b=fc(b,c);return Jd[a](...b)},Wb:()=>{zc();ic=null},tb:()=>Date.now(),W:()=>globalThis.devicePixelRatio??1,wa:(a,b,c)=>{a=L(a);if(!a)return-4;a=Cc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},q:()=>performance.now(),Xb:()=>
performance.now(),db:(a,b)=>{function c(d){R.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Z:(a,b,c,d)=>Gc(a,b,c,d,12,"blur"),T:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=
c;return 0},_:(a,b,c,d)=>Gc(a,b,c,d,13,"focus"),Y:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;Hc(a,b,c,d,"webkitfullscreenchange");return Hc(a,b,c,d,"fullscreenchange")},oa:(a,b,c,d)=>Ic(a,b,c,d,2,"keydown"),ka:(a,b,c,d)=>Ic(a,b,c,d,1,"keypress"),la:(a,b,c,d)=>Ic(a,b,c,d,3,"keyup"),eb:(a,b,c)=>{a=R.get(a);yc(a,b,c)},L:(a,b,c,d)=>Kc(a,b,c,d,5,"mousedown"),ta:(a,b,c,d)=>Kc(a,b,c,d,33,"mouseenter"),ra:(a,b,c,d)=>Kc(a,b,c,d,34,"mouseleave"),va:(a,b,c,d)=>Kc(a,b,c,d,8,"mousemove"),
H:(a,b,c,d)=>Kc(a,b,c,d,6,"mouseup"),aa:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Lc(a,b,c,d):-4:-1,$:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Mc(a,b,c,d):-4:-1,ca:(a,b,c,d)=>Nc(a,b,c,d),ba:(a,b,c,d)=>Oc(a,b,c,d,25,"touchcancel"),da:(a,b,c,d)=>Oc(a,b,c,d,23,"touchend"),ea:(a,b,c,d)=>Oc(a,b,c,d,24,"touchmove"),fa:(a,b,c,d)=>Oc(a,b,c,d,22,"touchstart"),X:(a,b,c,d)=>{ld(a,b,c,d,31,"webglcontextlost");return 0},V:(a,b,c,d)=>{ld(a,b,c,d,32,"webglcontextrestored");return 0},pa:(a,
b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?md(a,b,c,d):-1:-4,Ua:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:nd[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],ce:t[c+4],ff:t[c+5],Yd:p[b+24],se:p[b+25],kf:t[c+7],qf:p[b+32]};a=L(a);return!a||b.se?0:kd(a,b)},Na:a=>{Y=Yc[a];h.ctx=S=Y?.ud;return!a||S?0:-5},wb:(a,b)=>{var c=0,d=0,e;for(e of qd()){var f=b+c;v[a+d>>2]=f;c+=C(e,r,f,Infinity)+
1;d+=4}return 0},xb:(a,b)=>{var c=qd();v[a>>2]=c.length;a=0;for(var d of c)a+=Wa(d)+1;v[b>>2]=a;return 0},zb:a=>{pa=a;bc(a)},y:function(a){try{var b=Cb(a);Pb(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.Ic}},ha:function(a,b,c,d){try{a:{var e=Cb(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var k=e,q=m,u=n,x=f,D=p;if(0>u||0>x)throw new F(28);if(null===k.fd)throw new F(8);if(1===(k.flags&2097155))throw new F(8);if(I(k.node.mode))throw new F(31);
if(!k.Fc.read)throw new F(28);var E="undefined"!=typeof x;if(!E)x=k.position;else if(!k.seekable)throw new F(70);var O=k.Fc.read(k,D,q,u,x);E||(k.position+=O);var H=O;if(0>H){var B=-1;break a}b+=H;if(H<n)break;"undefined"!=typeof f&&(f+=H)}B=b}v[d>>2]=B;return 0}catch(T){if("undefined"==typeof K||"ErrnoError"!==T.name)throw T;return T.Ic}},rb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Cb(a);Qb(e,b,c);sa[d>>3]=BigInt(e.position);e.Dd&&
0===b&&0===c&&(e.Dd=null);return 0}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return f.Ic}},ga:function(a,b,c,d){try{a:{var e=Cb(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var k=Rb(e,p,m,n,f);if(0>k){var q=-1;break a}b+=k;if(k<n)break;"undefined"!=typeof f&&(f+=k)}q=b}v[d>>2]=q;return 0}catch(u){if("undefined"==typeof K||"ErrnoError"!==u.name)throw u;return u.Ic}},A:a=>S.activeTexture(a),v:(a,b)=>{S.attachShader(V[a],W[b])},c:(a,b)=>{if(b&&!U[b]){var c=S.createBuffer();
c.name=b;U[b]=c}34962==a?S.bd=b:34963==a&&(S.jd=b);35051==a?S.Wd=b:35052==a&&(S.cd=b);S.bindBuffer(a,U[b])},qa:(a,b,c)=>{S.bindBufferBase(a,b,U[c])},Ba:(a,b,c,d,e)=>{S.bindBufferRange(a,b,U[c],d,e)},h:(a,b)=>{S.bindFramebuffer(a,Uc[b])},Ia:(a,b)=>{S.bindRenderbuffer(a,Vc[b])},z:(a,b)=>{S.bindSampler(a,Zc[b])},i:(a,b)=>{S.bindTexture(a,Wc[b])},U:a=>{S.bindVertexArray(Xc[a]);a=S.getParameter(34965);S.jd=a?a.name|0:0},F:(a,b,c,d)=>S.blendColor(a,b,c,d),G:(a,b)=>S.blendEquationSeparate(a,b),I:(a,b,c,
d)=>S.blendFuncSeparate(a,b,c,d),_b:(a,b,c,d,e,f,g,m,n,k)=>S.blitFramebuffer(a,b,c,d,e,f,g,m,n,k),Ta:(a,b,c,d)=>{2<=Y.version?c&&b?S.bufferData(a,r,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?r.subarray(c,c+b):b,d)},w:(a,b,c,d)=>{2<=Y.version?c&&S.bufferSubData(a,b,r,d,c):S.bufferSubData(a,b,r.subarray(d,d+c))},Hb:a=>S.checkFramebufferStatus(a),Fa:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),K:(a,b,c)=>{S.clearBufferfv(a,b,w,c>>2)},Ea:(a,b,c)=>{S.clearBufferiv(a,b,t,c>>2)},l:(a,b,c,d)=>{S.colorMask(!!a,!!b,
!!c,!!d)},Jb:a=>{S.compileShader(W[a])},Pb:(a,b,c,d,e,f,g,m,n)=>{2<=Y.version?S.cd||!m?S.compressedTexSubImage2D(a,b,c,d,e,f,g,m,n):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r,n,m):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+m))},Nb:(a,b,c,d,e,f,g,m,n,k,q)=>{S.cd?S.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,k,q):S.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,r,q,k)},Oa:()=>{var a=dd(V),b=S.createProgram();b.name=a;b.pd=b.nd=b.od=0;b.Od=1;V[a]=b;return a},Lb:a=>{var b=dd(W);W[b]=S.createShader(a);
return b},E:a=>S.cullFace(a),Qb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=U[d];e&&(S.deleteBuffer(e),e.name=0,U[d]=null,d==S.bd&&(S.bd=0),d==S.jd&&(S.jd=0),d==S.Wd&&(S.Wd=0),d==S.cd&&(S.cd=0))}},x:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Uc[d];e&&(S.deleteFramebuffer(e),e.name=0,Uc[d]=null)}},o:a=>{if(a){var b=V[a];b?(S.deleteProgram(b),b.name=0,V[a]=null):X||=1281}},R:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Vc[d];e&&(S.deleteRenderbuffer(e),e.name=0,Vc[d]=null)}},Xa:(a,b)=>
{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Zc[d];e&&(S.deleteSampler(e),e.name=0,Zc[d]=null)}},m:a=>{if(a){var b=W[a];b?(S.deleteShader(b),W[a]=null):X||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Wc[d];e&&(S.deleteTexture(e),e.name=0,Wc[d]=null)}},Wa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];S.deleteVertexArray(Xc[d]);Xc[d]=null}},r:a=>S.depthFunc(a),s:a=>{S.depthMask(!!a)},d:a=>S.disable(a),ua:a=>{Y.$c[a].enabled=!1;S.disableVertexAttribArray(a)},ac:(a,b,c)=>{hd(b+c);S.drawArrays(a,
b,c);gd&&S.bindBuffer(34962,U[S.bd])},bc:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},M:(a,b)=>{for(var c=rd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];S.drawBuffers(c)},cc:(a,b,c,d)=>{var e=0;if(!S.jd){var f=1*$c[c-5120]*b;var g=fd(f);S.bindBuffer(34963,g);S.bufferSubData(34963,0,r.subarray(d,d+f));if(0<b)for(g=0;g<Y.Gd;++g)if(f=Y.$c[g],f.ad&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:X||=1282;return}e=(new e(r.buffer,d,b)).reduce((m,
n)=>Math.max(m,n))+1;break}d=0}hd(e);S.drawElements(a,b,c,d);gd&&S.bindBuffer(34962,U[S.bd]);S.jd||S.bindBuffer(34963,null)},dc:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},g:a=>S.enable(a),xa:a=>{Y.$c[a].enabled=!0;S.enableVertexAttribArray(a)},j:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Vc[d])},e:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,Wc[d],e)},u:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,Wc[c],d,e)},D:a=>S.frontFace(a),Va:(a,b)=>{ed(a,b,"createBuffer",U)},S:(a,b)=>{ed(a,b,"createFramebuffer",
Uc)},Ja:(a,b)=>{ed(a,b,"createRenderbuffer",Vc)},Pa:(a,b)=>{ed(a,b,"createSampler",Zc)},Sa:(a,b)=>{ed(a,b,"createTexture",Wc)},Za:(a,b)=>{ed(a,b,"createVertexArray",Xc)},Ka:(a,b)=>S.getAttribLocation(V[a],A(b)),b:(a,b)=>td(a,b),Ma:(a,b,c,d)=>{a=S.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,r,d,b):0;c&&(t[c>>2]=b)},O:(a,b,c)=>{if(c)if(a>=Tc)X||=1281;else if(a=V[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.pd){var d=
S.getProgramParameter(a,35718);for(b=0;b<d;++b)a.pd=Math.max(a.pd,S.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.pd}else if(35722==b){if(!a.nd)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.nd=Math.max(a.nd,S.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.nd}else if(35381==b){if(!a.od)for(d=S.getProgramParameter(a,35382),b=0;b<d;++b)a.od=Math.max(a.od,S.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.od}else t[c>>2]=S.getProgramParameter(a,b);else X||=1281},Ib:(a,b,c,d)=>{a=S.getShaderInfoLog(W[a]);
null===a&&(a="(unknown error)");b=0<b&&d?C(a,r,d,b):0;c&&(t[c>>2]=b)},na:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(W[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=S.getShaderParameter(W[a],b):X||=1281},_a:(a,b)=>{if(2>Y.version)return X||=1282,0;var c=ad[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=sd().map(ud),c=ad[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},
N:(a,b)=>{b=A(b);if(a=V[a]){var c=a,d=c.md,e=c.oe,f;if(!d){c.md=d={};c.ne={};var g=S.getProgramParameter(c,35718);for(f=0;f<g;++f){var m=S.getActiveUniform(c,f);var n=m.name;m=m.size;var k=vd(n);k=0<k?n.slice(0,k):n;var q=c.Od;c.Od+=m;e[k]=[m,q];for(n=0;n<m;++n)d[q]=n,c.ne[q++]=k}}c=a.md;d=0;e=b;f=vd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.oe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else X||=1281;return-1},Zb:(a,b,c)=>{for(var d=rd[b],e=0;e<b;e++)d[e]=
t[c+4*e>>2];S.invalidateFramebuffer(a,d)},P:a=>{a=V[a];S.linkProgram(a);a.md=0;a.oe={}},Ya:(a,b)=>{3317==a?bd=b:3314==a&&(cd=b);S.pixelStorei(a,b)},J:(a,b)=>S.polygonOffset(a,b),$b:a=>S.readBuffer(a),Ha:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),Q:(a,b,c)=>{S.samplerParameterf(Zc[a],b,c)},f:(a,b,c)=>{S.samplerParameteri(Zc[a],b,c)},t:(a,b,c,d)=>S.scissor(a,b,c,d),Kb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=A(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);S.shaderSource(W[a],e)},Sb:(a,b,c)=>S.stencilFunc(a,
b,c),Da:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),n:a=>S.stencilMask(a),Rb:(a,b,c)=>S.stencilOp(a,b,c),Ca:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Ra:(a,b,c,d,e)=>S.texStorage2D(a,b,c,d,e),Qa:(a,b,c,d,e,f)=>S.texStorage3D(a,b,c,d,e,f),Ob:(a,b,c,d,e,f,g,m,n)=>{if(2<=Y.version){if(S.cd){S.texSubImage2D(a,b,c,d,e,f,g,m,n);return}if(n){var k=wd(m);S.texSubImage2D(a,b,c,d,e,f,g,m,k,n>>>31-Math.clz32(k.BYTES_PER_ELEMENT));return}}if(n){k=wd(m);var q=f*((cd||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,
29846:3,29847:4}[g-6402]||1)*k.BYTES_PER_ELEMENT+bd-1&-bd);n=k.subarray(n>>>31-Math.clz32(k.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(k.BYTES_PER_ELEMENT))}else n=null;S.texSubImage2D(a,b,c,d,e,f,g,m,n)},Mb:(a,b,c,d,e,f,g,m,n,k,q)=>{if(S.cd)S.texSubImage3D(a,b,c,d,e,f,g,m,n,k,q);else if(q){var u=wd(k);S.texSubImage3D(a,b,c,d,e,f,g,m,n,k,u,q>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,f,g,m,n,k,null)},mc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1fv(Z(a),w,c>>2,b);else{if(288>=b)for(var d=
xd[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1fv(Z(a),d)}},La:(a,b)=>{S.uniform1i(Z(a),b)},ic:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1iv(Z(a),t,c>>2,b);else{if(288>=b)for(var d=yd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);S.uniform1iv(Z(a),d)}},lc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2fv(Z(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=xd[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);S.uniform2fv(Z(a),
d)}},hc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2iv(Z(a),t,c>>2,2*b);else{if(144>=b){b*=2;for(var d=yd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+8*b>>2);S.uniform2iv(Z(a),d)}},kc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3fv(Z(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=xd[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);S.uniform3fv(Z(a),d)}},gc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3iv(Z(a),t,c>>2,
3*b);else{if(96>=b){b*=3;for(var d=yd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);S.uniform3iv(Z(a),d)}},jc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4fv(Z(a),w,c>>2,4*b);else{if(72>=b){var d=xd[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);S.uniform4fv(Z(a),d)}},fc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4iv(Z(a),t,c>>2,4*b);else{if(72>=b){b*=
4;for(var d=yd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);S.uniform4iv(Z(a),d)}},ec:(a,b,c,d)=>{if(2<=Y.version)b&&S.uniformMatrix4fv(Z(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=xd[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+
12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=w.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(Z(a),!!c,e)}},p:a=>{a=V[a];S.useProgram(a);S.re=a},ya:(a,b)=>{S.vertexAttribDivisor(a,b)},za:(a,b,c,d,e)=>{var f=Y.$c[a];S.bd?(f.ad=!1,S.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Id=!1,f.stride=d,f.kd=e,f.ad=!0,f.Pd=function(g,m,n,k,q,u){this.vertexAttribIPointer(g,m,n,q,u)})},Aa:(a,b,c,d,e,f)=>{var g=Y.$c[a];S.bd?(g.ad=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=
c,g.Id=d,g.stride=e,g.kd=f,g.ad=!0,g.Pd=function(m,n,k,q,u,x){this.vertexAttribPointer(m,n,k,q,u,x)})},Ga:(a,b,c,d)=>S.viewport(a,b,c,d),Eb:function(){try{if("undefined"===typeof S||!S)return 0;var a=S.getExtension("WEBGL_debug_renderer_info"),b=a?S.getParameter(a.UNMASKED_RENDERER_WEBGL):S.getParameter(S.RENDERER)||"";return"string"!==typeof b?0:/Apple/i.test(b)?1:0}catch(c){return 0}},Db:function(a,b,c,d,e,f,g){var m=globalThis.CowPlatform;if(!m)return-1;try{return m.call(a,b,c,d?A(d,e):null,f?
A(f,g):null)|0}catch(n){return-1}},Cb:function(){var a=globalThis.CowPlatform.cur;return a?a.c|0:0},Bb:function(){var a=globalThis.CowPlatform.cur;return a&&null!=a.s?ud(a.s):0},Ab:function(a){var b=globalThis.CowPlatform;if(!b)return 0;a=b.getStr(a);return null==a||""===a?0:ud(a)},ma:function(){var a=globalThis.CowPlatform;if(!a)return-1;var b=a.queue;if(0===b.length)return-1;a.cur=b.shift();return a.cur.k|0},Gb:function(){try{var a=globalThis.localStorage;if(!a)return 0;var b=a.getItem("ScopeBee.PlayerPrefs");
return null===b?0:ud(b)}catch(c){return 0}},Fb:function(a,b){try{var c=globalThis.localStorage;c&&c.setItem("ScopeBee.PlayerPrefs",A(a,b))}catch(d){}},ob:bc,hb:function(){h.he=a=>{0!=Ld()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.he)},gb:function(){h.me=a=>{const b=a.clipboardData.getData("text");Dd(()=>{const c=Ad(b);Kd(c)})};window.addEventListener("paste",h.me)},fb:function(){h.rf=[];h.ie=b=>{b.stopPropagation();b.preventDefault()};h.je=b=>{b.stopPropagation();
b.preventDefault()};h.ke=b=>{b.stopPropagation();b.preventDefault()};h.le=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.sf=c;Md(c.length);for(let e=0;e<c.length;e++)Dd(()=>{const f=Ad(c[e].name);Nd(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Od(b.clientX,b.clientY,d)};const a=h.Wc;a.addEventListener("dragenter",h.ie,!1);a.addEventListener("dragleave",h.je,!1);a.addEventListener("dragover",h.ke,!1);a.addEventListener("drop",h.le,
!1)},ab:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},bb:function(a){h.wd&&(URL.revokeObjectURL(h.wd[a].Je),h.wd[a]=null)},nc:function(a,b){0!==b&&(document.title=A(b));a=A(a);void 0!==h.canvas&&("object"===typeof h.canvas?Bc[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Wc=L(a);h.Wc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Wc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",
a)},Vb:function(){window.removeEventListener("beforeunload",h.he)},Ub:function(){window.removeEventListener("paste",h.me)},Tb:function(){const a=h.Wc;a.removeEventListener("dragenter",h.ie);a.removeEventListener("dragleave",h.je);a.removeEventListener("dragover",h.ke);a.removeEventListener("drop",h.le)},B:function(){h.Wc&&h.Wc.requestPointerLock&&h.Wc.requestPointerLock()},cb:function(a,b,c){if(h.Wc){if(0===b)a="none";else if(0!=c)a=h.wd[a].Qe;else switch(a){case 0:a="auto";break;case 1:a="default";
break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Wc.style.cursor=a}},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(r.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");
a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},sa:function(a,b){b=A(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function Sd(a=[]){var b=Pd;a.unshift(ea);var c=a.length,d=zd(4*(c+1)),e=d,f;for(f of a)v[e>>2]=Ad(f),e+=4;v[e>>2]=0;try{var g=b(c,d);pa=g;bc(g)}catch(m){ac(m)}}
function Td(a=da){function b(){h.calledRun=!0;if(!oa){if(!h.noFSInit&&!qb){var c,d;qb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Vb("/dev","stdin",c):Kb("/dev/tty","/dev/stdin");d?Vb("/dev","stdout",null,d):Kb("/dev/tty","/dev/stdout");e?Vb("/dev","stderr",null,e):Kb("/dev/tty1","/dev/stderr");Ob("/dev/stdin",0);Ob("/dev/stdout",1);Ob("/dev/stderr",1)}Ud.pc();rb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Sd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ba.push(e)}Aa(Ba)}}if(0<Ea)Fa=Td;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<Ea?Fa=Td:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Ud;
(async function(){function a(c){c=Ud=c.exports;Kd=h.__sapp_emsc_onpaste=c.qc;Ld=h.__sapp_html5_get_ask_leave_site=c.sc;Md=h.__sapp_emsc_begin_drop=c.tc;Nd=h.__sapp_emsc_drop=c.uc;Od=h.__sapp_emsc_end_drop=c.vc;h.__sapp_emsc_invoke_fetch_cb=c.wc;h.__sapp_emsc_set_fullscreen_flag=c.xc;Q=c.yc;Pd=h._main=c.zc;Qd=c.Ac;Cd=c.Bc;zd=c.Cc;Bd=c.Dc;ua=c.oc;R=c.rc;ta();Ga("wasm-instantiate");return Ud}Ha("wasm-instantiate");var b={a:Rd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,
e))})});va??=h.locateFile?h.locateFile("index.wasm",ia):ia+"index.wasm";return a((await ya(b)).instance)})();Td();
