var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(l,q){if(b){var u=require("fs").readFileSync(l);return(new Uint8Array(u)).buffer}h.dataFileDownloads||(h.dataFileDownloads={});try{var x=await fetch(l)}catch(A){throw Error(`Network Error: ${l}`,
{e:A});}if(!x.ok)throw Error(`${x.status}: ${x.url}`);u=[];q=Number(x.headers.get("Content-Length")||q);let C=0;h.setStatus&&h.setStatus("Downloading data...");for(x=x.body.getReader();;){var {done:D,value:O}=await x.read();if(D)break;u.push(O);C+=O.length;h.dataFileDownloads[l]={loaded:C,total:q};let A=0,T=0;for(var H of Object.values(h.dataFileDownloads))A+=H.loaded,T+=H.total;h.setStatus&&h.setStatus(`Downloading data... (${A}/${T})`)}l=new Uint8Array(u.map(A=>A.length).reduce((A,T)=>A+T,0));H=
0;for(const A of u)l.set(A,H),H+=A.length;return l.buffer}async function e(l){l.FS_createPath("/","Assets",!0,!0);l.FS_createPath("/Assets","Prefab",!0,!0);l.FS_createPath("/Assets","Scenes",!0,!0);l.FS_createPath("/","assets",!0,!0);l.FS_createPath("/assets","builtin",!0,!0);for(var q of c.files)l.addRunDependency(`fp ${q.filename}`);l.addRunDependency("datafile_build/web/Empty/index.data");l.preloadResults||(l.preloadResults={});l.preloadResults["build/web/Empty/index.data"]={Re:!1};n||=await m;
(async function(u){if(!u)throw Error("Loading data file failed.");if(u.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+u.constructor.name);u=new Uint8Array(u);for(var x of c.files){var C=x.filename;l.FS_createDataFile(C,null,u.subarray(x.start,x.end),!0,!0,!0);l.removeRunDependency(`fp ${C}`)}l.removeRunDependency("datafile_build/web/Empty/index.data")})(n)}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+
"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=c.remote_package_size,m,n=h.getPreloadedPackage&&h.getPreloadedPackage(f,g);n||(m=d(f,g));h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))})({files:[{filename:"/Assets/MainScene.json",start:0,end:2},{filename:"/Assets/Prefab/TestPrefab.prefab",start:2,end:3106},{filename:"/Assets/Scenes/MainScene.json",
start:3106,end:3801},{filename:"/Assets/project.json",start:3801,end:5476},{filename:"/assets/builtin/Background.png",start:5476,end:5648},{filename:"/assets/builtin/Checkmark.png",start:5648,end:6138},{filename:"/assets/builtin/Knob.png",start:6138,end:6620},{filename:"/assets/builtin/UIMask.png",start:6620,end:6909},{filename:"/assets/builtin/UISprite.png",start:6909,end:7198}],remote_package_size:7198})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;
"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),p,r,qa,ra,t,v,w,y,sa;
function ta(){var a=ua.buffer;p=new Int8Array(a);qa=new Int16Array(a);r=new Uint8Array(a);ra=new Uint16Array(a);t=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);y=new Float64Array(a);sa=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ya(a){var b=va;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=0,Fa=null,Ga=()=>{Ea--;h.monitorRunDependencies?.(Ea);if(0==Ea&&Fa){var a=Fa;Fa=null;a()}},Ha=()=>{Ea++;h.monitorRunDependencies?.(Ea)},Ia=!0,Ja=new TextDecoder,Ka=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},B=(a,b,c)=>a?Ja.decode(r.subarray(a,Ka(r,a,b,c))):"",Ma=()=>{var a=t[+La>>2];La+=4;return a},Na=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):
".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Na(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Qa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ra=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>
crypto.getRandomValues(b)},Sa=a=>{(Sa=Ra())(a)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Na(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ua=a=>{var b=Ka(a,0);return Ja.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Xa=a=>{var b=Array(Wa(a)+1);a=E(a,b,0,b.length);
b.length=a;return b},Ya=[];function Za(a,b){Ya[a]={input:[],output:[],Mc:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new F(43);a.tty=b;a.seekable=!1},close(a){a.tty.Mc.fsync(a.tty)},fsync(a){a.tty.Mc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Mc.Pd)throw new F(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Mc.Pd(a.tty)}catch(m){throw new F(29);}if(void 0===g&&0===e)throw new F(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Mc.zd)throw new F(60);try{for(var e=0;e<d;e++)a.tty.Mc.zd(a.tty,b[c+e])}catch(f){throw new F(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bb={Pd(){a:{if(!Va.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Xa(a)}a=Va.shift()}return a},zd(a,b){null===b||10===b?(ma(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(Ua(a.output)),a.output=[])},me(){return{De:25856,Fe:5,Ce:191,Ee:35387,Be:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ne(){return 0},oe(){return[24,80]}},cb={zd(a,b){null===b||10===b?(k(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(Ua(a.output)),a.output=[])}},G={Jc:null,Lc(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.Jc||(G.Jc={dir:{node:{Pc:G.xc.Pc,
Kc:G.xc.Kc,lookup:G.xc.lookup,gd:G.xc.gd,rename:G.xc.rename,unlink:G.xc.unlink,rmdir:G.xc.rmdir,readdir:G.xc.readdir,symlink:G.xc.symlink},stream:{Ic:G.wc.Ic}},file:{node:{Pc:G.xc.Pc,Kc:G.xc.Kc},stream:{Ic:G.wc.Ic,read:G.wc.read,write:G.wc.write,wd:G.wc.wd,Ud:G.wc.Ud}},link:{node:{Pc:G.xc.Pc,Kc:G.xc.Kc,readlink:G.xc.readlink},stream:{}},Kd:{node:{Pc:G.xc.Pc,Kc:G.xc.Kc},stream:db}});c=eb(a,b,c,d);I(c.mode)?(c.xc=G.Jc.dir.node,c.wc=G.Jc.dir.stream,c.vc={}):32768===(c.mode&61440)?(c.xc=G.Jc.file.node,
c.wc=G.Jc.file.stream,c.yc=0,c.vc=null):40960===(c.mode&61440)?(c.xc=G.Jc.link.node,c.wc=G.Jc.link.stream):8192===(c.mode&61440)&&(c.xc=G.Jc.Kd.node,c.wc=G.Jc.Kd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.vc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},Ue(a){return a.vc?a.vc.subarray?a.vc.subarray(0,a.yc):new Uint8Array(a.vc):new Uint8Array(0)},xc:{Pc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;I(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.yc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Kc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.yc!=b&&(0==b?(a.vc=null,a.yc=0):(c=a.vc,a.vc=new Uint8Array(b),c&&a.vc.set(c.subarray(0,Math.min(b,a.yc))),a.yc=b)))},lookup(){G.nd||(G.nd=new F(44),G.nd.stack="<generic error, no stack>");
throw G.nd;},gd(a,b,c,d){return G.createNode(a,b,c,d)},rename(a,b,c){try{var d=fb(b,c)}catch(f){}if(d){if(I(a.mode))for(var e in d.vc)throw new F(55);gb(d)}delete a.parent.vc[a.name];b.vc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.vc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=fb(a,b),d;for(d in c.vc)throw new F(55);delete a.vc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.vc)]},symlink(a,b,c){a=G.createNode(a,b,41471,
0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},wc:{read(a,b,c,d,e){var f=a.node.vc;if(e>=a.node.yc)return 0;a=Math.min(a.node.yc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.vc||a.vc.subarray)){if(f)return a.vc=b.subarray(c,c+d),a.yc=d;if(0===a.yc&&0===e)return a.vc=b.slice(c,c+d),a.yc=d;
if(e+d<=a.yc)return a.vc.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.vc?a.vc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.vc,a.vc=new Uint8Array(f),0<a.yc&&a.vc.set(g.subarray(0,a.yc),0));if(a.vc.subarray&&b.subarray)a.vc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.vc[e+f]=b[c+f];a.yc=Math.max(a.yc,e+d);return d},Ic(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.yc);if(0>b)throw new F(28);return b},wd(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new F(43);a=a.node.vc;if(e&2||!a||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new F(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{$c:e,xe:d}},Ud(a,b,c,d){G.wc.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=async a=>{a=await ja(a);return new Uint8Array(a)},jb=[],kb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.Ve();for(var c of jb)if(c.canHandle(b))return c.handle(a,
b);return a},lb=null,mb={},nb=[],ob=1,pb=null,qb=!1,rb=!0,sb={},F=class{name="ErrnoError";constructor(a){this.zc=a}},tb=class{Dc={};node=null;get flags(){return this.Dc.flags}set flags(a){this.Dc.flags=a}get position(){return this.Dc.position}set position(a){this.Dc.position=a}},ub=class{xc={};wc={};Vc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Lc=a.Lc;this.id=ob++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get qe(){return I(this.mode)}get pe(){return 8192===(this.mode&61440)}};
function vb(a,b={}){if(!a)throw new F(44);b.qd??(b.qd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(m=>!!m);for(var d=lb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Pa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oa(e+"/"+a[f]);try{d=fb(d,a[f])}catch(m){if(44===m?.zc&&g&&b.se)return{path:e};throw m;}!d.Vc||g&&!b.qd||(d=d.Vc.root);if(40960===(d.mode&61440)&&(!g||b.pd)){if(!d.xc.readlink)throw new F(52);
d=d.xc.readlink(d);"/"===d.charAt(0)||(d=Pa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new F(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.Lc.Td,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}
function gb(a){var b=xb(a.parent.id,a.name);if(pb[b]===a)pb[b]=a.Wc;else for(b=pb[b];b;){if(b.Wc===a){b.Wc=a.Wc;break}b=b.Wc}}function fb(a,b){var c=I(a.mode)?(c=yb(a,"x"))?c:a.xc.lookup?0:2:54;if(c)throw new F(c);for(c=pb[xb(a.id,b)];c;c=c.Wc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.xc.lookup(a,b)}function eb(a,b,c,d){a=new ub(a,b,c,d);b=xb(a.parent.id,a.name);a.Wc=pb[b];return pb[b]=a}function I(a){return 16384===(a&61440)}
function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){if(!I(a.mode))return 54;try{return fb(a,b),20}catch(c){}return yb(a,"wx")}
function Bb(a,b,c){try{var d=fb(a,b)}catch(e){return e.zc}if(a=yb(a,"wx"))return a;if(c){if(!I(d.mode))return 54;if(d===d.parent||"/"===wb(d))return 10}else if(I(d.mode))return 31;return 0}function Cb(a){a=nb[a];if(!a)throw new F(8);return a}function Db(a,b=-1){a=Object.assign(new tb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!nb[b])break a;throw new F(33);}a.fd=b;return nb[b]=a}function Eb(a,b=-1){a=Db(a,b);a.wc?.Ne?.(a);return a}
function Fb(a,b){var c=null?.wc.Kc,d=c?null:a;c??=a.xc.Kc;if(!c)throw new F(63);c(d,b)}var db={open(a){a.wc=mb[a.node.rdev].wc;a.wc.open?.(a)},Ic(){throw new F(70);}};function $a(a,b){mb[a]={wc:b}}function Gb(a,b){var c="/"===b;if(c&&lb)throw new F(10);if(!c&&b){var d=vb(b,{qd:!1});b=d.path;d=d.node;if(d.Vc)throw new F(10);if(!I(d.mode))throw new F(54);}b={type:a,Ze:{},Td:b,re:[]};a=a.Lc(b);a.Lc=b;b.root=a;c?lb=a:d&&(d.Vc=b,d.Lc&&d.Lc.re.push(b))}
function Hb(a,b,c){var d=vb(a,{parent:!0}).node;a=Qa(a);if(!a)throw new F(28);if("."===a||".."===a)throw new F(20);var e=Ab(d,a);if(e)throw new F(e);if(!d.xc.gd)throw new F(63);return d.xc.gd(d,a,b,c)}function Ib(a,b=438){return Hb(a,b&4095|32768,0)}function J(a){return Hb(a,16895,0)}function Jb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Hb(a,b|8192,c)}
function Kb(a,b){if(!Ta(a))throw new F(44);var c=vb(b,{parent:!0}).node;if(!c)throw new F(44);b=Qa(b);var d=Ab(c,b);if(d)throw new F(d);if(!c.xc.symlink)throw new F(63);c.xc.symlink(c,b,a)}function Lb(a){var b=vb(a,{parent:!0}).node;a=Qa(a);var c=fb(b,a),d=Bb(b,a,!0);if(d)throw new F(d);if(!b.xc.rmdir)throw new F(63);if(c.Vc)throw new F(10);b.xc.rmdir(b,a);gb(c)}
function Mb(a){var b=vb(a,{parent:!0}).node;if(!b)throw new F(44);a=Qa(a);var c=fb(b,a),d=Bb(b,a,!1);if(d)throw new F(d);if(!b.xc.unlink)throw new F(63);if(c.Vc)throw new F(10);b.xc.unlink(b,a);gb(c)}function Nb(a,b){a="string"==typeof a?vb(a,{pd:!0}).node:a;Fb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Me:void 0})}
function Ob(a,b,c=438){if(""===a)throw new F(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=vb(a,{pd:!(b&131072),se:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new F(20);}else{if(e)throw new F(31);d=Hb(a,c|511,0);f=!0}if(!d)throw new F(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!I(d.mode))throw new F(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:I(d.mode)&&("r"!==zb(b)||b&576)?31:yb(d,zb(b)):44))throw new F(e);if(b&512&&!f){e=d;e="string"==typeof e?vb(e,{pd:!0}).node:e;if(I(e.mode))throw new F(31);if(32768!==(e.mode&61440))throw new F(28);var g=yb(e,"w");if(g)throw new F(g);Fb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Db({node:d,path:wb(d),flags:b,seekable:!0,position:0,wc:d.wc,ve:[],error:!1});e.wc.open&&e.wc.open(e);f&&Nb(d,c&511);!h.logReadFiles||b&1||a in sb||(sb[a]=1);return e}
function Pb(a){if(null===a.fd)throw new F(8);a.sd&&(a.sd=null);try{a.wc.close&&a.wc.close(a)}catch(b){throw b;}finally{nb[a.fd]=null}a.fd=null}function Qb(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.wc.Ic)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.wc.Ic(a,b,c);a.ve=[]}
function Rb(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(I(a.node.mode))throw new F(31);if(!a.wc.write)throw new F(28);a.seekable&&a.flags&1024&&Qb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F(70);b=a.wc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Sb(a,b){a="string"==typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oa(a+"/"+c);try{J(d)}catch(e){if(20!=e.zc)throw e;}a=d}}return d}function Tb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);return Ib(a,hb(c,d))}
function Ub(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:wb(a),g=b?Oa(a+"/"+b):a);a=hb(d,e);g=Ib(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Nb(g,a|146);b=Ob(g,577);Rb(b,c,0,c.length,0,f);Pb(b);Nb(g,a)}}
function Vb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);b=hb(!!c,!!d);Vb.Rd??(Vb.Rd=64);var e=Vb.Rd++<<8|0;$a(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,m,n){for(var l=0,q=0;q<n;q++){try{var u=c()}catch(x){throw new F(29);}if(void 0===u&&0===l)throw new F(6);if(null===u||void 0===u)break;l++;g[m+q]=u}l&&(f.node.atime=Date.now());return l},write(f,g,m,n){for(var l=0;l<n;l++)try{d(g[m+l])}catch(q){throw new F(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return l}});
return Jb(a,b,e)}function Wb(a){if(!(a.pe||a.qe||a.link||a.vc))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.vc=ka(a.url)}catch(b){throw new F(29);}}
function Xb(a,b,c,d,e){class f{Hd=!1;Dc=[];Fd=void 0;fe=0;ee=0;get(l){if(!(l>this.length-1||0>l)){var q=l%this.chunkSize;return this.Fd(l/this.chunkSize|0)[q]}}ge(l){this.Fd=l}Id(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||z("Couldn't load "+c+". Status: "+l.status);var q=Number(l.getResponseHeader("Content-length")),u,x=(u=l.getResponseHeader("Accept-Ranges"))&&"bytes"===u;l=(u=l.getResponseHeader("Content-Encoding"))&&"gzip"===u;var C=
1048576;x||(C=q);var D=this;D.ge(O=>{var H=O*C,A=(O+1)*C-1;A=Math.min(A,q-1);if("undefined"==typeof D.Dc[O]){var T=D.Dc;H>A&&z("invalid range ("+H+", "+A+") or no bytes requested!");A>q-1&&z("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);q!==C&&N.setRequestHeader("Range","bytes="+H+"-"+A);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);200<=N.status&&300>N.status||304===N.status||z("Couldn't load "+
c+". Status: "+N.status);H=void 0!==N.response?new Uint8Array(N.response||[]):Xa(N.responseText||"");T[O]=H}"undefined"==typeof D.Dc[O]&&z("doXHR failed!");return D.Dc[O]});if(l||!q)C=q=1,C=q=this.Fd(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.fe=q;this.ee=C;this.Hd=!0}get length(){this.Hd||this.Id();return this.fe}get chunkSize(){this.Hd||this.Id();return this.ee}}if(globalThis.XMLHttpRequest){ba||z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var m=void 0}else m=c,g=void 0;var n=Tb(a,b,d,e);g?n.vc=g:m&&(n.vc=null,n.url=m);Object.defineProperties(n,{yc:{get:function(){return this.vc.length}}});a={};for(const [l,q]of Object.entries(n.wc))a[l]=(...u)=>{Wb(n);return q(...u)};a.read=(l,q,u,x,C)=>{Wb(n);l=l.node.vc;if(C>=l.length)q=0;else{x=Math.min(l.length-C,x);if(l.slice)for(var D=0;D<x;D++)q[u+D]=l[C+D];else for(D=0;D<x;D++)q[u+D]=l.get(C+D);q=x}return q};a.wd=()=>{Wb(n);z();throw new F(48);};n.wc=a;return n}var K={};
function Yb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Cb(a).path;if(0==b.length)throw new F(44);return a+"/"+b}
var La=void 0,Zb=0,$b={},ac=a=>{a instanceof za||"unwind"==a||fa(1,a)},bc=a=>{pa=a;Ia||0<Zb||(h.onExit?.(a),oa=!0);fa(a,new za(a))},cc=()=>{if(!(Ia||0<Zb))try{var a=pa;pa=a;bc(a)}catch(b){ac(b)}},dc=a=>{if(!oa)try{a(),cc()}catch(b){ac(b)}},ec=[],oc=(a,b)=>{fc=a;gc=b;if(hc)if(ic||=!0,0==a)jc=function(){setTimeout(kc,Math.max(0,lc+b-performance.now())|0)};else if(1==a)jc=function(){mc(kc)};else if(2==a){if(!nc)if(globalThis.setImmediate)nc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===
d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);nc=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}jc=function(){nc(kc)}}},xc=(a,b,c,d,e)=>{function f(){return g<pc?(cc(),!1):!0}hc=a;qc=d;var g=pc;ic=!1;kc=function(){if(!oa)if(0<rc.length){var m=rc.shift();m.Se(m.ye);if(sc){var n=sc,l=0==n%1?n-1:Math.floor(n);sc=m.Ge?l:(8*n+(l+.5))/9}h.setStatus&&(m=h.statusMessage||
"Please wait...",n=sc??0,l=tc.Oe??0,n?n<l?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(kc,0)}else if(f())if(uc=uc+1|0,1==fc&&1<gc&&0!=uc%gc)jc();else{0==fc&&(lc=performance.now());a:if(!oa){for(m of vc)if(!1===m())break a;dc(a);for(n of wc)n()}f()&&jc()}};e||(0<b?oc(0,1E3/b):oc(1,1),jc());if(c)throw"unwind";},ic=!1,jc=null,pc=0,hc=null,qc=0,fc=0,gc=0,uc=0,rc=[],vc=[],wc=[];function yc(){jc=null;pc++}var zc=0;
function mc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===zc)zc=b+1E3/60;else for(;b+2>=zc;)zc+=1E3/60;setTimeout(a,Math.max(zc-b,0))}}var tc={},lc,kc,nc,sc,Ac=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?B(a):a;return Ac[a]||globalThis.document?.querySelector(a)},Bc=a=>0>Ac.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Cc(a){var b=M.Bc[a];b.target.removeEventListener(b.Ac,b.Od,b.Fc);M.Bc.splice(a,1)}
function Dc(){if(navigator.userActivation?navigator.userActivation.isActive:M.td&&M.he.md){var a=M.Oc;M.Oc=[];for(var b of a)b.Ad(...b.Jd)}}function P(a){if(!a.target)return-4;if(a.Cc)a.Od=function(c){++M.td;M.he=a;Dc();a.Hc(c);Dc();--M.td},a.target.addEventListener(a.Ac,a.Od,a.Fc),M.Bc.push(a);else for(var b=0;b<M.Bc.length;++b)M.Bc[b].target==a.target&&M.Bc[b].Ac==a.Ac&&Cc(b--);return 0}function Ec(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={ze:0,Te:0,ud:0,hd:0,Gd:0,Cd:0,od:0,Ke:0,$e:0,Je:0,rd:0,yd:0,kf:0,Bd:0,bf(){for(;M.Bc.length;)Cc(M.Bc.length-1);M.Oc=[]},td:0,Oc:[],Ie(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var m in f)if(f[m]!=g[m])return!1;return!0}for(var e of M.Oc)if(e.Ad==a&&d(e.Jd,c))return;M.Oc.push({Ad:a,Wd:b,Jd:c});M.Oc.sort((f,g)=>f.Wd<g.Wd)},df(a){M.Oc=M.Oc.filter(b=>b.Ad!=a)},Bc:[],cf:(a,b)=>{for(var c=0;c<M.Bc.length;++c)M.Bc[c].target!=a||b&&b!=M.Bc[c].Ac||Cc(c--)},ef(a){let b=!1;for(let c=0;c<
M.Bc.length;++c){const d=M.Bc[c];d.target===a.target&&d.Ec===a.Ec&&d.Cc===a.Cc&&d.Gc===a.Gc&&(Cc(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Fc=(a,b,c,d,e,f)=>{M.od||(M.od=Q(256));a={target:L(a),Ac:f,Ec:e,Gc:b,Cc:d,Hc:g=>{var m=g.target.id?g.target.id:"",n=M.od;E(Ec(g.target),r,n+0,128);E(m,r,n+128,128);R.get(d)(e,n,b)&&g.preventDefault()},Fc:c};return P(a)},Gc=(a,b,c,d,e)=>{M.rd||(M.rd=Q(276));return P({target:a,Ac:e,Ec:19,Gc:b,
Cc:d,Hc:f=>{var g=M.rd,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!m;p[g]=n;p[g+1]=M.fullscreenEnabled();var l=n?m:M.ue,q=l?.id||"";E(Ec(l),r,g+2,128);E(q,r,g+130,128);t[g+260>>2]=l?l.clientWidth:0;t[g+264>>2]=l?l.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(M.ue=m);R.get(d)(19,g,b)&&f.preventDefault()},Fc:c})},Hc=(a,b,c,d,e,f)=>{M.ud||(M.ud=Q(160));
a={target:L(a),Ac:f,Ec:e,Gc:b,Cc:d,Hc:g=>{var m=M.ud;y[m>>3]=g.timeStamp;var n=m>>2;t[n+2]=g.location;p[m+12]=g.ctrlKey;p[m+13]=g.shiftKey;p[m+14]=g.altKey;p[m+15]=g.metaKey;p[m+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;E(g.key||"",r,m+32,32);E(g.code||"",r,m+64,32);E(g.char||"",r,m+96,32);E(g.locale||"",r,m+128,32);R.get(d)(e,m,b)&&g.preventDefault()},Fc:c};return P(a)},Ic=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;
p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Bc(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Jc=(a,b,c,d,e,f)=>{M.hd||(M.hd=Q(64));a=L(a);return P({target:a,md:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ac:f,Ec:e,Gc:b,Cc:d,Hc:g=>{Ic(M.hd,g,a);R.get(d)(e,M.hd,b)&&g.preventDefault()},Fc:c})},Kc=(a,b,c,d)=>{M.yd||(M.yd=Q(257));return P({target:a,Ac:"pointerlockchange",Ec:20,
Gc:b,Cc:d,Hc:e=>{var f=M.yd,g=document.pointerLockElement;p[f]=!!g;var m=g?.id||"";E(Ec(g),r,f+1,128);E(m,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},Fc:c})},Lc=(a,b,c,d)=>P({target:a,Ac:"pointerlockerror",Ec:38,Gc:b,Cc:d,Hc:e=>{R.get(d)(38,0,b)&&e.preventDefault()},Fc:c}),Mc=(a,b,c,d)=>{M.Cd||(M.Cd=Q(36));a=L(a);return P({target:a,Ac:"resize",Ec:10,Gc:b,Cc:d,Hc:e=>{if(e.target==a){var f=document.body;if(f){var g=M.Cd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;
t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},Fc:c})},Nc=(a,b,c,d,e,f)=>{M.Bd||(M.Bd=Q(1552));a=L(a);return P({target:a,md:"touchstart"==f||"touchend"==f,Ac:f,Ec:e,Gc:b,Cc:d,Hc:g=>{var m={},n=g.touches;for(var l of n)l.Qd=l.Vd=0,m[l.identifier]=l;for(var q of g.changedTouches)q.Qd=1,m[q.identifier]=q;for(var u of g.targetTouches)m[u.identifier].Vd=1;n=M.Bd;y[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;
p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;l=n+16;q=Bc(a);u=0;for(let x of Object.values(m))if(m=l>>2,t[m]=x.identifier,t[m+1]=x.screenX,t[m+2]=x.screenY,t[m+3]=x.clientX,t[m+4]=x.clientY,t[m+5]=x.pageX,t[m+6]=x.pageY,p[l+28]=x.Qd,p[l+29]=x.Vd,t[m+8]=x.clientX-(q.left|0),t[m+9]=x.clientY-(q.top|0),l+=48,31<++u)break;t[n+8>>2]=u;R.get(d)(e,n,b)&&g.preventDefault()},Fc:c})},S,Oc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Pc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Qc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Rc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Sc=1,U=[],V=[],Tc=[],Uc=[],Vc=[],W=[],Wc=[],Xc=[],Yc=[],Zc=[1,1,2,2,4,4,4,2,3,4,8],$c={},ad=4,bd=0,cd=a=>{for(var b=Sc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Sc++;return b},dd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&cd(d);f?(f.name=g,d[g]=f):X||=1282;t[b+4*e>>2]=g}},ed=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Y.Xc[a];if(b)return b;b=S.getParameter(34965);Y.Xc[a]=S.createBuffer();S.bindBuffer(34963,Y.Xc[a]);S.bufferData(34963,
1<<a,35048);S.bindBuffer(34963,b);return Y.Xc[a]},gd=a=>{fd=!1;for(var b=0;b<Y.vd;++b){var c=Y.Rc[b];if(c.Sc&&c.enabled){fd=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*Zc[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=Y.Yc[e];var g=Y.Qc[e];Y.Qc[e]=Y.Qc[e]+1&63;var m=f[g];m?e=m:(m=S.getParameter(34964),f[g]=S.createBuffer(),S.bindBuffer(34962,f[g]),S.bufferData(34962,1<<e,35048),S.bindBuffer(34962,m),e=f[g]);S.bindBuffer(34962,e);S.bufferSubData(34962,0,r.subarray(c.$c,c.$c+d));c.Ed.call(S,b,c.size,
c.type,c.xd,c.stride,0)}}},jd=(a,b)=>{a.Dc||(a.Dc=a.getContext,a.getContext=function(d,e){e=a.Dc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Sd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?hd(c,b):0},hd=(a,b)=>{var c=cd(Xc),d={handle:c,attributes:b,version:b.Sd,kd:a};a.canvas&&(a.canvas.we=d);Xc[c]=d;if("undefined"==typeof b.Nd||b.Nd)if((a=d)||(a=Y),!a.ke){a.ke=!0;b=a.kd;b.Ye=b.getExtension("WEBGL_multi_draw");b.Qe=b.getExtension("EXT_polygon_offset_clamp");
b.Pe=b.getExtension("EXT_clip_control");b.lf=b.getExtension("WEBGL_polygon_mode");Oc(b);Pc(b);Qc(b);b.Le=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.We=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Md=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Md)b.Md=b.getExtension("EXT_disjoint_timer_query");for(var e of Rc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.vd=d.kd.getParameter(34921);
d.Rc=[];for(e=0;e<d.vd;e++)d.Rc[e]={enabled:!1,Sc:!1,size:0,type:0,xd:0,stride:0,$c:0,Ed:null};d.Qc=[];d.jd=[];d.Qc.length=d.jd.length=22;d.Yc=[];d.ad=[];d.Yc.length=d.ad.length=22;d.Xc=[];d.Xc.length=22;for(e=0;21>=e;++e){d.Xc[e]=null;d.Qc[e]=d.jd[e]=0;d.Yc[e]=[];d.ad[e]=[];a=d.Yc[e];b=d.ad[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},X,Y,fd,kd=(a,b,c,d,e,f)=>{a={target:L(a),Ac:f,Ec:e,Gc:b,Cc:d,Hc:g=>{R.get(d)(e,0,b)&&g.preventDefault()},Fc:c};P(a)},ld=(a,b,c,d)=>{M.Gd||
(M.Gd=Q(96));return P({target:a,md:!0,Ac:"wheel",Ec:9,Gc:b,Cc:d,Hc:e=>{var f=M.Gd;Ic(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},Fc:c})},md=["default","low-power","high-performance"],nd={},pd=()=>{if(!od){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in nd)void 0===nd[b]?delete a[b]:
a[b]=nd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);od=c}return od},od,qd=[],rd=()=>{var a=Rc(S);return a=a.concat(a.map(b=>"GL_"+b))},sd=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){X||=1282;return}c=rd().length;break;case 33307:case 33308:if(2>Y.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)t[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){X||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}t[b>>2]=c}else X||=1281},td=a=>{var b=Wa(a)+1,c=Q(b);c&&E(a,r,c,b);return c},ud=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),vd=a=>{a-=5120;return 0==a?p:1==a?r:2==a?qa:4==a?t:6==a?w:5==a||28922==a||28520==a||30779==a||30782==
a?v:ra},Z=a=>{var b=S.ie;if(b){var c=b.bd[a];"number"==typeof c&&(b.bd[a]=c=S.getUniformLocation(b,b.ce[a]+(0<c?`[${c}]`:"")));return c}X||=1282},wd=[],xd=[],zd=a=>{var b=Wa(a)+1,c=yd(b);E(a,r,c,b);return c},Cd=a=>{var b=Ad();a();Bd(b)},Dd=(a,b,c,d)=>{var e={string:l=>{var q=0;null!==l&&void 0!==l&&0!==l&&(q=zd(l));return q},array:l=>{var q=yd(l.length);p.set(l,q);return q}};a=h["_"+a];var f=[],g=0;if(d)for(var m=0;m<d.length;m++){var n=e[c[m]];n?(0===g&&(g=Ad()),f[m]=n(d[m])):f[m]=d[m]}c=a(...f);
return c=function(l){0!==g&&Bd(g);return"string"===b?B(l):"boolean"===b?!!l:l}(c)};pb=Array(4096);Gb(G,"/");J("/tmp");J("/home");J("/home/web_user");(function(){J("/dev");$a(259,{read:()=>0,write:(d,e,f,g)=>g,Ic:()=>0});Jb("/dev/null",259);Za(1280,bb);Za(1536,cb);Jb("/dev/tty",1280);Jb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Sa(a),b=a.byteLength);return a[--b]};Vb("/dev","random",c);Vb("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Gb({Lc(){var b=eb(a,"fd",16895,73);b.wc={Ic:G.wc.Ic};b.xc={lookup(c,d){c=+d;var e=Cb(c);c={parent:null,Lc:{Td:"fake"},xc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(nb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=mc;h.pauseMainLoop=yc;h.resumeMainLoop=function(){pc++;var a=fc,b=gc,c=hc;hc=null;xc(c,0,!1,qc,!0);oc(a,b);jc()};
h.preMainLoop&&vc.push(h.preMainLoop);h.postMainLoop&&wc.push(h.postMainLoop);var Ed=()=>{if(Y){var a=Y.Yc;Y.Yc=Y.ad;Y.ad=a;a=Y.Qc;Y.Qc=Y.jd;Y.jd=a;for(a=0;21>=a;++a)Y.Qc[a]=0}};"undefined"!=typeof tc&&vc.push(Ed);for(let a=0;32>a;++a)qd.push(Array(a));for(var Fd=new Float32Array(288),Gd=0;288>=Gd;++Gd)wd[Gd]=Fd.subarray(0,Gd);var Hd=new Int32Array(288);for(Gd=0;288>=Gd;++Gd)xd[Gd]=Hd.subarray(0,Gd);h.noExitRuntime&&(Ia=h.noExitRuntime);h.preloadPlugins&&(jb=h.preloadPlugins);h.print&&(ma=h.print);
h.printErr&&(k=h.printErr);h.wasmBinary&&(na=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=Ha;h.removeRunDependency=Ga;h.ccall=Dd;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Dd(a,b,c,f,d)};h.UTF8ToString=B;h.stringToNewUTF8=td;
h.FS_preloadFile=async(a,b,c,d,e,f,g,m)=>{var n=b?Ta(Oa(a+"/"+b)):a,l=`cp ${n}`;Ha(l);try{var q=c;"string"==typeof c&&(q=await ib(c));q=await kb(q,n);m?.();f||Ub(a,b,q,d,e,g)}finally{Ga(l)}};h.FS_unlink=(...a)=>Mb(...a);h.FS_createPath=(...a)=>Sb(...a);h.FS_createDevice=(...a)=>Vb(...a);h.FS_createDataFile=(...a)=>Ub(...a);h.FS_createLazyFile=(...a)=>Xb(...a);
var Id={360403:(a,b)=>{console.log(B(a,b))},360442:(a,b)=>{console.warn(B(a,b))},360482:(a,b)=>{console.error(B(a,b))},360523:()=>performance.now()},Jd,Kd,Ld,Md,Nd,Q,Od,Pd,Bd,yd,Ad,ua,R,Qd={vb:(a,b)=>{var c=Error().stack.toString(),d=c.split("\n");c="";var e=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),f=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of d){d=f.exec(g);if(5==d?.length)d=d[1];else if(d=e.exec(g),4<=d?.length)d=d[1];else{c+=g+"\n";continue}if("_emscripten_log"==d||"_emscripten_get_callstack"==
d)c=""}c=c.replace(/\s+$/,"");c=c.split("\n");for(e=0;e<c.length&&0===R.get(a)(0,b);e++);},d:(a,b,c,d)=>z(`Assertion failed: ${B(a)}, at: `+[b?B(b):"unknown filename",c,d?B(d):"unknown function"]),mb:(a,b)=>R.get(a)(b),ja:function(a,b,c){La=c;try{var d=Cb(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;nb[e];)e++;return Eb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==
typeof K||"ErrnoError"!==f.name)throw f;return-f.zc}},rb:function(a,b,c){La=c;try{var d=Cb(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Mc.me){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Mc.ne)for(e=
Ma(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ma();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ma();if(!d.wc.le)throw new F(59);return d.wc.le(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Mc.oe&&(f=[24,80],e=Ma(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.zc}},pb:function(a,b,c,d){try{b=
B(b);b=Yb(a,b);switch(c&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}Hb(b,c,d);return 0}catch(e){if("undefined"==typeof K||"ErrnoError"!==e.name)throw e;return-e.zc}},ia:function(a,b,c,d){La=d;try{b=B(b);b=Yb(a,b);var e=d?Ma():0;return Ob(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.zc}},kb:function(a){try{return a=B(a),Lb(a),0}catch(b){if("undefined"==typeof K||"ErrnoError"!==b.name)throw b;return-b.zc}},lb:function(a,
b,c){try{b=B(b);b=Yb(a,b);if(c)if(512===c)Lb(b);else return-28;else Mb(b);return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.zc}},sb:()=>z(""),ob:()=>{Ia=!1;Zb=0},jb:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=qa[e+4>>1],g=32,m=nb[t[e>>2]];m&&(m.wc.te?g=m.wc.te(m,-1):g=5);(g&=f|24)&&c++;qa[e+6>>1]=g}return c}catch(n){if("undefined"==typeof K||"ErrnoError"!==n.name)throw n;return-n.zc}},hb:(a,b)=>{$b[a]&&(clearTimeout($b[a].id),delete $b[a]);if(!b)return 0;
var c=setTimeout(()=>{delete $b[a];dc(()=>Pd(a,performance.now()))},b);$b[a]={id:c,jf:b};return 0},B:(a,b,c)=>{ec.length=0;for(var d;d=r[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;ec.push(112==d?v[c>>2]:106==d?sa[c>>3]:105==d?t[c>>2]:y[c>>3]);c+=e?8:4}return Id[a](...ec)},Ob:()=>{yc();hc=null},V:()=>globalThis.devicePixelRatio??1,va:(a,b,c)=>{a=L(a);if(!a)return-4;a=Bc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},ra:()=>performance.now(),Pb:()=>performance.now(),cb:(a,b)=>{function c(d){R.get(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},ib:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Y:(a,b,c,d)=>Fc(a,b,c,d,12,"blur"),S:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},Z:(a,b,c,d)=>Fc(a,b,c,d,13,"focus"),X:(a,
b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;Gc(a,b,c,d,"webkitfullscreenchange");return Gc(a,b,c,d,"fullscreenchange")},ma:(a,b,c,d)=>Hc(a,b,c,d,2,"keydown"),fa:(a,b,c,d)=>Hc(a,b,c,d,1,"keypress"),ka:(a,b,c,d)=>Hc(a,b,c,d,3,"keyup"),db:(a,b,c)=>{a=R.get(a);xc(a,b,c)},K:(a,b,c,d)=>Jc(a,b,c,d,5,"mousedown"),sa:(a,b,c,d)=>Jc(a,b,c,d,33,"mouseenter"),pa:(a,b,c,d)=>Jc(a,b,c,d,34,"mouseleave"),ua:(a,b,c,d)=>Jc(a,b,c,d,8,"mousemove"),G:(a,b,c,d)=>Jc(a,b,c,d,6,"mouseup"),$:(a,b,c,d)=>
document.body?.requestPointerLock?(a=L(a))?Kc(a,b,c,d):-4:-1,_:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Lc(a,b,c,d):-4:-1,ba:(a,b,c,d)=>Mc(a,b,c,d),aa:(a,b,c,d)=>Nc(a,b,c,d,25,"touchcancel"),ca:(a,b,c,d)=>Nc(a,b,c,d,23,"touchend"),da:(a,b,c,d)=>Nc(a,b,c,d,24,"touchmove"),ea:(a,b,c,d)=>Nc(a,b,c,d,22,"touchstart"),W:(a,b,c,d)=>{kd(a,b,c,d,31,"webglcontextlost");return 0},U:(a,b,c,d)=>{kd(a,b,c,d,32,"webglcontextrestored");return 0},na:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?ld(a,
b,c,d):-1:-4,Ta:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+5],powerPreference:md[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],Sd:t[c+4],Xe:t[c+5],Nd:p[b+24],je:p[b+25],af:t[c+7],ff:p[b+32]};a=L(a);return!a||b.je?0:jd(a,b)},Ma:a=>{Y=Xc[a];h.ctx=S=Y?.kd;return!a||S?0:-5},tb:(a,b)=>{var c=0,d=0,e;for(e of pd()){var f=b+c;v[a+d>>2]=f;c+=E(e,r,f,Infinity)+1;d+=4}return 0},ub:(a,b)=>{var c=pd();v[a>>2]=
c.length;a=0;for(var d of c)a+=Wa(d)+1;v[b>>2]=a;return 0},wb:a=>{pa=a;bc(a)},x:function(a){try{var b=Cb(a);Pb(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.zc}},ha:function(a,b,c,d){try{a:{var e=Cb(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var l=e,q=m,u=n,x=f,C=p;if(0>u||0>x)throw new F(28);if(null===l.fd)throw new F(8);if(1===(l.flags&2097155))throw new F(8);if(I(l.node.mode))throw new F(31);if(!l.wc.read)throw new F(28);var D="undefined"!=
typeof x;if(!D)x=l.position;else if(!l.seekable)throw new F(70);var O=l.wc.read(l,C,q,u,x);D||(l.position+=O);var H=O;if(0>H){var A=-1;break a}b+=H;if(H<n)break;"undefined"!=typeof f&&(f+=H)}A=b}v[d>>2]=A;return 0}catch(T){if("undefined"==typeof K||"ErrnoError"!==T.name)throw T;return T.zc}},qb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Cb(a);Qb(e,b,c);sa[d>>3]=BigInt(e.position);e.sd&&0===b&&0===c&&(e.sd=null);return 0}catch(f){if("undefined"==
typeof K||"ErrnoError"!==f.name)throw f;return f.zc}},ga:function(a,b,c,d){try{a:{var e=Cb(a);a=b;for(var f,g=b=0;g<c;g++){var m=v[a>>2],n=v[a+4>>2];a+=8;var l=Rb(e,p,m,n,f);if(0>l){var q=-1;break a}b+=l;if(l<n)break;"undefined"!=typeof f&&(f+=l)}q=b}v[d>>2]=q;return 0}catch(u){if("undefined"==typeof K||"ErrnoError"!==u.name)throw u;return u.zc}},z:a=>S.activeTexture(a),u:(a,b)=>{S.attachShader(V[a],W[b])},b:(a,b)=>{if(b&&!U[b]){var c=S.createBuffer();c.name=b;U[b]=c}34962==a?S.Tc=b:34963==a&&(S.Zc=
b);35051==a?S.Ld=b:35052==a&&(S.Uc=b);S.bindBuffer(a,U[b])},oa:(a,b,c)=>{S.bindBufferBase(a,b,U[c])},Aa:(a,b,c,d,e)=>{S.bindBufferRange(a,b,U[c],d,e)},h:(a,b)=>{S.bindFramebuffer(a,Tc[b])},Ha:(a,b)=>{S.bindRenderbuffer(a,Uc[b])},y:(a,b)=>{S.bindSampler(a,Yc[b])},i:(a,b)=>{S.bindTexture(a,Vc[b])},T:a=>{S.bindVertexArray(Wc[a]);a=S.getParameter(34965);S.Zc=a?a.name|0:0},E:(a,b,c,d)=>S.blendColor(a,b,c,d),F:(a,b)=>S.blendEquationSeparate(a,b),H:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),Rb:(a,b,c,d,e,f,
g,m,n,l)=>S.blitFramebuffer(a,b,c,d,e,f,g,m,n,l),Sa:(a,b,c,d)=>{2<=Y.version?c&&b?S.bufferData(a,r,d,c,b):S.bufferData(a,b,d):S.bufferData(a,c?r.subarray(c,c+b):b,d)},v:(a,b,c,d)=>{2<=Y.version?c&&S.bufferSubData(a,b,r,d,c):S.bufferSubData(a,b,r.subarray(d,d+c))},zb:a=>S.checkFramebufferStatus(a),Ea:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),J:(a,b,c)=>{S.clearBufferfv(a,b,w,c>>2)},Da:(a,b,c)=>{S.clearBufferiv(a,b,t,c>>2)},l:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Bb:a=>{S.compileShader(W[a])},Hb:(a,b,
c,d,e,f,g,m,n)=>{2<=Y.version?S.Uc||!m?S.compressedTexSubImage2D(a,b,c,d,e,f,g,m,n):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r,n,m):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r.subarray(n,n+m))},Fb:(a,b,c,d,e,f,g,m,n,l,q)=>{S.Uc?S.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,l,q):S.compressedTexSubImage3D(a,b,c,d,e,f,g,m,n,r,q,l)},Na:()=>{var a=cd(V),b=S.createProgram();b.name=a;b.ed=b.cd=b.dd=0;b.Dd=1;V[a]=b;return a},Db:a=>{var b=cd(W);W[b]=S.createShader(a);return b},D:a=>S.cullFace(a),Ib:(a,b)=>{for(var c=
0;c<a;c++){var d=t[b+4*c>>2],e=U[d];e&&(S.deleteBuffer(e),e.name=0,U[d]=null,d==S.Tc&&(S.Tc=0),d==S.Zc&&(S.Zc=0),d==S.Ld&&(S.Ld=0),d==S.Uc&&(S.Uc=0))}},w:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Tc[d];e&&(S.deleteFramebuffer(e),e.name=0,Tc[d]=null)}},o:a=>{if(a){var b=V[a];b?(S.deleteProgram(b),b.name=0,V[a]=null):X||=1281}},Q:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Uc[d];e&&(S.deleteRenderbuffer(e),e.name=0,Uc[d]=null)}},Wa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Yc[d];
e&&(S.deleteSampler(e),e.name=0,Yc[d]=null)}},m:a=>{if(a){var b=W[a];b?(S.deleteShader(b),W[a]=null):X||=1281}},k:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Vc[d];e&&(S.deleteTexture(e),e.name=0,Vc[d]=null)}},Va:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];S.deleteVertexArray(Wc[d]);Wc[d]=null}},q:a=>S.depthFunc(a),r:a=>{S.depthMask(!!a)},c:a=>S.disable(a),ta:a=>{Y.Rc[a].enabled=!1;S.disableVertexAttribArray(a)},Tb:(a,b,c)=>{gd(b+c);S.drawArrays(a,b,c);fd&&S.bindBuffer(34962,U[S.Tc])},Ub:(a,
b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},L:(a,b)=>{for(var c=qd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];S.drawBuffers(c)},Vb:(a,b,c,d)=>{var e=0;if(!S.Zc){var f=1*Zc[c-5120]*b;var g=ed(f);S.bindBuffer(34963,g);S.bufferSubData(34963,0,r.subarray(d,d+f));if(0<b)for(g=0;g<Y.vd;++g)if(f=Y.Rc[g],f.Sc&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:X||=1282;return}e=(new e(r.buffer,d,b)).reduce((m,n)=>Math.max(m,n))+1;break}d=0}gd(e);S.drawElements(a,
b,c,d);fd&&S.bindBuffer(34962,U[S.Tc]);S.Zc||S.bindBuffer(34963,null)},Wb:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},g:a=>S.enable(a),wa:a=>{Y.Rc[a].enabled=!0;S.enableVertexAttribArray(a)},j:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Uc[d])},e:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,Vc[d],e)},t:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,Vc[c],d,e)},C:a=>S.frontFace(a),Ua:(a,b)=>{dd(a,b,"createBuffer",U)},R:(a,b)=>{dd(a,b,"createFramebuffer",Tc)},Ia:(a,b)=>{dd(a,b,"createRenderbuffer",
Uc)},Oa:(a,b)=>{dd(a,b,"createSampler",Yc)},Ra:(a,b)=>{dd(a,b,"createTexture",Vc)},Ya:(a,b)=>{dd(a,b,"createVertexArray",Wc)},Ja:(a,b)=>S.getAttribLocation(V[a],B(b)),a:(a,b)=>sd(a,b),La:(a,b,c,d)=>{a=S.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,r,d,b):0;c&&(t[c>>2]=b)},N:(a,b,c)=>{if(c)if(a>=Sc)X||=1281;else if(a=V[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.ed){var d=S.getProgramParameter(a,35718);for(b=
0;b<d;++b)a.ed=Math.max(a.ed,S.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.ed}else if(35722==b){if(!a.cd)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.cd=Math.max(a.cd,S.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.cd}else if(35381==b){if(!a.dd)for(d=S.getProgramParameter(a,35382),b=0;b<d;++b)a.dd=Math.max(a.dd,S.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.dd}else t[c>>2]=S.getProgramParameter(a,b);else X||=1281},Ab:(a,b,c,d)=>{a=S.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");
b=0<b&&d?E(a,r,d,b):0;c&&(t[c>>2]=b)},la:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(W[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=S.getShaderParameter(W[a],b):X||=1281},Za:(a,b)=>{if(2>Y.version)return X||=1282,0;var c=$c[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=rd().map(td),c=$c[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},M:(a,b)=>{b=B(b);if(a=V[a]){var c=
a,d=c.bd,e=c.de,f;if(!d){c.bd=d={};c.ce={};var g=S.getProgramParameter(c,35718);for(f=0;f<g;++f){var m=S.getActiveUniform(c,f);var n=m.name;m=m.size;var l=ud(n);l=0<l?n.slice(0,l):n;var q=c.Dd;c.Dd+=m;e[l]=[m,q];for(n=0;n<m;++n)d[q]=n,c.ce[q++]=l}}c=a.bd;d=0;e=b;f=ud(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.de[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else X||=1281;return-1},Qb:(a,b,c)=>{for(var d=qd[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];S.invalidateFramebuffer(a,
d)},O:a=>{a=V[a];S.linkProgram(a);a.bd=0;a.de={}},Xa:(a,b)=>{3317==a?ad=b:3314==a&&(bd=b);S.pixelStorei(a,b)},I:(a,b)=>S.polygonOffset(a,b),Sb:a=>S.readBuffer(a),Ga:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),P:(a,b,c)=>{S.samplerParameterf(Yc[a],b,c)},f:(a,b,c)=>{S.samplerParameteri(Yc[a],b,c)},s:(a,b,c,d)=>S.scissor(a,b,c,d),Cb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=B(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);S.shaderSource(W[a],e)},Kb:(a,b,c)=>S.stencilFunc(a,b,c),Ca:(a,b,c,d)=>S.stencilFuncSeparate(a,
b,c,d),n:a=>S.stencilMask(a),Jb:(a,b,c)=>S.stencilOp(a,b,c),Ba:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Qa:(a,b,c,d,e)=>S.texStorage2D(a,b,c,d,e),Pa:(a,b,c,d,e,f)=>S.texStorage3D(a,b,c,d,e,f),Gb:(a,b,c,d,e,f,g,m,n)=>{if(2<=Y.version){if(S.Uc){S.texSubImage2D(a,b,c,d,e,f,g,m,n);return}if(n){var l=vd(m);S.texSubImage2D(a,b,c,d,e,f,g,m,l,n>>>31-Math.clz32(l.BYTES_PER_ELEMENT));return}}if(n){l=vd(m);var q=f*((bd||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*l.BYTES_PER_ELEMENT+
ad-1&-ad);n=l.subarray(n>>>31-Math.clz32(l.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(l.BYTES_PER_ELEMENT))}else n=null;S.texSubImage2D(a,b,c,d,e,f,g,m,n)},Eb:(a,b,c,d,e,f,g,m,n,l,q)=>{if(S.Uc)S.texSubImage3D(a,b,c,d,e,f,g,m,n,l,q);else if(q){var u=vd(l);S.texSubImage3D(a,b,c,d,e,f,g,m,n,l,u,q>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,f,g,m,n,l,null)},dc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1fv(Z(a),w,c>>2,b);else{if(288>=b)for(var d=wd[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=
w.subarray(c>>2,c+4*b>>2);S.uniform1fv(Z(a),d)}},Ka:(a,b)=>{S.uniform1i(Z(a),b)},$b:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1iv(Z(a),t,c>>2,b);else{if(288>=b)for(var d=xd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);S.uniform1iv(Z(a),d)}},cc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2fv(Z(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=wd[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);S.uniform2fv(Z(a),d)}},_b:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2iv(Z(a),
t,c>>2,2*b);else{if(144>=b){b*=2;for(var d=xd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+8*b>>2);S.uniform2iv(Z(a),d)}},bc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3fv(Z(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=wd[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);S.uniform3fv(Z(a),d)}},Zb:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3iv(Z(a),t,c>>2,3*b);else{if(96>=b){b*=3;for(var d=xd[b],e=0;e<b;e+=3)d[e]=
t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);S.uniform3iv(Z(a),d)}},ac:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4fv(Z(a),w,c>>2,4*b);else{if(72>=b){var d=wd[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);S.uniform4fv(Z(a),d)}},Yb:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4iv(Z(a),t,c>>2,4*b);else{if(72>=b){b*=4;for(var d=xd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+
(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);S.uniform4iv(Z(a),d)}},Xb:(a,b,c,d)=>{if(2<=Y.version)b&&S.uniformMatrix4fv(Z(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=wd[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=
w.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(Z(a),!!c,e)}},p:a=>{a=V[a];S.useProgram(a);S.ie=a},xa:(a,b)=>{S.vertexAttribDivisor(a,b)},ya:(a,b,c,d,e)=>{var f=Y.Rc[a];S.Tc?(f.Sc=!1,S.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.xd=!1,f.stride=d,f.$c=e,f.Sc=!0,f.Ed=function(g,m,n,l,q,u){this.vertexAttribIPointer(g,m,n,q,u)})},za:(a,b,c,d,e,f)=>{var g=Y.Rc[a];S.Tc?(g.Sc=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.xd=d,g.stride=e,g.$c=f,g.Sc=!0,g.Ed=function(m,n,l,q,u,x){this.vertexAttribPointer(m,
n,l,q,u,x)})},Fa:(a,b,c,d)=>S.viewport(a,b,c,d),yb:function(){try{var a=globalThis.localStorage;if(!a)return 0;var b=a.getItem("ScopeBee.PlayerPrefs");return null===b?0:td(b)}catch(c){return 0}},xb:function(a,b){try{var c=globalThis.localStorage;c&&c.setItem("ScopeBee.PlayerPrefs",B(a,b))}catch(d){}},nb:bc,gb:function(){h.Xd=a=>{0!=Kd()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Xd)},fb:function(){h.be=a=>{const b=a.clipboardData.getData("text");Cd(()=>{const c=
zd(b);Jd(c)})};window.addEventListener("paste",h.be)},eb:function(){h.gf=[];h.Yd=b=>{b.stopPropagation();b.preventDefault()};h.Zd=b=>{b.stopPropagation();b.preventDefault()};h.$d=b=>{b.stopPropagation();b.preventDefault()};h.ae=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.hf=c;Ld(c.length);for(let e=0;e<c.length;e++)Cd(()=>{const f=zd(c[e].name);Md(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Nd(b.clientX,b.clientY,d)};const a=
h.Nc;a.addEventListener("dragenter",h.Yd,!1);a.addEventListener("dragleave",h.Zd,!1);a.addEventListener("dragover",h.$d,!1);a.addEventListener("drop",h.ae,!1)},$a:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},ab:function(a){h.ld&&(URL.revokeObjectURL(h.ld[a].Ae),h.ld[a]=null)},ec:function(a,b){0!==b&&(document.title=B(b));a=B(a);void 0!==h.canvas&&("object"===typeof h.canvas?Ac[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
h.Nc=L(a);h.Nc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Nc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Nb:function(){window.removeEventListener("beforeunload",h.Xd)},Mb:function(){window.removeEventListener("paste",h.be)},Lb:function(){const a=h.Nc;a.removeEventListener("dragenter",h.Yd);a.removeEventListener("dragleave",h.Zd);a.removeEventListener("dragover",h.$d);a.removeEventListener("drop",h.ae)},A:function(){h.Nc&&
h.Nc.requestPointerLock&&h.Nc.requestPointerLock()},bb:function(a,b,c){if(h.Nc){if(0===b)a="none";else if(0!=c)a=h.ld[a].He;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Nc.style.cursor=a}},_a:function(a,b,c){const d=document.createElement("canvas");
d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(r.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},qa:function(a,b){b=B(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};
function Rd(a=[]){var b=Od;a.unshift(ea);var c=a.length,d=yd(4*(c+1)),e=d,f;for(f of a)v[e>>2]=zd(f),e+=4;v[e>>2]=0;try{var g=b(c,d);pa=g;bc(g)}catch(m){ac(m)}}
function Sd(a=da){function b(){h.calledRun=!0;if(!oa){if(!h.noFSInit&&!qb){var c,d;qb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Vb("/dev","stdin",c):Kb("/dev/tty","/dev/stdin");d?Vb("/dev","stdout",null,d):Kb("/dev/tty","/dev/stdout");e?Vb("/dev","stderr",null,e):Kb("/dev/tty1","/dev/stderr");Ob("/dev/stdin",0);Ob("/dev/stdout",1);Ob("/dev/stderr",1)}Td.gc();rb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Rd(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ba.push(e)}Aa(Ba)}}if(0<Ea)Fa=Sd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<Ea?Fa=Sd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Td;
(async function(){function a(c){c=Td=c.exports;Jd=h.__sapp_emsc_onpaste=c.hc;Kd=h.__sapp_html5_get_ask_leave_site=c.jc;Ld=h.__sapp_emsc_begin_drop=c.kc;Md=h.__sapp_emsc_drop=c.lc;Nd=h.__sapp_emsc_end_drop=c.mc;h.__sapp_emsc_invoke_fetch_cb=c.nc;h.__sapp_emsc_set_fullscreen_flag=c.oc;Q=c.pc;Od=h._main=c.qc;Pd=c.rc;Bd=c.sc;yd=c.tc;Ad=c.uc;ua=c.fc;R=c.ic;ta();Ga("wasm-instantiate");return Td}Ha("wasm-instantiate");var b={a:Qd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,
e))})});va??=h.locateFile?h.locateFile("index.wasm",ia):ia+"index.wasm";return a((await ya(b)).instance)})();Sd();
