var h;h||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;h.expectedDataFileDownloads||(h.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;if(!("undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a)){var b=globalThis.process&&globalThis.process.versions&&globalThis.process.versions.node&&"renderer"!=globalThis.process.type;(async function(c){async function d(m,q){if(b){var u=require("fs").readFileSync(m);return(new Uint8Array(u)).buffer}h.dataFileDownloads||(h.dataFileDownloads={});try{var x=await fetch(m)}catch(C){throw Error(`Network Error: ${m}`,
{e:C});}if(!x.ok)throw Error(`${x.status}: ${x.url}`);u=[];q=Number(x.headers.get("Content-Length")||q);let E=0;h.setStatus&&h.setStatus("Downloading data...");for(x=x.body.getReader();;){var {done:F,value:O}=await x.read();if(F)break;u.push(O);E+=O.length;h.dataFileDownloads[m]={loaded:E,total:q};let C=0,T=0;for(var I of Object.values(h.dataFileDownloads))C+=I.loaded,T+=I.total;h.setStatus&&h.setStatus(`Downloading data... (${C}/${T})`)}m=new Uint8Array(u.map(C=>C.length).reduce((C,T)=>C+T,0));I=
0;for(const C of u)m.set(C,I),I+=C.length;return m.buffer}async function e(m){m.FS_createPath("/","Assets",!0,!0);m.FS_createPath("/Assets","Animations",!0,!0);m.FS_createPath("/Assets/Animations","Bird",!0,!0);m.FS_createPath("/Assets","Prefab",!0,!0);m.FS_createPath("/Assets","Scenes",!0,!0);m.FS_createPath("/Assets","Sprites",!0,!0);m.FS_createPath("/","assets",!0,!0);m.FS_createPath("/assets","builtin",!0,!0);for(var q of c.files)m.addRunDependency(`fp ${q.filename}`);m.addRunDependency("datafile_build/web/FlappyBIrd/index.data");
m.preloadResults||(m.preloadResults={});m.preloadResults["build/web/FlappyBIrd/index.data"]={$e:!1};n||=await l;(async function(u){if(!u)throw Error("Loading data file failed.");if(u.constructor.name!==ArrayBuffer.name)throw Error("bad input to processPackageData "+u.constructor.name);u=new Uint8Array(u);for(var x of c.files){var E=x.filename;m.FS_createDataFile(E,null,u.subarray(x.start,x.end),!0,!0,!0);m.removeRunDependency(`fp ${E}`)}m.removeRunDependency("datafile_build/web/FlappyBIrd/index.data")})(n)}
"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=c.remote_package_size,l,n=h.getPreloadedPackage&&h.getPreloadedPackage(f,g);n||(l=d(f,g));h.calledRun?e(h):(h.preRun||(h.preRun=[]),h.preRun.push(e))})({files:[{filename:"/Assets/Animations/Bird/BirdAnimator.coanimator",
start:0,end:667},{filename:"/Assets/Animations/Bird/Idle.coanim",start:667,end:9799},{filename:"/Assets/Animations/Bird/Jump.coanim",start:9799,end:11181},{filename:"/Assets/Prefab/Pipe.sbb",start:11181,end:12951},{filename:"/Assets/Prefab/TestPrefab.sbb",start:12951,end:14476},{filename:"/Assets/Scenes/FlappyBird.sbb",start:14476,end:24329},{filename:"/Assets/Sprites/0.ktx2",start:24329,end:25349},{filename:"/Assets/Sprites/1.ktx2",start:25349,end:26448},{filename:"/Assets/Sprites/2.ktx2",start:26448,
end:27532},{filename:"/Assets/Sprites/3.ktx2",start:27532,end:28597},{filename:"/Assets/Sprites/4.ktx2",start:28597,end:29862},{filename:"/Assets/Sprites/5.ktx2",start:29862,end:30945},{filename:"/Assets/Sprites/6.ktx2",start:30945,end:32025},{filename:"/Assets/Sprites/7.ktx2",start:32025,end:33324},{filename:"/Assets/Sprites/8.ktx2",start:33324,end:34399},{filename:"/Assets/Sprites/9.ktx2",start:34399,end:35476},{filename:"/Assets/Sprites/background-day.ktx2",start:35476,end:97208},{filename:"/Assets/Sprites/base.ktx2",
start:97208,end:100467},{filename:"/Assets/Sprites/gameover.ktx2",start:100467,end:108318},{filename:"/Assets/Sprites/message.ktx2",start:108318,end:134408},{filename:"/Assets/Sprites/pipe-green.ktx2",start:134408,end:149798},{filename:"/Assets/Sprites/redbird-downflap.ktx2",start:149798,end:152606},{filename:"/Assets/Sprites/redbird-midflap.ktx2",start:152606,end:155434},{filename:"/Assets/Sprites/redbird-upflap.ktx2",start:155434,end:158288},{filename:"/Assets/_texsizes.txt",start:158288,end:159162},
{filename:"/Assets/project.json",start:159162,end:161598},{filename:"/assets/builtin/Background.ktx2",start:161598,end:161978},{filename:"/assets/builtin/Checkmark.ktx2",start:161978,end:162479},{filename:"/assets/builtin/Knob.ktx2",start:162479,end:163009},{filename:"/assets/builtin/UIMask.ktx2",start:163009,end:163434},{filename:"/assets/builtin/UISprite.ktx2",start:163434,end:163859}],remote_package_size:163859})}})();var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;
"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),k=console.error.bind(console),na,oa=!1,pa,la=a=>a.startsWith("file://"),p,r,qa,ra,t,v,w,y,sa;
function ta(){var a=ua.buffer;p=new Int8Array(a);qa=new Int16Array(a);r=new Uint8Array(a);ra=new Uint16Array(a);t=new Int32Array(a);v=new Uint32Array(a);w=new Float32Array(a);y=new Float64Array(a);sa=new BigInt64Array(a);new BigUint64Array(a)}function z(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);oa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var va;
async function wa(a){if(!na)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==va&&na)a=new Uint8Array(na);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ya(a){var b=va;if(!na&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ea=0,Fa=null,Ga=()=>{Ea--;h.monitorRunDependencies?.(Ea);if(0==Ea&&Fa){var a=Fa;Fa=null;a()}},Ha=()=>{Ea++;h.monitorRunDependencies?.(Ea)},Ia=!0,Ja=new TextDecoder,Ka=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},A=(a,b,c)=>a?Ja.decode(r.subarray(a,Ka(r,a,b,c))):"",Ma=()=>{var a=t[+La>>2];La+=4;return a},Na=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):
".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Na(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Qa=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ra=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>
crypto.getRandomValues(b)},Sa=a=>{(Sa=Ra())(a)},Ta=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Na(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ua=a=>{var b=Ka(a,0);return Ja.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Va=[],Wa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=
d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},B=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Xa=a=>{var b=Array(Wa(a)+1);a=B(a,b,0,b.length);
b.length=a;return b},Ya=[];function Za(a,b){Ya[a]={input:[],output:[],Wc:b};$a(a,ab)}
var ab={open(a){var b=Ya[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Wc.fsync(a.tty)},fsync(a){a.tty.Wc.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Wc.$d)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Wc.$d(a.tty)}catch(l){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Wc.Kd)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Wc.Kd(a.tty,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},bb={$d(){a:{if(!Va.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Va=Xa(a)}a=Va.shift()}return a},Kd(a,b){null===b||10===b?(ma(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&
(ma(Ua(a.output)),a.output=[])},ve(){return{Me:25856,Oe:5,Le:191,Ne:35387,Ke:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},we(){return 0},xe(){return[24,80]}},cb={Kd(a,b){null===b||10===b?(k(Ua(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(k(Ua(a.output)),a.output=[])}},G={Sc:null,Vc(){return G.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);G.Sc||(G.Sc={dir:{node:{Uc:G.Gc.Uc,
Tc:G.Gc.Tc,lookup:G.Gc.lookup,rd:G.Gc.rd,rename:G.Gc.rename,unlink:G.Gc.unlink,rmdir:G.Gc.rmdir,readdir:G.Gc.readdir,symlink:G.Gc.symlink},stream:{Rc:G.Fc.Rc}},file:{node:{Uc:G.Gc.Uc,Tc:G.Gc.Tc},stream:{Rc:G.Fc.Rc,read:G.Fc.read,write:G.Fc.write,Hd:G.Fc.Hd,ee:G.Fc.ee}},link:{node:{Uc:G.Gc.Uc,Tc:G.Gc.Tc,readlink:G.Gc.readlink},stream:{}},Vd:{node:{Uc:G.Gc.Uc,Tc:G.Gc.Tc},stream:db}});c=eb(a,b,c,d);H(c.mode)?(c.Gc=G.Sc.dir.node,c.Fc=G.Sc.dir.stream,c.Ec={}):32768===(c.mode&61440)?(c.Gc=G.Sc.file.node,
c.Fc=G.Sc.file.stream,c.Hc=0,c.Ec=null):40960===(c.mode&61440)?(c.Gc=G.Sc.link.node,c.Fc=G.Sc.link.stream):8192===(c.mode&61440)&&(c.Gc=G.Sc.Vd.node,c.Fc=G.Sc.Vd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.Ec[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},cf(a){return a.Ec?a.Ec.subarray?a.Ec.subarray(0,a.Hc):new Uint8Array(a.Ec):new Uint8Array(0)},Gc:{Uc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===
(a.mode&61440)?b.size=a.Hc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},Tc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Hc!=b&&(0==b?(a.Ec=null,a.Hc=0):(c=a.Ec,a.Ec=new Uint8Array(b),c&&a.Ec.set(c.subarray(0,Math.min(b,a.Hc))),a.Hc=b)))},lookup(){G.zd||(G.zd=new D(44),G.zd.stack="<generic error, no stack>");
throw G.zd;},rd(a,b,c,d){return G.createNode(a,b,c,d)},rename(a,b,c){try{var d=fb(b,c)}catch(f){}if(d){if(H(a.mode))for(var e in d.Ec)throw new D(55);gb(d)}delete a.parent.Ec[a.name];b.Ec[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.Ec[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=fb(a,b),d;for(d in c.Ec)throw new D(55);delete a.Ec[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.Ec)]},symlink(a,b,c){a=G.createNode(a,b,41471,
0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},Fc:{read(a,b,c,d,e){var f=a.node.Ec;if(e>=a.node.Hc)return 0;a=Math.min(a.node.Hc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===p.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.Ec||a.Ec.subarray)){if(f)return a.Ec=b.subarray(c,c+d),a.Hc=d;if(0===a.Hc&&0===e)return a.Ec=b.slice(c,c+d),a.Hc=d;
if(e+d<=a.Hc)return a.Ec.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.Ec?a.Ec.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.Ec,a.Ec=new Uint8Array(f),0<a.Hc&&a.Ec.set(g.subarray(0,a.Hc),0));if(a.Ec.subarray&&b.subarray)a.Ec.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Ec[e+f]=b[c+f];a.Hc=Math.max(a.Hc,e+d);return d},Rc(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Hc);if(0>b)throw new D(28);return b},Hd(a,b,c,d,e){if(32768!==(a.node.mode&
61440))throw new D(43);a=a.node.Ec;if(e&2||!a||a.buffer!==p.buffer){d=!0;z();e=void 0;if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);p.set(a,e)}}else d=!1,e=a.byteOffset;return{kd:e,Ge:d}},ee(a,b,c,d){G.Fc.write(a,b,0,d,c,!1);return 0}}},hb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ib=async a=>{a=await ja(a);return new Uint8Array(a)},jb=[],kb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.df();for(var c of jb)if(c.canHandle(b))return c.handle(a,
b);return a},lb=null,mb={},nb=[],ob=1,pb=null,qb=!1,rb=!0,sb={},D=class{name="ErrnoError";constructor(a){this.Ic=a}},tb=class{Lc={};node=null;get flags(){return this.Lc.flags}set flags(a){this.Lc.flags=a}get position(){return this.Lc.position}set position(a){this.Lc.position=a}},ub=class{Gc={};Fc={};dd=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Vc=a.Vc;this.id=ob++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get ze(){return H(this.mode)}get ye(){return 8192===(this.mode&61440)}};
function vb(a,b={}){if(!a)throw new D(44);b.Bd??(b.Bd=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=lb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Pa(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oa(e+"/"+a[f]);try{d=fb(d,a[f])}catch(l){if(44===l?.Ic&&g&&b.Be)return{path:e};throw l;}!d.dd||g&&!b.Bd||(d=d.dd.root);if(40960===(d.mode&61440)&&(!g||b.nd)){if(!d.Gc.readlink)throw new D(52);
d=d.Gc.readlink(d);"/"===d.charAt(0)||(d=Pa(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function wb(a){for(var b;;){if(a===a.parent)return a=a.Vc.de,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function xb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%pb.length}
function gb(a){var b=xb(a.parent.id,a.name);if(pb[b]===a)pb[b]=a.ed;else for(b=pb[b];b;){if(b.ed===a){b.ed=a.ed;break}b=b.ed}}function fb(a,b){var c=H(a.mode)?(c=yb(a,"x"))?c:a.Gc.lookup?0:2:54;if(c)throw new D(c);for(c=pb[xb(a.id,b)];c;c=c.ed){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Gc.lookup(a,b)}function eb(a,b,c,d){a=new ub(a,b,c,d);b=xb(a.parent.id,a.name);a.ed=pb[b];return pb[b]=a}function H(a){return 16384===(a&61440)}
function zb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function yb(a,b){if(rb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Ab(a,b){if(!H(a.mode))return 54;try{return fb(a,b),20}catch(c){}return yb(a,"wx")}
function Bb(a,b,c){try{var d=fb(a,b)}catch(e){return e.Ic}if(a=yb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(d===d.parent||"/"===wb(d))return 10}else if(H(d.mode))return 31;return 0}function Cb(a){if(!a)throw new D(63);return a}function Db(a){a=nb[a];if(!a)throw new D(8);return a}function Eb(a,b=-1){a=Object.assign(new tb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!nb[b])break a;throw new D(33);}a.fd=b;return nb[b]=a}function Fb(a,b=-1){a=Eb(a,b);a.Fc?.We?.(a);return a}
function Gb(a,b){var c=null?.Fc.Tc,d=c?null:a;c??=a.Gc.Tc;Cb(c);c(d,b)}var db={open(a){a.Fc=mb[a.node.rdev].Fc;a.Fc.open?.(a)},Rc(){throw new D(70);}};function $a(a,b){mb[a]={Fc:b}}function Hb(a,b){var c="/"===b;if(c&&lb)throw new D(10);if(!c&&b){var d=vb(b,{Bd:!1});b=d.path;d=d.node;if(d.dd)throw new D(10);if(!H(d.mode))throw new D(54);}b={type:a,hf:{},de:b,Ae:[]};a=a.Vc(b);a.Vc=b;b.root=a;c?lb=a:d&&(d.dd=b,d.Vc&&d.Vc.Ae.push(b))}
function Ib(a,b,c){var d=vb(a,{parent:!0}).node;a=Qa(a);if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=Ab(d,a);if(e)throw new D(e);if(!d.Gc.rd)throw new D(63);return d.Gc.rd(d,a,b,c)}function Jb(a,b=438){return Ib(a,b&4095|32768,0)}function J(a){return Ib(a,16895,0)}function Kb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ib(a,b|8192,c)}
function Lb(a,b){if(!Ta(a))throw new D(44);var c=vb(b,{parent:!0}).node;if(!c)throw new D(44);b=Qa(b);var d=Ab(c,b);if(d)throw new D(d);if(!c.Gc.symlink)throw new D(63);c.Gc.symlink(c,b,a)}function Mb(a){var b=vb(a,{parent:!0}).node;a=Qa(a);var c=fb(b,a),d=Bb(b,a,!0);if(d)throw new D(d);if(!b.Gc.rmdir)throw new D(63);if(c.dd)throw new D(10);b.Gc.rmdir(b,a);gb(c)}
function Nb(a){var b=vb(a,{parent:!0}).node;if(!b)throw new D(44);a=Qa(a);var c=fb(b,a),d=Bb(b,a,!1);if(d)throw new D(d);if(!b.Gc.unlink)throw new D(63);if(c.dd)throw new D(10);b.Gc.unlink(b,a);gb(c)}function Ob(a,b){a="string"==typeof a?vb(a,{nd:!0}).node:a;Gb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),Ve:void 0})}
function Pb(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=vb(a,{nd:!(b&131072),Be:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Ib(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!H(d.mode))throw new D(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:H(d.mode)&&("r"!==zb(b)||b&576)?31:yb(d,zb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?vb(e,{nd:!0}).node:e;if(H(e.mode))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=yb(e,"w");if(g)throw new D(g);Gb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:d,path:wb(d),flags:b,seekable:!0,position:0,Fc:d.Fc,Ee:[],error:!1});e.Fc.open&&e.Fc.open(e);f&&Ob(d,c&511);!h.logReadFiles||b&1||a in sb||(sb[a]=1);return e}
function Qb(a){if(null===a.fd)throw new D(8);a.Dd&&(a.Dd=null);try{a.Fc.close&&a.Fc.close(a)}catch(b){throw b;}finally{nb[a.fd]=null}a.fd=null}function Rb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.Fc.Rc)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.Fc.Rc(a,b,c);a.Ee=[]}
function Sb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(H(a.node.mode))throw new D(31);if(!a.Fc.write)throw new D(28);a.seekable&&a.flags&1024&&Rb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.Fc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Tb(a,b){a="string"==typeof a?a:wb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oa(a+"/"+c);try{J(d)}catch(e){if(20!=e.Ic)throw e;}a=d}}return d}function Ub(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);return Jb(a,hb(c,d))}
function Vb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:wb(a),g=b?Oa(a+"/"+b):a);a=hb(d,e);g=Jb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ob(g,a|146);b=Pb(g,577);Sb(b,c,0,c.length,0,f);Qb(b);Ob(g,a)}}
function Wb(a,b,c,d){a=Oa(("string"==typeof a?a:wb(a))+"/"+b);b=hb(!!c,!!d);Wb.be??(Wb.be=64);var e=Wb.be++<<8|0;$a(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var m=0,q=0;q<n;q++){try{var u=c()}catch(x){throw new D(29);}if(void 0===u&&0===m)throw new D(6);if(null===u||void 0===u)break;m++;g[l+q]=u}m&&(f.node.atime=Date.now());return m},write(f,g,l,n){for(var m=0;m<n;m++)try{d(g[l+m])}catch(q){throw new D(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return m}});
return Kb(a,b,e)}function Xb(a){if(!(a.ye||a.ze||a.link||a.Ec))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.Ec=ka(a.url)}catch(b){throw new D(29);}}
function Yb(a,b,c,d,e){class f{wd=!1;Lc=[];ud=void 0;Sd=0;Rd=0;get(m){if(!(m>this.length-1||0>m)){var q=m%this.chunkSize;return this.ud(m/this.chunkSize|0)[q]}}pe(m){this.ud=m}Td(){var m=new XMLHttpRequest;m.open("HEAD",c,!1);m.send(null);200<=m.status&&300>m.status||304===m.status||z("Couldn't load "+c+". Status: "+m.status);var q=Number(m.getResponseHeader("Content-length")),u,x=(u=m.getResponseHeader("Accept-Ranges"))&&"bytes"===u;m=(u=m.getResponseHeader("Content-Encoding"))&&"gzip"===u;var E=
1048576;x||(E=q);var F=this;F.pe(O=>{var I=O*E,C=(O+1)*E-1;C=Math.min(C,q-1);if("undefined"==typeof F.Lc[O]){var T=F.Lc;I>C&&z("invalid range ("+I+", "+C+") or no bytes requested!");C>q-1&&z("only "+q+" bytes available! programmer error!");var N=new XMLHttpRequest;N.open("GET",c,!1);q!==E&&N.setRequestHeader("Range","bytes="+I+"-"+C);N.responseType="arraybuffer";N.overrideMimeType&&N.overrideMimeType("text/plain; charset=x-user-defined");N.send(null);200<=N.status&&300>N.status||304===N.status||z("Couldn't load "+
c+". Status: "+N.status);I=void 0!==N.response?new Uint8Array(N.response||[]):Xa(N.responseText||"");T[O]=I}"undefined"==typeof F.Lc[O]&&z("doXHR failed!");return F.Lc[O]});if(m||!q)E=q=1,E=q=this.ud(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.Sd=q;this.Rd=E;this.wd=!0}get length(){this.wd||this.Td();return this.Sd}get chunkSize(){this.wd||this.Td();return this.Rd}}if(globalThis.XMLHttpRequest){ba||z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var g=new f;var l=void 0}else l=c,g=void 0;var n=Ub(a,b,d,e);g?n.Ec=g:l&&(n.Ec=null,n.url=l);Object.defineProperties(n,{Hc:{get:function(){return this.Ec.length}}});a={};for(const [m,q]of Object.entries(n.Fc))a[m]=(...u)=>{Xb(n);return q(...u)};a.read=(m,q,u,x,E)=>{Xb(n);m=m.node.Ec;if(E>=m.length)q=0;else{x=Math.min(m.length-E,x);if(m.slice)for(var F=0;F<x;F++)q[u+F]=m[E+F];else for(F=0;F<x;F++)q[u+F]=m.get(E+F);q=x}return q};a.Hd=()=>{Xb(n);z();throw new D(48);};n.Fc=a;return n}var K={};
function Zb(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Db(a).path;if(0==b.length)throw new D(44);return a+"/"+b}
var La=void 0,$b=0,ac={},bc=a=>{a instanceof za||"unwind"==a||fa(1,a)},cc=a=>{pa=a;Ia||0<$b||(h.onExit?.(a),oa=!0);fa(a,new za(a))},dc=()=>{if(!(Ia||0<$b))try{var a=pa;pa=a;cc(a)}catch(b){bc(b)}},ec=a=>{if(!oa)try{a(),dc()}catch(b){bc(b)}},fc=[],gc=(a,b)=>{fc.length=0;for(var c;c=r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;fc.push(112==c?v[b>>2]:106==c?sa[b>>3]:105==c?t[b>>2]:y[b>>3]);b+=d?8:4}return fc},qc=(a,b)=>{hc=a;ic=b;if(jc)if(kc||=!0,0==a)lc=function(){setTimeout(mc,Math.max(0,nc+b-performance.now())|
0)};else if(1==a)lc=function(){oc(mc)};else if(2==a){if(!pc)if(globalThis.setImmediate)pc=setImmediate;else{var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);pc=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}lc=function(){pc(mc)}}},zc=(a,b,c,d,e)=>{function f(){return g<rc?(dc(),!1):!0}jc=a;sc=
d;var g=rc;kc=!1;mc=function(){if(!oa)if(0<tc.length){var l=tc.shift();l.af(l.He);if(uc){var n=uc,m=0==n%1?n-1:Math.floor(n);uc=l.Pe?m:(8*n+(m+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",n=uc??0,m=vc.Xe??0,n?n<m?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(mc,0)}else if(f())if(wc=wc+1|0,1==hc&&1<ic&&0!=wc%ic)lc();else{0==hc&&(nc=performance.now());a:if(!oa){for(l of xc)if(!1===l())break a;ec(a);for(n of yc)n()}f()&&lc()}};
e||(0<b?qc(0,1E3/b):qc(1,1),lc());if(c)throw"unwind";},kc=!1,lc=null,rc=0,jc=null,sc=0,hc=0,ic=0,wc=0,tc=[],xc=[],yc=[];function Ac(){lc=null;rc++}var Bc=0;function oc(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Bc)Bc=b+1E3/60;else for(;b+2>=Bc;)Bc+=1E3/60;setTimeout(a,Math.max(Bc-b,0))}}
var vc={},nc,mc,pc,uc,Cc=[0,globalThis.document??0,globalThis.window??0],L=a=>{a=2<a?A(a):a;return Cc[a]||globalThis.document?.querySelector(a)},Dc=a=>0>Cc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0};function Ec(a){var b=M.Kc[a];b.target.removeEventListener(b.Jc,b.Zd,b.Oc);M.Kc.splice(a,1)}function Fc(){if(navigator.userActivation?navigator.userActivation.isActive:M.Ed&&M.qe.yd){var a=M.Yc;M.Yc=[];for(var b of a)b.Ld(...b.Ud)}}
function P(a){if(!a.target)return-4;if(a.Mc)a.Zd=function(c){++M.Ed;M.qe=a;Fc();a.Qc(c);Fc();--M.Ed},a.target.addEventListener(a.Jc,a.Zd,a.Oc),M.Kc.push(a);else for(var b=0;b<M.Kc.length;++b)M.Kc[b].target==a.target&&M.Kc[b].Jc==a.Jc&&Ec(b--);return 0}function Gc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var M={Ie:0,bf:0,Fd:0,sd:0,Qd:0,Nd:0,Ad:0,Te:0,jf:0,Se:0,Cd:0,Jd:0,uf:0,Md:0,lf(){for(;M.Kc.length;)Ec(M.Kc.length-1);M.Yc=[]},Ed:0,Yc:[],Re(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of M.Yc)if(e.Ld==a&&d(e.Ud,c))return;M.Yc.push({Ld:a,ge:b,Ud:c});M.Yc.sort((f,g)=>f.ge<g.ge)},nf(a){M.Yc=M.Yc.filter(b=>b.Ld!=a)},Kc:[],mf:(a,b)=>{for(var c=0;c<M.Kc.length;++c)M.Kc[c].target!=a||b&&b!=M.Kc[c].Jc||Ec(c--)},pf(a){let b=!1;for(let c=0;c<
M.Kc.length;++c){const d=M.Kc[c];d.target===a.target&&d.Nc===a.Nc&&d.Mc===a.Mc&&d.Pc===a.Pc&&(Ec(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Hc=(a,b,c,d,e,f)=>{M.Ad||(M.Ad=Q(256));a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var l=g.target.id?g.target.id:"",n=M.Ad;B(Gc(g.target),r,n+0,128);B(l,r,n+128,128);R.get(d)(e,n,b)&&g.preventDefault()},Oc:c};return P(a)},Ic=(a,b,c,d,e)=>{M.Cd||(M.Cd=Q(276));return P({target:a,Jc:e,Nc:19,Pc:b,
Mc:d,Qc:f=>{var g=M.Cd,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;p[g]=n;p[g+1]=M.fullscreenEnabled();var m=n?l:M.De,q=m?.id||"";B(Gc(m),r,g+2,128);B(q,r,g+130,128);t[g+260>>2]=m?m.clientWidth:0;t[g+264>>2]=m?m.clientHeight:0;t[g+268>>2]=screen.width;t[g+272>>2]=screen.height;n&&(M.De=l);R.get(d)(19,g,b)&&f.preventDefault()},Oc:c})},Jc=(a,b,c,d,e,f)=>{M.Fd||(M.Fd=Q(160));
a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var l=M.Fd;y[l>>3]=g.timeStamp;var n=l>>2;t[n+2]=g.location;p[l+12]=g.ctrlKey;p[l+13]=g.shiftKey;p[l+14]=g.altKey;p[l+15]=g.metaKey;p[l+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;B(g.key||"",r,l+32,32);B(g.code||"",r,l+64,32);B(g.char||"",r,l+96,32);B(g.locale||"",r,l+128,32);R.get(d)(e,l,b)&&g.preventDefault()},Oc:c};return P(a)},Kc=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;
p[a+24]=b.ctrlKey;p[a+25]=b.shiftKey;p[a+26]=b.altKey;p[a+27]=b.metaKey;qa[2*d+14]=b.button;qa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;a=Dc(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Lc=(a,b,c,d,e,f)=>{M.sd||(M.sd=Q(64));a=L(a);return P({target:a,yd:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{Kc(M.sd,g,a);R.get(d)(e,M.sd,b)&&g.preventDefault()},Oc:c})},Mc=(a,b,c,d)=>{M.Jd||(M.Jd=Q(257));return P({target:a,Jc:"pointerlockchange",Nc:20,
Pc:b,Mc:d,Qc:e=>{var f=M.Jd,g=document.pointerLockElement;p[f]=!!g;var l=g?.id||"";B(Gc(g),r,f+1,128);B(l,r,f+129,128);R.get(d)(20,f,b)&&e.preventDefault()},Oc:c})},Nc=(a,b,c,d)=>P({target:a,Jc:"pointerlockerror",Nc:38,Pc:b,Mc:d,Qc:e=>{R.get(d)(38,0,b)&&e.preventDefault()},Oc:c}),Oc=(a,b,c,d)=>{M.Nd||(M.Nd=Q(36));a=L(a);return P({target:a,Jc:"resize",Nc:10,Pc:b,Mc:d,Qc:e=>{if(e.target==a){var f=document.body;if(f){var g=M.Nd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;
t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;R.get(d)(10,g,b)&&e.preventDefault()}}},Oc:c})},Pc=(a,b,c,d,e,f)=>{M.Md||(M.Md=Q(1552));a=L(a);return P({target:a,yd:"touchstart"==f||"touchend"==f,Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{var l={},n=g.touches;for(var m of n)m.ae=m.fe=0,l[m.identifier]=m;for(var q of g.changedTouches)q.ae=1,l[q.identifier]=q;for(var u of g.targetTouches)l[u.identifier].fe=1;n=M.Md;y[n>>3]=g.timeStamp;p[n+12]=g.ctrlKey;
p[n+13]=g.shiftKey;p[n+14]=g.altKey;p[n+15]=g.metaKey;m=n+16;q=Dc(a);u=0;for(let x of Object.values(l))if(l=m>>2,t[l]=x.identifier,t[l+1]=x.screenX,t[l+2]=x.screenY,t[l+3]=x.clientX,t[l+4]=x.clientY,t[l+5]=x.pageX,t[l+6]=x.pageY,p[m+28]=x.ae,p[m+29]=x.fe,t[l+8]=x.clientX-(q.left|0),t[l+9]=x.clientY-(q.top|0),m+=48,31<++u)break;t[n+8>>2]=u;R.get(d)(e,n,b)&&g.preventDefault()},Oc:c})},S,Qc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Rc=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Sc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Tc=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Uc=1,U=[],V=[],Vc=[],Wc=[],Xc=[],W=[],Yc=[],Zc=[],$c=[],ad=[1,1,2,2,4,4,4,2,3,4,8],bd={},cd=4,dd=0,ed=a=>{for(var b=Uc++,c=a.length;c<b;c++)a[c]=null;for(;a[b];)b=Uc++;return b},fd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&ed(d);f?(f.name=g,d[g]=f):X||=1282;t[b+4*e>>2]=g}},gd=a=>{a=32-Math.clz32(0===a?0:a-1);var b=Y.gd[a];if(b)return b;b=S.getParameter(34965);Y.gd[a]=S.createBuffer();S.bindBuffer(34963,Y.gd[a]);S.bufferData(34963,
1<<a,35048);S.bindBuffer(34963,b);return Y.gd[a]},jd=a=>{hd=!1;for(var b=0;b<Y.Gd;++b){var c=Y.$c[b];if(c.ad&&c.enabled){hd=!0;var d=c.size;var e=c.type,f=c.stride;d=0<f?a*f:d*ad[e-5120]*a;e=32-Math.clz32(0===d?0:d-1);f=Y.hd[e];var g=Y.Zc[e];Y.Zc[e]=Y.Zc[e]+1&63;var l=f[g];l?e=l:(l=S.getParameter(34964),f[g]=S.createBuffer(),S.bindBuffer(34962,f[g]),S.bufferData(34962,1<<e,35048),S.bindBuffer(34962,l),e=f[g]);S.bindBuffer(34962,e);S.bufferSubData(34962,0,r.subarray(c.kd,c.kd+d));c.Pd.call(S,b,c.size,
c.type,c.Id,c.stride,0)}}},ld=(a,b)=>{a.Lc||(a.Lc=a.getContext,a.getContext=function(d,e){e=a.Lc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ce?a.getContext("webgl2",b):a.getContext("webgl",b);return c?kd(c,b):0},kd=(a,b)=>{var c=ed(Zc),d={handle:c,attributes:b,version:b.ce,vd:a};a.canvas&&(a.canvas.Fe=d);Zc[c]=d;if("undefined"==typeof b.Yd||b.Yd)if((a=d)||(a=Y),!a.te){a.te=!0;b=a.vd;b.gf=b.getExtension("WEBGL_multi_draw");b.Ze=b.getExtension("EXT_polygon_offset_clamp");
b.Ye=b.getExtension("EXT_clip_control");b.vf=b.getExtension("WEBGL_polygon_mode");Qc(b);Rc(b);Sc(b);b.Ue=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ef=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Xd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Xd)b.Xd=b.getExtension("EXT_disjoint_timer_query");for(var e of Tc(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}d.Gd=d.vd.getParameter(34921);
d.$c=[];for(e=0;e<d.Gd;e++)d.$c[e]={enabled:!1,ad:!1,size:0,type:0,Id:0,stride:0,kd:0,Pd:null};d.Zc=[];d.td=[];d.Zc.length=d.td.length=22;d.hd=[];d.ld=[];d.hd.length=d.ld.length=22;d.gd=[];d.gd.length=22;for(e=0;21>=e;++e){d.gd[e]=null;d.Zc[e]=d.td[e]=0;d.hd[e]=[];d.ld[e]=[];a=d.hd[e];b=d.ld[e];a.length=b.length=64;for(var f=0;64>f;++f)a[f]=b[f]=null}return c},X,Y,hd,md=(a,b,c,d,e,f)=>{a={target:L(a),Jc:f,Nc:e,Pc:b,Mc:d,Qc:g=>{R.get(d)(e,0,b)&&g.preventDefault()},Oc:c};P(a)},nd=(a,b,c,d)=>{M.Qd||
(M.Qd=Q(96));return P({target:a,yd:!0,Jc:"wheel",Nc:9,Pc:b,Mc:d,Qc:e=>{var f=M.Qd;Kc(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>3]=e.deltaZ;t[f+88>>2]=e.deltaMode;R.get(d)(9,f,b)&&e.preventDefault()},Oc:c})},od=["default","low-power","high-performance"],pd={},rd=()=>{if(!qd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in pd)void 0===pd[b]?delete a[b]:
a[b]=pd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qd=c}return qd},qd,sd=[],td=()=>{var a=Tc(S);return a=a.concat(a.map(b=>"GL_"+b))},ud=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=S.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){X||=1282;return}c=td().length;break;case 33307:case 33308:if(2>Y.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=S.getParameter(a),typeof d){case "number":c=
d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)t[b+4*a>>2]=d[a];return}try{c=
d.name|0}catch(e){X||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;k(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}t[b>>2]=c}else X||=1281},vd=a=>{var b=Wa(a)+1,c=Q(b);c&&B(a,r,c,b);return c},wd=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),xd=a=>{a-=5120;return 0==a?p:1==a?r:2==a?qa:4==a?t:6==a?w:5==a||28922==a||28520==a||30779==a||30782==
a?v:ra},Z=a=>{var b=S.re;if(b){var c=b.md[a];"number"==typeof c&&(b.md[a]=c=S.getUniformLocation(b,b.ne[a]+(0<c?`[${c}]`:"")));return c}X||=1282},yd=[],zd=[],Bd=a=>{var b=Wa(a)+1,c=Ad(b);B(a,r,c,b);return c},Ed=a=>{var b=Cd();a();Dd(b)},Fd=(a,b,c,d)=>{var e={string:m=>{var q=0;null!==m&&void 0!==m&&0!==m&&(q=Bd(m));return q},array:m=>{var q=Ad(m.length);p.set(m,q);return q}};a=h["_"+a];var f=[],g=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(0===g&&(g=Cd()),f[l]=n(d[l])):f[l]=d[l]}c=a(...f);
return c=function(m){0!==g&&Dd(g);return"string"===b?A(m):"boolean"===b?!!m:m}(c)};pb=Array(4096);Hb(G,"/");J("/tmp");J("/home");J("/home/web_user");(function(){J("/dev");$a(259,{read:()=>0,write:(d,e,f,g)=>g,Rc:()=>0});Kb("/dev/null",259);Za(1280,bb);Za(1536,cb);Kb("/dev/tty",1280);Kb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Sa(a),b=a.byteLength);return a[--b]};Wb("/dev","random",c);Wb("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Hb({Vc(){var b=eb(a,"fd",16895,73);b.Fc={Rc:G.Fc.Rc};b.Gc={lookup(c,d){c=+d;var e=Db(c);c={parent:null,Vc:{de:"fake"},Gc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(nb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.requestAnimationFrame=oc;h.pauseMainLoop=Ac;h.resumeMainLoop=function(){rc++;var a=hc,b=ic,c=jc;jc=null;zc(c,0,!1,sc,!0);qc(a,b);lc()};
h.preMainLoop&&xc.push(h.preMainLoop);h.postMainLoop&&yc.push(h.postMainLoop);var Gd=()=>{if(Y){var a=Y.hd;Y.hd=Y.ld;Y.ld=a;a=Y.Zc;Y.Zc=Y.td;Y.td=a;for(a=0;21>=a;++a)Y.Zc[a]=0}};"undefined"!=typeof vc&&xc.push(Gd);for(let a=0;32>a;++a)sd.push(Array(a));for(var Hd=new Float32Array(288),Id=0;288>=Id;++Id)yd[Id]=Hd.subarray(0,Id);var Jd=new Int32Array(288);for(Id=0;288>=Id;++Id)zd[Id]=Jd.subarray(0,Id);h.noExitRuntime&&(Ia=h.noExitRuntime);h.preloadPlugins&&(jb=h.preloadPlugins);h.print&&(ma=h.print);
h.printErr&&(k=h.printErr);h.wasmBinary&&(na=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.addRunDependency=Ha;h.removeRunDependency=Ga;h.ccall=Fd;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>Fd(a,b,c,f,d)};h.UTF8ToString=A;h.stringToNewUTF8=vd;
h.FS_preloadFile=async(a,b,c,d,e,f,g,l)=>{var n=b?Ta(Oa(a+"/"+b)):a,m=`cp ${n}`;Ha(m);try{var q=c;"string"==typeof c&&(q=await ib(c));q=await kb(q,n);l?.();f||Vb(a,b,q,d,e,g)}finally{Ga(m)}};h.FS_unlink=(...a)=>Nb(...a);h.FS_createPath=(...a)=>Tb(...a);h.FS_createDevice=(...a)=>Wb(...a);h.FS_createDataFile=(...a)=>Vb(...a);h.FS_createLazyFile=(...a)=>Yb(...a);
var Kd={696585:(a,b)=>{console.log(A(a,b))},696624:(a,b)=>{console.warn(A(a,b))},696664:(a,b)=>{console.error(A(a,b))},696705:()=>performance.now(),696735:()=>{try{return(new URLSearchParams(location.search)).has("perf")?1:0}catch(a){return 0}},696836:(a,b)=>{try{var c=(new URLSearchParams(location.search)).get(A(a));if(null===c)return b;var d=parseInt(c,10);return isNaN(d)?b:d}catch(e){return b}}},Ld,Md,Nd,Od,Pd,Q,Qd,Rd,Dd,Ad,Cd,ua,R,Sd={zb:(a,b)=>{var c=Error().stack.toString(),d=c.split("\n");
c="";var e=RegExp("\\s*(.*?)@(.*?):([0-9]+):([0-9]+)"),f=RegExp("\\s*at (.*?) \\((.*):(.*):(.*)\\)"),g;for(g of d){d=f.exec(g);if(5==d?.length)d=d[1];else if(d=e.exec(g),4<=d?.length)d=d[1];else{c+=g+"\n";continue}if("_emscripten_log"==d||"_emscripten_get_callstack"==d)c=""}c=c.replace(/\s+$/,"");c=c.split("\n");for(e=0;e<c.length&&0===R.get(a)(0,b);e++);},c:(a,b,c,d)=>z(`Assertion failed: ${A(a)}, at: `+[b?A(b):"unknown filename",c,d?A(d):"unknown function"]),nb:(a,b)=>R.get(a)(b),fa:function(a,
b,c){La=c;try{var d=Db(a);switch(b){case 0:var e=Ma();if(0>e)break;for(;nb[e];)e++;return Fb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ma(),d.flags|=e,0;case 12:return e=Ma(),qa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Ic}},tb:function(a,b,c){La=c;try{var d=Db(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Wc.ve){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ma();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)p[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Wc.we)for(e=Ma(),a=[],f=0;32>f;f++)a.push(p[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=Ma();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=Ma();if(!d.Fc.ue)throw new D(59);return d.Fc.ue(d,b,e);case 21523:if(!d.tty)return-59;
d.tty.Wc.xe&&(f=[24,80],e=Ma(),qa[e>>1]=f[0],qa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.Ic}},qb:function(a,b,c,d){try{b=A(b);b=Zb(a,b);switch(c&61440){case 32768:case 8192:case 24576:case 4096:case 49152:break;default:return-28}Ib(b,c,d);return 0}catch(e){if("undefined"==typeof K||"ErrnoError"!==e.name)throw e;return-e.Ic}},ea:function(a,b,c,d){La=d;try{b=A(b);b=
Zb(a,b);var e=d?Ma():0;return Pb(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.Ic}},lb:function(a){try{return a=A(a),Mb(a),0}catch(b){if("undefined"==typeof K||"ErrnoError"!==b.name)throw b;return-b.Ic}},rb:function(a,b){try{a=A(a);var c=vb(a,{nd:!0}).node;var d=Cb(c.Gc.Uc)(c);v[b>>2]=d.dev;v[b+4>>2]=d.mode;v[b+8>>2]=d.nlink;v[b+12>>2]=d.uid;v[b+16>>2]=d.gid;v[b+20>>2]=d.rdev;sa[b+24>>3]=BigInt(d.size);t[b+32>>2]=4096;t[b+36>>2]=d.blocks;var e=d.atime.getTime(),
f=d.mtime.getTime(),g=d.ctime.getTime();sa[b+40>>3]=BigInt(Math.floor(e/1E3));v[b+48>>2]=e%1E3*1E6;sa[b+56>>3]=BigInt(Math.floor(f/1E3));v[b+64>>2]=f%1E3*1E6;sa[b+72>>3]=BigInt(Math.floor(g/1E3));v[b+80>>2]=g%1E3*1E6;sa[b+88>>3]=BigInt(d.ino);return 0}catch(l){if("undefined"==typeof K||"ErrnoError"!==l.name)throw l;return-l.Ic}},mb:function(a,b,c){try{b=A(b);b=Zb(a,b);if(c)if(512===c)Mb(b);else return-28;else Nb(b);return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.Ic}},
wb:()=>z(""),pb:()=>{Ia=!1;$b=0},kb:function(a,b){try{for(var c=0,d=0;d<b;d++){var e=a+8*d,f=qa[e+4>>1],g=32,l=nb[t[e>>2]];l&&(l.Fc.Ce?g=l.Fc.Ce(l,-1):g=5);(g&=f|24)&&c++;qa[e+6>>1]=g}return c}catch(n){if("undefined"==typeof K||"ErrnoError"!==n.name)throw n;return-n.Ic}},ib:(a,b)=>{ac[a]&&(clearTimeout(ac[a].id),delete ac[a]);if(!b)return 0;var c=setTimeout(()=>{delete ac[a];ec(()=>Rd(a,performance.now()))},b);ac[a]={id:c,tf:b};return 0},vb:function(a,b,c){if(!(0<=a&&3>=a))return 28;sa[c>>3]=BigInt(Math.round(1E6*
(0===a?Date.now():performance.now())));return 0},ac:(a,b,c)=>{b=gc(b,c);return Kd[a](...b)},n:(a,b,c)=>{b=gc(b,c);return Kd[a](...b)},_b:()=>{Ac();jc=null},ub:()=>Date.now(),S:()=>globalThis.devicePixelRatio??1,ta:(a,b,c)=>{a=L(a);if(!a)return-4;a=Dc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},o:()=>performance.now(),$b:()=>performance.now(),db:(a,b)=>{function c(d){R.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},jb:a=>{var b=r.length;a>>>=0;if(2147483648<a)return!1;for(var c=
1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},V:(a,b,c,d)=>Hc(a,b,c,d,12,"blur"),O:(a,b,c)=>{a=L(a);if(!a)return-4;a.width=b;a.height=c;return 0},W:(a,b,c,d)=>Hc(a,b,c,d,13,"focus"),U:(a,b,c,d)=>{if(!M.fullscreenEnabled())return-1;a=L(a);if(!a)return-4;Ic(a,b,c,d,"webkitfullscreenchange");return Ic(a,b,c,d,"fullscreenchange")},
ka:(a,b,c,d)=>Jc(a,b,c,d,2,"keydown"),ga:(a,b,c,d)=>Jc(a,b,c,d,1,"keypress"),ha:(a,b,c,d)=>Jc(a,b,c,d,3,"keyup"),eb:(a,b,c)=>{a=R.get(a);zc(a,b,c)},F:(a,b,c,d)=>Lc(a,b,c,d,5,"mousedown"),ra:(a,b,c,d)=>Lc(a,b,c,d,33,"mouseenter"),pa:(a,b,c,d)=>Lc(a,b,c,d,34,"mouseleave"),sa:(a,b,c,d)=>Lc(a,b,c,d,8,"mousemove"),y:(a,b,c,d)=>Lc(a,b,c,d,6,"mouseup"),Y:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Mc(a,b,c,d):-4:-1,X:(a,b,c,d)=>document.body?.requestPointerLock?(a=L(a))?Nc(a,b,c,d):-4:-1,_:(a,
b,c,d)=>Oc(a,b,c,d),Z:(a,b,c,d)=>Pc(a,b,c,d,25,"touchcancel"),$:(a,b,c,d)=>Pc(a,b,c,d,23,"touchend"),aa:(a,b,c,d)=>Pc(a,b,c,d,24,"touchmove"),ba:(a,b,c,d)=>Pc(a,b,c,d,22,"touchstart"),T:(a,b,c,d)=>{md(a,b,c,d,31,"webglcontextlost");return 0},R:(a,b,c,d)=>{md(a,b,c,d,32,"webglcontextrestored");return 0},ma:(a,b,c,d)=>(a=L(a))?"undefined"!=typeof a.onwheel?nd(a,b,c,d):-1:-4,Ra:(a,b)=>{var c=b>>2;b={alpha:!!p[b+0],depth:!!p[b+1],stencil:!!p[b+2],antialias:!!p[b+3],premultipliedAlpha:!!p[b+4],preserveDrawingBuffer:!!p[b+
5],powerPreference:od[t[c+2]],failIfMajorPerformanceCaveat:!!p[b+12],ce:t[c+4],ff:t[c+5],Yd:p[b+24],se:p[b+25],kf:t[c+7],qf:p[b+32]};a=L(a);return!a||b.se?0:ld(a,b)},Na:a=>{Y=Zc[a];h.ctx=S=Y?.vd;return!a||S?0:-5},xb:(a,b)=>{var c=0,d=0,e;for(e of rd()){var f=b+c;v[a+d>>2]=f;c+=B(e,r,f,Infinity)+1;d+=4}return 0},yb:(a,b)=>{var c=rd();v[a>>2]=c.length;a=0;for(var d of c)a+=Wa(d)+1;v[b>>2]=a;return 0},Ab:a=>{pa=a;cc(a)},v:function(a){try{var b=Db(a);Qb(b);return 0}catch(c){if("undefined"==typeof K||
"ErrnoError"!==c.name)throw c;return c.Ic}},da:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var l=v[a>>2],n=v[a+4>>2];a+=8;var m=e,q=l,u=n,x=f,E=p;if(0>u||0>x)throw new D(28);if(null===m.fd)throw new D(8);if(1===(m.flags&2097155))throw new D(8);if(H(m.node.mode))throw new D(31);if(!m.Fc.read)throw new D(28);var F="undefined"!=typeof x;if(!F)x=m.position;else if(!m.seekable)throw new D(70);var O=m.Fc.read(m,E,q,u,x);F||(m.position+=O);var I=O;if(0>I){var C=-1;break a}b+=I;if(I<
n)break;"undefined"!=typeof f&&(f+=I)}C=b}v[d>>2]=C;return 0}catch(T){if("undefined"==typeof K||"ErrnoError"!==T.name)throw T;return T.Ic}},sb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=Db(a);Rb(e,b,c);sa[d>>3]=BigInt(e.position);e.Dd&&0===b&&0===c&&(e.Dd=null);return 0}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return f.Ic}},ca:function(a,b,c,d){try{a:{var e=Db(a);a=b;for(var f,g=b=0;g<c;g++){var l=v[a>>2],n=v[a+
4>>2];a+=8;var m=Sb(e,p,l,n,f);if(0>m){var q=-1;break a}b+=m;if(m<n)break;"undefined"!=typeof f&&(f+=m)}q=b}v[d>>2]=q;return 0}catch(u){if("undefined"==typeof K||"ErrnoError"!==u.name)throw u;return u.Ic}},na:a=>S.activeTexture(a),t:(a,b)=>{S.attachShader(V[a],W[b])},e:(a,b)=>{if(b&&!U[b]){var c=S.createBuffer();c.name=b;U[b]=c}34962==a?S.bd=b:34963==a&&(S.jd=b);35051==a?S.Wd=b:35052==a&&(S.cd=b);S.bindBuffer(a,U[b])},oa:(a,b,c)=>{S.bindBufferBase(a,b,U[c])},ya:(a,b,c,d,e)=>{S.bindBufferRange(a,b,
U[c],d,e)},g:(a,b)=>{S.bindFramebuffer(a,Vc[b])},Ja:(a,b)=>{S.bindRenderbuffer(a,Wc[b])},w:(a,b)=>{S.bindSampler(a,$c[b])},h:(a,b)=>{S.bindTexture(a,Xc[b])},Q:a=>{S.bindVertexArray(Yc[a]);a=S.getParameter(34965);S.jd=a?a.name|0:0},B:(a,b,c,d)=>S.blendColor(a,b,c,d),C:(a,b)=>S.blendEquationSeparate(a,b),D:(a,b,c,d)=>S.blendFuncSeparate(a,b,c,d),bc:(a,b,c,d,e,f,g,l,n,m)=>S.blitFramebuffer(a,b,c,d,e,f,g,l,n,m),Va:(a,b,c,d)=>{2<=Y.version?c&&b?S.bufferData(a,r,d,c,b):S.bufferData(a,b,d):S.bufferData(a,
c?r.subarray(c,c+b):b,d)},u:(a,b,c,d)=>{2<=Y.version?c&&S.bufferSubData(a,b,r,d,c):S.bufferSubData(a,b,r.subarray(d,d+c))},Hb:a=>S.checkFramebufferStatus(a),Ga:(a,b,c,d)=>S.clearBufferfi(a,b,c,d),G:(a,b,c)=>{S.clearBufferfv(a,b,w,c>>2)},Fa:(a,b,c)=>{S.clearBufferiv(a,b,t,c>>2)},s:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Kb:a=>{S.compileShader(W[a])},Qb:(a,b,c,d,e,f,g,l,n)=>{2<=Y.version?S.cd||!l?S.compressedTexSubImage2D(a,b,c,d,e,f,g,l,n):S.compressedTexSubImage2D(a,b,c,d,e,f,g,r,n,l):S.compressedTexSubImage2D(a,
b,c,d,e,f,g,r.subarray(n,n+l))},Ob:(a,b,c,d,e,f,g,l,n,m,q)=>{S.cd?S.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,m,q):S.compressedTexSubImage3D(a,b,c,d,e,f,g,l,n,r,q,m)},Pa:()=>{var a=ed(V),b=S.createProgram();b.name=a;b.qd=b.od=b.pd=0;b.Od=1;V[a]=b;return a},Mb:a=>{var b=ed(W);W[b]=S.createShader(a);return b},A:a=>S.cullFace(a),Tb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=U[d];e&&(S.deleteBuffer(e),e.name=0,U[d]=null,d==S.bd&&(S.bd=0),d==S.jd&&(S.jd=0),d==S.Wd&&(S.Wd=0),d==S.cd&&(S.cd=0))}},
N:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Vc[d];e&&(S.deleteFramebuffer(e),e.name=0,Vc[d]=null)}},m:a=>{if(a){var b=V[a];b?(S.deleteProgram(b),b.name=0,V[a]=null):X||=1281}},Rb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Wc[d];e&&(S.deleteRenderbuffer(e),e.name=0,Wc[d]=null)}},Sb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=$c[d];e&&(S.deleteSampler(e),e.name=0,$c[d]=null)}},k:a=>{if(a){var b=W[a];b?(S.deleteShader(b),W[a]=null):X||=1281}},la:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+
4*c>>2],e=Xc[d];e&&(S.deleteTexture(e),e.name=0,Xc[d]=null)}},Xa:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];S.deleteVertexArray(Yc[d]);Yc[d]=null}},q:a=>S.depthFunc(a),r:a=>{S.depthMask(!!a)},b:a=>S.disable(a),x:a=>{Y.$c[a].enabled=!1;S.disableVertexAttribArray(a)},ec:(a,b,c)=>{jd(b+c);S.drawArrays(a,b,c);hd&&S.bindBuffer(34962,U[S.bd])},fc:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},I:(a,b)=>{for(var c=sd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];S.drawBuffers(c)},gc:(a,b,c,d)=>{var e=0;if(!S.jd){var f=
1*ad[c-5120]*b;var g=gd(f);S.bindBuffer(34963,g);S.bufferSubData(34963,0,r.subarray(d,d+f));if(0<b)for(g=0;g<Y.Gd;++g)if(f=Y.$c[g],f.ad&&f.enabled){switch(c){case 5121:e=Uint8Array;break;case 5123:e=Uint16Array;break;case 5125:e=Uint32Array;break;default:X||=1282;return}e=(new e(r.buffer,d,b)).reduce((l,n)=>Math.max(l,n))+1;break}d=0}jd(e);S.drawElements(a,b,c,d);hd&&S.bindBuffer(34962,U[S.bd]);S.jd||S.bindBuffer(34963,null)},hc:(a,b,c,d,e)=>{S.drawElementsInstanced(a,b,c,d,e)},f:a=>S.enable(a),za:a=>
{Y.$c[a].enabled=!0;S.enableVertexAttribArray(a)},j:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,Wc[d])},i:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,Xc[d],e)},Ib:(a,b,c,d,e)=>{S.framebufferTextureLayer(a,b,Xc[c],d,e)},z:a=>S.frontFace(a),Wa:(a,b)=>{fd(a,b,"createBuffer",U)},P:(a,b)=>{fd(a,b,"createFramebuffer",Vc)},Ka:(a,b)=>{fd(a,b,"createRenderbuffer",Wc)},Qa:(a,b)=>{fd(a,b,"createSampler",$c)},Ua:(a,b)=>{fd(a,b,"createTexture",Xc)},_a:(a,b)=>{fd(a,b,"createVertexArray",Yc)},La:(a,b)=>S.getAttribLocation(V[a],
A(b)),a:(a,b)=>ud(a,b),Oa:(a,b,c,d)=>{a=S.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},K:(a,b,c)=>{if(c)if(a>=Uc)X||=1281;else if(a=V[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.qd){var d=S.getProgramParameter(a,35718);for(b=0;b<d;++b)a.qd=Math.max(a.qd,S.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.qd}else if(35722==b){if(!a.od)for(d=S.getProgramParameter(a,35721),b=0;b<d;++b)a.od=
Math.max(a.od,S.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.od}else if(35381==b){if(!a.pd)for(d=S.getProgramParameter(a,35382),b=0;b<d;++b)a.pd=Math.max(a.pd,S.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.pd}else t[c>>2]=S.getProgramParameter(a,b);else X||=1281},Jb:(a,b,c,d)=>{a=S.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?B(a,r,d,b):0;c&&(t[c>>2]=b)},ja:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=
S.getShaderSource(W[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=S.getShaderParameter(W[a],b):X||=1281},Ya:(a,b)=>{if(2>Y.version)return X||=1282,0;var c=bd[a];if(c)return 0>b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=td().map(vd),c=bd[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},J:(a,b)=>{b=A(b);if(a=V[a]){var c=a,d=c.md,e=c.oe,f;if(!d){c.md=d={};c.ne={};var g=S.getProgramParameter(c,35718);for(f=0;f<g;++f){var l=S.getActiveUniform(c,f);var n=l.name;l=l.size;var m=
wd(n);m=0<m?n.slice(0,m):n;var q=c.Od;c.Od+=l;e[m]=[l,q];for(n=0;n<l;++n)d[q]=n,c.ne[q++]=m}}c=a.md;d=0;e=b;f=wd(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.oe[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else X||=1281;return-1},dc:(a,b,c)=>{for(var d=sd[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];S.invalidateFramebuffer(a,d)},L:a=>{a=V[a];S.linkProgram(a);a.md=0;a.oe={}},Za:(a,b)=>{3317==a?cd=b:3314==a&&(dd=b);S.pixelStorei(a,b)},E:(a,b)=>S.polygonOffset(a,b),cc:a=>
S.readBuffer(a),Ia:(a,b,c,d,e)=>S.renderbufferStorageMultisample(a,b,c,d,e),M:(a,b,c)=>{S.samplerParameterf($c[a],b,c)},d:(a,b,c)=>{S.samplerParameteri($c[a],b,c)},H:(a,b,c,d)=>S.scissor(a,b,c,d),Lb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=A(v[c+4*f>>2],d?v[d+4*f>>2]:void 0);S.shaderSource(W[a],e)},Vb:(a,b,c)=>S.stencilFunc(a,b,c),Ea:(a,b,c,d)=>S.stencilFuncSeparate(a,b,c,d),p:a=>S.stencilMask(a),Ub:(a,b,c)=>S.stencilOp(a,b,c),Da:(a,b,c,d)=>S.stencilOpSeparate(a,b,c,d),Ta:(a,b,c,d,e)=>S.texStorage2D(a,
b,c,d,e),Sa:(a,b,c,d,e,f)=>S.texStorage3D(a,b,c,d,e,f),Pb:(a,b,c,d,e,f,g,l,n)=>{if(2<=Y.version){if(S.cd){S.texSubImage2D(a,b,c,d,e,f,g,l,n);return}if(n){var m=xd(l);S.texSubImage2D(a,b,c,d,e,f,g,l,m,n>>>31-Math.clz32(m.BYTES_PER_ELEMENT));return}}if(n){m=xd(l);var q=f*((dd||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*m.BYTES_PER_ELEMENT+cd-1&-cd);n=m.subarray(n>>>31-Math.clz32(m.BYTES_PER_ELEMENT),n+q>>>31-Math.clz32(m.BYTES_PER_ELEMENT))}else n=null;S.texSubImage2D(a,
b,c,d,e,f,g,l,n)},Nb:(a,b,c,d,e,f,g,l,n,m,q)=>{if(S.cd)S.texSubImage3D(a,b,c,d,e,f,g,l,n,m,q);else if(q){var u=xd(m);S.texSubImage3D(a,b,c,d,e,f,g,l,n,m,u,q>>>31-Math.clz32(u.BYTES_PER_ELEMENT))}else S.texSubImage3D(a,b,c,d,e,f,g,l,n,m,null)},xa:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1fv(Z(a),w,c>>2,b);else{if(288>=b)for(var d=yd[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1fv(Z(a),d)}},Ma:(a,b)=>{S.uniform1i(Z(a),b)},mc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform1iv(Z(a),
t,c>>2,b);else{if(288>=b)for(var d=zd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);S.uniform1iv(Z(a),d)}},wa:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2fv(Z(a),w,c>>2,2*b);else{if(144>=b){b*=2;for(var d=yd[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);S.uniform2fv(Z(a),d)}},lc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform2iv(Z(a),t,c>>2,2*b);else{if(144>=b){b*=2;for(var d=zd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>
2,c+8*b>>2);S.uniform2iv(Z(a),d)}},va:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3fv(Z(a),w,c>>2,3*b);else{if(96>=b){b*=3;for(var d=yd[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);S.uniform3fv(Z(a),d)}},kc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform3iv(Z(a),t,c>>2,3*b);else{if(96>=b){b*=3;for(var d=zd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);S.uniform3iv(Z(a),d)}},ua:(a,
b,c)=>{if(2<=Y.version)b&&S.uniform4fv(Z(a),w,c>>2,4*b);else{if(72>=b){var d=yd[4*b],e=w;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);S.uniform4fv(Z(a),d)}},jc:(a,b,c)=>{if(2<=Y.version)b&&S.uniform4iv(Z(a),t,c>>2,4*b);else{if(72>=b){b*=4;for(var d=zd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);S.uniform4iv(Z(a),d)}},ic:(a,
b,c,d)=>{if(2<=Y.version)b&&S.uniformMatrix4fv(Z(a),!!c,w,d>>2,16*b);else{if(18>=b){var e=yd[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=w.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(Z(a),!!c,e)}},l:a=>{a=V[a];S.useProgram(a);S.re=a},Aa:(a,b)=>{S.vertexAttribDivisor(a,
b)},Ba:(a,b,c,d,e)=>{var f=Y.$c[a];S.bd?(f.ad=!1,S.vertexAttribIPointer(a,b,c,d,e)):(f.size=b,f.type=c,f.Id=!1,f.stride=d,f.kd=e,f.ad=!0,f.Pd=function(g,l,n,m,q,u){this.vertexAttribIPointer(g,l,n,q,u)})},Ca:(a,b,c,d,e,f)=>{var g=Y.$c[a];S.bd?(g.ad=!1,S.vertexAttribPointer(a,b,c,!!d,e,f)):(g.size=b,g.type=c,g.Id=d,g.stride=e,g.kd=f,g.ad=!0,g.Pd=function(l,n,m,q,u,x){this.vertexAttribPointer(l,n,m,q,u,x)})},Ha:(a,b,c,d)=>S.viewport(a,b,c,d),Eb:function(a,b,c,d,e,f,g){var l=globalThis.CowPlatform;if(!l)return-1;
try{return l.call(a,b,c,d?A(d,e):null,f?A(f,g):null)|0}catch(n){return-1}},Db:function(){var a=globalThis.CowPlatform.cur;return a?a.c|0:0},Cb:function(){var a=globalThis.CowPlatform.cur;return a&&null!=a.s?vd(a.s):0},Bb:function(a){var b=globalThis.CowPlatform;if(!b)return 0;a=b.getStr(a);return null==a||""===a?0:vd(a)},ia:function(){var a=globalThis.CowPlatform;if(!a)return-1;var b=a.queue;if(0===b.length)return-1;a.cur=b.shift();return a.cur.k|0},Gb:function(){try{var a=globalThis.localStorage;
if(!a)return 0;var b=a.getItem("ScopeBee.PlayerPrefs");return null===b?0:vd(b)}catch(c){return 0}},Fb:function(a,b){try{var c=globalThis.localStorage;c&&c.setItem("ScopeBee.PlayerPrefs",A(a,b))}catch(d){}},ob:cc,hb:function(){h.he=a=>{0!=Md()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.he)},gb:function(){h.me=a=>{const b=a.clipboardData.getData("text");Ed(()=>{const c=Bd(b);Ld(c)})};window.addEventListener("paste",h.me)},fb:function(){h.rf=[];h.ie=b=>{b.stopPropagation();
b.preventDefault()};h.je=b=>{b.stopPropagation();b.preventDefault()};h.ke=b=>{b.stopPropagation();b.preventDefault()};h.le=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.sf=c;Nd(c.length);for(let e=0;e<c.length;e++)Ed(()=>{const f=Bd(c[e].name);Od(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Pd(b.clientX,b.clientY,d)};const a=h.Xc;a.addEventListener("dragenter",h.ie,!1);a.addEventListener("dragleave",h.je,!1);a.addEventListener("dragover",
h.ke,!1);a.addEventListener("drop",h.le,!1)},ab:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},bb:function(a){h.xd&&(URL.revokeObjectURL(h.xd[a].Je),h.xd[a]=null)},nc:function(a,b){0!==b&&(document.title=A(b));a=A(a);void 0!==h.canvas&&("object"===typeof h.canvas?Cc[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Xc=L(a);h.Xc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Xc.requestPointerLock||
console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Zb:function(){window.removeEventListener("beforeunload",h.he)},Yb:function(){window.removeEventListener("paste",h.me)},Xb:function(){const a=h.Xc;a.removeEventListener("dragenter",h.ie);a.removeEventListener("dragleave",h.je);a.removeEventListener("dragover",h.ke);a.removeEventListener("drop",h.le)},Wb:function(){h.Xc&&h.Xc.requestPointerLock&&h.Xc.requestPointerLock()},cb:function(a,b,c){if(h.Xc){if(0===b)a="none";else if(0!=
c)a=h.xd[a].Qe;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Xc.style.cursor=a}},$a:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(r.subarray(c,
c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},qa:function(a,b){b=A(b);switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function Td(a=[]){var b=Qd;a.unshift(ea);var c=a.length,d=Ad(4*(c+1)),e=d,f;for(f of a)v[e>>2]=Bd(f),e+=4;v[e>>2]=0;try{var g=b(c,d);pa=g;cc(g)}catch(l){bc(l)}}
function Ud(a=da){function b(){h.calledRun=!0;if(!oa){if(!h.noFSInit&&!qb){var c,d;qb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Wb("/dev","stdin",c):Lb("/dev/tty","/dev/stdin");d?Wb("/dev","stdout",null,d):Lb("/dev/tty","/dev/stdout");e?Wb("/dev","stderr",null,e):Lb("/dev/tty1","/dev/stderr");Pb("/dev/stdin",0);Pb("/dev/stdout",1);Pb("/dev/stderr",1)}Vd.pc();rb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Td(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ba.push(e)}Aa(Ba)}}if(0<Ea)Fa=Ud;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<Ea?Fa=Ud:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}var Vd;
(async function(){function a(c){c=Vd=c.exports;Ld=h.__sapp_emsc_onpaste=c.qc;Md=h.__sapp_html5_get_ask_leave_site=c.sc;Nd=h.__sapp_emsc_begin_drop=c.tc;Od=h.__sapp_emsc_drop=c.uc;Pd=h.__sapp_emsc_end_drop=c.vc;h.__sapp_emsc_invoke_fetch_cb=c.wc;h.__sapp_emsc_set_fullscreen_flag=c.xc;Q=c.yc;Qd=h._main=c.zc;Rd=c.Ac;Dd=c.Bc;Ad=c.Cc;Cd=c.Dc;ua=c.oc;R=c.rc;ta();Ga("wasm-instantiate");return Vd}Ha("wasm-instantiate");var b={a:Sd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,
e))})});va??=h.locateFile?h.locateFile("index.wasm",ia):ia+"index.wasm";return a((await ya(b)).instance)})();Ud();
